import type { CareFinderLang } from "../../../shared/careFinder/careRoutes";

type Copy = ReturnType<typeof englishCopy>;

function englishCopy() {
  return {
    title: "Find the right care",
    back: "Back",
    pause: "Finish later",
    readAloud: "Read this to me",
    stopReading: "Stop reading",
    loading: "Loading your search…",
    closed: "That search was already finished, so we've started a fresh one.",
    saving: "Saving…",
    saved: "Your answers are saved",
    savedOffline: "Saved on this device. We'll sync when you're back online.",
    notDiagnosis: "VYVA helps you find care. It does not diagnose.",
    intro: "Tell us what's going on and we'll help you find the right kind of care nearby. Nothing is shared or booked without your OK.",
    resume: {
      title: "Continue where you left off?",
      body: (about: string, when: string) => `You were looking for care${about ? ` about ${about}` : ""} on ${when}.`,
      continue: "Continue my search",
      startNew: "Start a new search",
    },
    legacy: (when: string | null) => `You started this search${when ? ` on ${when}` : ""}. We've improved how VYVA searches for health care, so we'll ask a few quick questions to find better options. We've kept your description.`,
    who: {
      question: "Who needs care?",
      self: "For me",
      selfDetail: "I'm looking for myself",
      other: "For someone I'm helping",
      otherDetail: "A parent, partner or friend",
    },
    need: {
      question: (self: boolean): string => self ? "What's bothering you?" : "What's bothering them?",
      help: "Choose the closest, or describe it in your own words.",
      unmatched: "Thank you, we've kept your words. Which of these is closest?",
      inputLabel: "Describe it in your own words",
      placeholder: "For example: my knee hurts on the stairs",
      submit: "Use my description",
      orChoose: "Or choose one",
    },
    area: {
      question: "Where do you notice it most?",
      help: "If nothing fits, choose \"Still not sure\". A family doctor is the right first step then.",
    },
    describe: {
      question: "Tell us what's going on",
      help: "A few words are enough. You can type or speak.",
    },
    voice: {
      speak: "Speak instead of typing",
      stop: "Stop listening",
      listening: "Listening… speak now",
    },
    safety: {
      question: (self: boolean): string => self ? "Is any of this happening right now?" : "Is any of this happening to them right now?",
      help: "Tap one if it is. Otherwise tap \"None of these\".",
      none: "None of these are happening",
    },
    urgent: {
      title: "This may need help right now",
      body: "If this is happening now, please don't wait for an appointment.",
      unsure: "If you're not sure, calling is the safe choice.",
      notNow: "It's not happening right now. Continue",
      selfHarm: "You don't have to face this alone. People are ready to listen, right now.",
    },
    timing: {
      question: (self: boolean): string => self ? "How soon would you like to be seen?" : "How soon would they like to be seen?",
    },
    profile: {
      question: "Shall we use what VYVA already knows?",
      help: "Only for this search. Nothing is shared with anyone.",
      cover: "Health cover",
      place: "Search near",
      usualDoctor: "Usual doctor",
      notSaved: "Not saved yet",
      accept: "Yes, use these",
      change: "Change something",
    },
    coverage: {
      question: (self: boolean): string => self ? "How is your health care paid for?" : "How is their health care paid for?",
      help: "This decides where to start. In the public system, the family doctor is usually the first step.",
    },
    location: {
      question: "Where should we look?",
      help: "A town, neighbourhood or postcode. Used only to find places nearby.",
      label: "Town or postcode",
      submit: "Look near this place",
    },
    route: {
      question: "Where to start",
      help: "Based on what you've told us, this is where people usually start. It isn't a diagnosis.",
      suggested: "A good place to start",
      alternative: "Another option",
      choose: (label: string) => `Look for ${label.toLowerCase()}`,
      publicAccess: "Public system",
      privateAccess: "Private, usually paid or insured",
      notSure: "I'm still not sure. Start with a family doctor",
    },
    access: {
      question: "Anything that would make it easier?",
      help: "Choose any that apply. We'll use them in the search and when you call.",
      suggestedNote: "We selected \"No stairs\" because you mentioned difficulty with stairs or walking. Tap it to remove.",
      show: (label: string, place: string) => `Show ${label.toLowerCase()} near ${place}`,
    },
    results: {
      loading: (label: string, place: string) => `Looking for ${label.toLowerCase()} near ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "option" : "options"} for ${label.toLowerCase()} near ${place}`,
      orderTravel: "Closest first. This order is not a quality ranking.",
      orderRelevance: "In the order Google Maps returned them. This is not a quality ranking.",
      legendTitle: "How to read these",
      checked: "Checked",
      checkedDetail: "On the place's own website",
      google: "From Google Maps",
      googleDetail: "Listed by Google. Usually right, worth confirming",
      unknown: "Not known",
      unknownDetail: "Ask when you call",
      why: "Why it's here",
      goodToKnow: "Good to know (VYVA's general understanding, not checked for this place)",
      prepare: (name: string) => `Prepare to contact ${name}`,
      openMap: "Open in Google Maps",
      compare: "Compare side by side",
      hideCompare: "Hide comparison",
      usualDoctorTitle: "Your usual doctor",
      usualDoctorDetail: "Saved in your VYVA profile",
      changeAnswers: "Change my answers",
      checkedOn: (when: string) => `Information collected ${when}`,
      noResults: (label: string, place: string) => `We didn't find any ${label.toLowerCase()} near ${place} that we could check.`,
      unavailable: "The search isn't available right now. Nothing has been lost.",
      error: "We couldn't search just now. Your answers are saved.",
      offline: "You seem to be offline. Your answers are saved on this device.",
      retry: "Try the search again",
      tryPlace: "Try a different place",
      tryCare: "Try another kind of care",
      mapsYourself: "Search Google Maps yourself (not checked by VYVA)",
      callUsual: (name: string) => `Call ${name}`,
      facts: {
        distance: "Getting there",
        availability: "Open today",
        accessibility: "Step-free access",
        coverage: "Accepts your cover",
        price: "Price",
        reputation: "Google reviews",
      },
    },
    contact: {
      heading: (name: string) => `Before you contact ${name}`,
      intro: "VYVA doesn't send anything. You decide what to say and when.",
      scriptTitle: "What you could say",
      scriptTranslated: "Said in Spanish, with the English meaning underneath.",
      askTitle: "Questions worth asking",
      shareTitle: "What you'll share",
      shareHelp: "Untick anything you'd rather keep to yourself.",
      shareReason: "Why you need care",
      shareCoverage: "How it's paid for",
      shareAccess: "Access needs",
      shareCompanion: "That someone will come along",
      call: (name: string) => `Call ${name}`,
      noPhone: "No phone number was found for this place.",
      website: "Open their website",
      bookingLink: "Open their booking page",
      confirmTitle: (name: string) => `Call ${name}?`,
      confirmBody: (phone: string) => `Your phone will call ${phone}. VYVA doesn't listen to or record the call.`,
      confirmYes: "Yes, call now",
      confirmNo: "Not yet",
      shareTitleHelper: "Share with someone I trust",
      shareIntro: "This exact message will be shared. Nothing is sent until you choose who to send it to.",
      shareButton: "Choose who to send it to",
      sharePreviewButton: "See the message first",
      copyButton: "Copy the message",
      copied: "Message copied",
      ride: "Arrange a ride there with VYVA",
      rideNote: "You'll confirm the details before anything is booked.",
      outcomeTitle: "How did it go?",
      outcomes: {
        booked: "I booked an appointment",
        call_back: "They'll call me back",
        no_answer: "No answer. I'll try later",
        not_suitable: "It wasn't right. Show other options",
      },
      otherOptions: "Back to the options",
    },
    done: {
      booked: "Well done. This search is complete.",
      bookedNext: "We've closed this search. You can always start a new one.",
      later: "We've kept this search saved, so you can come back to it.",
      health: "Back to Health",
      newSearch: "Start a new search",
      resume: "Back to my options",
    },
    summary: {
      title: "What VYVA understands",
      empty: "Your answers will appear here.",
      change: "Change",
      for: "For",
      self: "You",
      other: "Someone you're helping",
      words: "In your words",
      about: "About",
      warnings: "Warning signs",
      warningsNone: "None right now",
      warningsSeen: "You said it's not happening right now",
      soon: "How soon",
      cover: "Health cover",
      place: "Looking near",
      lookingFor: "Looking for",
      access: "Getting there",
      accessNone: "Nothing extra",
      show: "Show my answers",
      hide: "Hide my answers",
    },
    disclaimer: "VYVA helps you find care. It does not diagnose. In an emergency, call 112.",
  };
}

function spanishCopy(): Copy {
  return {
    title: "Encontrar la atención adecuada",
    back: "Atrás",
    pause: "Seguir luego",
    readAloud: "Léamelo",
    stopReading: "Dejar de leer",
    loading: "Cargando su búsqueda…",
    closed: "Esa búsqueda ya estaba terminada, así que empezamos una nueva.",
    saving: "Guardando…",
    saved: "Sus respuestas están guardadas",
    savedOffline: "Guardado en este dispositivo. Se sincronizará al recuperar la conexión.",
    notDiagnosis: "VYVA le ayuda a encontrar atención. No hace diagnósticos.",
    intro: "Cuéntenos qué pasa y le ayudamos a encontrar el tipo de atención adecuado cerca. No se comparte ni se reserva nada sin su permiso.",
    resume: {
      title: "¿Seguimos donde lo dejó?",
      body: (about: string, when: string) => `Estaba buscando atención${about ? ` por ${about}` : ""} el ${when}.`,
      continue: "Seguir con mi búsqueda",
      startNew: "Empezar una búsqueda nueva",
    },
    legacy: (when: string | null) => `Empezó esta búsqueda${when ? ` el ${when}` : ""}. Hemos mejorado cómo VYVA busca atención sanitaria, así que le haremos unas preguntas rápidas para encontrar mejores opciones. Hemos guardado su descripción.`,
    who: {
      question: "¿Para quién es la atención?",
      self: "Para mí",
      selfDetail: "Busco para mí",
      other: "Para alguien a quien ayudo",
      otherDetail: "Un familiar, pareja o amigo",
    },
    need: {
      question: (self: boolean): string => self ? "¿Qué le pasa?" : "¿Qué le pasa a esa persona?",
      help: "Elija lo más parecido o descríbalo con sus palabras.",
      unmatched: "Gracias, hemos guardado sus palabras. ¿Cuál de estas se parece más?",
      inputLabel: "Descríbalo con sus palabras",
      placeholder: "Por ejemplo: me duele la rodilla al subir escaleras",
      submit: "Usar mi descripción",
      orChoose: "O elija una opción",
    },
    area: {
      question: "¿Dónde lo nota más?",
      help: "Si nada encaja, elija \"Sigo sin estar seguro\". Entonces el médico de familia es el primer paso.",
    },
    describe: {
      question: "Cuéntenos qué pasa",
      help: "Con unas palabras basta. Puede escribir o hablar.",
    },
    voice: {
      speak: "Hablar en lugar de escribir",
      stop: "Dejar de escuchar",
      listening: "Escuchando… hable ahora",
    },
    safety: {
      question: (self: boolean): string => self ? "¿Le está pasando algo de esto ahora mismo?" : "¿Le está pasando algo de esto a esa persona ahora mismo?",
      help: "Pulse una si es así. Si no, pulse \"No pasa nada de esto\".",
      none: "No pasa nada de esto",
    },
    urgent: {
      title: "Esto puede necesitar ayuda ahora mismo",
      body: "Si está pasando ahora, no espere a una cita.",
      unsure: "Si no está seguro, llamar es lo más seguro.",
      notNow: "No está pasando ahora. Continuar",
      selfHarm: "No tiene que pasar por esto solo. Hay personas dispuestas a escucharle, ahora mismo.",
    },
    timing: {
      question: (self: boolean): string => self ? "¿Cuándo le gustaría que le vieran?" : "¿Cuándo le gustaría que le vieran a esa persona?",
    },
    profile: {
      question: "¿Usamos lo que VYVA ya sabe?",
      help: "Solo para esta búsqueda. No se comparte con nadie.",
      cover: "Cobertura",
      place: "Buscar cerca de",
      usualDoctor: "Médico habitual",
      notSaved: "Aún no guardado",
      accept: "Sí, usar estos datos",
      change: "Cambiar algo",
    },
    coverage: {
      question: (self: boolean): string => self ? "¿Cómo se paga su atención sanitaria?" : "¿Cómo se paga la atención sanitaria de esa persona?",
      help: "Esto decide por dónde empezar. En la sanidad pública, el médico de familia suele ser el primer paso.",
    },
    location: {
      question: "¿Dónde buscamos?",
      help: "Un pueblo, barrio o código postal. Solo se usa para encontrar sitios cercanos.",
      label: "Pueblo o código postal",
      submit: "Buscar cerca de aquí",
    },
    route: {
      question: "Por dónde empezar",
      help: "Según lo que nos ha contado, aquí es donde se suele empezar. No es un diagnóstico.",
      suggested: "Un buen punto de partida",
      alternative: "Otra opción",
      choose: (label: string) => `Buscar ${label.toLowerCase()}`,
      publicAccess: "Sanidad pública",
      privateAccess: "Privado, normalmente de pago o con seguro",
      notSure: "Sigo sin estar seguro. Empezar por el médico de familia",
    },
    access: {
      question: "¿Algo que se lo ponga más fácil?",
      help: "Elija lo que necesite. Lo usaremos en la búsqueda y al llamar.",
      suggestedNote: "Hemos marcado \"Sin escaleras\" porque mencionó dificultad con escaleras o al caminar. Púlselo para quitarlo.",
      show: (label: string, place: string) => `Ver ${label.toLowerCase()} cerca de ${place}`,
    },
    results: {
      loading: (label: string, place: string) => `Buscando ${label.toLowerCase()} cerca de ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "opción" : "opciones"} de ${label.toLowerCase()} cerca de ${place}`,
      orderTravel: "La más cercana primero. Este orden no es una valoración de calidad.",
      orderRelevance: "En el orden que dio Google Maps. No es una valoración de calidad.",
      legendTitle: "Cómo leer esto",
      checked: "Comprobado",
      checkedDetail: "En la web del propio sitio",
      google: "Según Google Maps",
      googleDetail: "Publicado por Google. Suele ser correcto, conviene confirmarlo",
      unknown: "No se sabe",
      unknownDetail: "Pregúntelo al llamar",
      why: "Por qué aparece",
      goodToKnow: "Conviene saber (información general de VYVA, no comprobada para este sitio)",
      prepare: (name: string) => `Preparar el contacto con ${name}`,
      openMap: "Abrir en Google Maps",
      compare: "Comparar una al lado de otra",
      hideCompare: "Ocultar comparación",
      usualDoctorTitle: "Su médico habitual",
      usualDoctorDetail: "Guardado en su perfil de VYVA",
      changeAnswers: "Cambiar mis respuestas",
      checkedOn: (when: string) => `Información recogida ${when}`,
      noResults: (label: string, place: string) => `No hemos encontrado ${label.toLowerCase()} cerca de ${place} que podamos comprobar.`,
      unavailable: "La búsqueda no está disponible ahora mismo. No se ha perdido nada.",
      error: "No hemos podido buscar ahora. Sus respuestas están guardadas.",
      offline: "Parece que no hay conexión. Sus respuestas están guardadas en este dispositivo.",
      retry: "Volver a buscar",
      tryPlace: "Probar otro lugar",
      tryCare: "Probar otro tipo de atención",
      mapsYourself: "Buscar usted mismo en Google Maps (no comprobado por VYVA)",
      callUsual: (name: string) => `Llamar a ${name}`,
      facts: {
        distance: "Cómo llegar",
        availability: "Abierto hoy",
        accessibility: "Acceso sin escalones",
        coverage: "Acepta su cobertura",
        price: "Precio",
        reputation: "Opiniones en Google",
      },
    },
    contact: {
      heading: (name: string) => `Antes de contactar con ${name}`,
      intro: "VYVA no envía nada. Usted decide qué decir y cuándo.",
      scriptTitle: "Lo que puede decir",
      scriptTranslated: "En español, con el significado en inglés debajo.",
      askTitle: "Preguntas que conviene hacer",
      shareTitle: "Lo que va a compartir",
      shareHelp: "Desmarque lo que prefiera no contar.",
      shareReason: "Por qué necesita atención",
      shareCoverage: "Cómo se paga",
      shareAccess: "Necesidades de acceso",
      shareCompanion: "Que irá acompañado",
      call: (name: string) => `Llamar a ${name}`,
      noPhone: "No hemos encontrado un teléfono para este sitio.",
      website: "Abrir su web",
      bookingLink: "Abrir su página de citas",
      confirmTitle: (name: string) => `¿Llamar a ${name}?`,
      confirmBody: (phone: string) => `Su teléfono llamará al ${phone}. VYVA no escucha ni graba la llamada.`,
      confirmYes: "Sí, llamar ahora",
      confirmNo: "Todavía no",
      shareTitleHelper: "Compartir con alguien de confianza",
      shareIntro: "Se compartirá exactamente este mensaje. No se envía nada hasta que elija a quién.",
      shareButton: "Elegir a quién enviarlo",
      sharePreviewButton: "Ver primero el mensaje",
      copyButton: "Copiar el mensaje",
      copied: "Mensaje copiado",
      ride: "Organizar el transporte con VYVA",
      rideNote: "Confirmará los detalles antes de reservar nada.",
      outcomeTitle: "¿Cómo ha ido?",
      outcomes: {
        booked: "He pedido cita",
        call_back: "Me van a llamar",
        no_answer: "No contestan. Lo intentaré luego",
        not_suitable: "No era lo adecuado. Ver otras opciones",
      },
      otherOptions: "Volver a las opciones",
    },
    done: {
      booked: "Muy bien. Esta búsqueda está completa.",
      bookedNext: "Hemos cerrado esta búsqueda. Puede empezar otra cuando quiera.",
      later: "Hemos guardado esta búsqueda para que pueda volver a ella.",
      health: "Volver a Salud",
      newSearch: "Empezar una búsqueda nueva",
      resume: "Volver a mis opciones",
    },
    summary: {
      title: "Lo que VYVA ha entendido",
      empty: "Aquí aparecerán sus respuestas.",
      change: "Cambiar",
      for: "Para",
      self: "Usted",
      other: "Alguien a quien ayuda",
      words: "Con sus palabras",
      about: "Sobre",
      warnings: "Señales de alarma",
      warningsNone: "Ninguna ahora",
      warningsSeen: "Ha dicho que no está pasando ahora",
      soon: "Cuándo",
      cover: "Cobertura",
      place: "Buscando cerca de",
      lookingFor: "Buscando",
      access: "Para llegar",
      accessNone: "Nada especial",
      show: "Ver mis respuestas",
      hide: "Ocultar mis respuestas",
    },
    disclaimer: "VYVA le ayuda a encontrar atención. No hace diagnósticos. En una emergencia, llame al 112.",
  };
}

export type CareFinderCopy = Copy;

export function careFinderCopy(lang: CareFinderLang): CareFinderCopy {
  return lang === "es" ? spanishCopy() : englishCopy();
}
