import type { CareFinderLang } from "../../../shared/careFinder/careRoutes";

type Copy = ReturnType<typeof englishCopy>;

function englishCopy() {
  return {
    title: "Find the right care",
    back: "Back",
    pause: "Finish later",
    readAloud: "Read this to me",
    stopReading: "Stop reading",
    loading: "Loading your search…",
    closed: "That search was already finished, so we've started a fresh one.",
    saving: "Saving…",
    saved: "Your answers are saved",
    savedOffline: "Saved on this device. We'll sync when you're back online.",
    notDiagnosis: "VYVA helps you find care. It does not diagnose.",
    intro: "Tell us what's going on and we'll help you find the right kind of care nearby. Nothing is shared or booked without your OK.",
    resume: {
      title: "Continue where you left off?",
      body: (about: string, when: string) => `You were looking for care${about ? ` about ${about}` : ""} on ${when}.`,
      continue: "Continue my search",
      startNew: "Start a new search",
    },
    legacy: (when: string | null) => `You started this search${when ? ` on ${when}` : ""}. We've improved how VYVA searches for health care, so we'll ask a few quick questions to find better options. We've kept your description.`,
    who: {
      question: "Who needs care?",
      self: "For me",
      selfDetail: "I'm looking for myself",
      other: "For someone I'm helping",
      otherDetail: "A parent, partner or friend",
    },
    need: {
      question: (self: boolean): string => self ? "What's bothering you?" : "What's bothering them?",
      help: "Choose the closest, or describe it in your own words.",
      unmatched: "Thank you, we've kept your words. Which of these is closest?",
      inputLabel: "Describe it in your own words",
      placeholder: "For example: my knee hurts on the stairs",
      submit: "Use my description",
      orChoose: "Or choose one",
    },
    area: {
      question: "Where do you notice it most?",
      help: "If nothing fits, choose \"Still not sure\". A family doctor is the right first step then.",
    },
    describe: {
      question: "Tell us what's going on",
      help: "A few words are enough. You can type or speak.",
    },
    voice: {
      speak: "Speak instead of typing",
      stop: "Stop listening",
      listening: "Listening… speak now",
    },
    safety: {
      question: (self: boolean): string => self ? "Is any of this happening right now?" : "Is any of this happening to them right now?",
      help: "Tap one if it is. Otherwise tap \"None of these\".",
      none: "None of these are happening",
    },
    urgent: {
      title: "This may need help right now",
      body: "If this is happening now, please don't wait for an appointment.",
      unsure: "If you're not sure, calling is the safe choice.",
      notNow: "It's not happening right now. Continue",
      selfHarm: "You don't have to face this alone. People are ready to listen, right now.",
    },
    timing: {
      question: (self: boolean): string => self ? "How soon would you like to be seen?" : "How soon would they like to be seen?",
    },
    profile: {
      question: "Shall we use what VYVA already knows?",
      help: "Only for this search. Nothing is shared with anyone.",
      cover: "Health cover",
      place: "Search near",
      usualDoctor: "Usual doctor",
      notSaved: "Not saved yet",
      accept: "Yes, use these",
      change: "Change something",
    },
    coverage: {
      question: (self: boolean): string => self ? "How is your health care paid for?" : "How is their health care paid for?",
      help: "This decides where to start. In the public system, the family doctor is usually the first step.",
    },
    location: {
      question: "Where should we look?",
      help: "A town, neighbourhood or postcode. Used only to find places nearby.",
      label: "Town or postcode",
      submit: "Look near this place",
    },
    route: {
      question: "Where to start",
      help: "Based on what you've told us, this is where people usually start. It isn't a diagnosis.",
      suggested: "A good place to start",
      alternative: "Another option",
      choose: (label: string) => `Look for ${label.toLowerCase()}`,
      publicAccess: "Public system",
      privateAccess: "Private, usually paid or insured",
      notSure: "I'm still not sure. Start with a family doctor",
    },
    access: {
      question: "Anything that would make it easier?",
      help: "Choose any that apply. We'll use them in the search and when you call.",
      suggestedNote: "We selected \"No stairs\" because you mentioned difficulty with stairs or walking. Tap it to remove.",
      show: (label: string, place: string) => `Show ${label.toLowerCase()} near ${place}`,
    },
    results: {
      loading: (label: string, place: string) => `Looking for ${label.toLowerCase()} near ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "option" : "options"} for ${label.toLowerCase()} near ${place}`,
      orderTravel: "Closest first. This order is not a quality ranking.",
      orderDistanceTown: "Closest first, in a straight line from your address, then other places in your town whose distance we don't know yet. Only places authorised in the official register of health centres are shown. This order is not a quality ranking.",
      orderDistance: "Closest first, in a straight line from your address. Only places authorised in the official register of health centres are shown. This order is not a quality ranking.",
      orderRelevance: "In the order Google Maps returned them. This is not a quality ranking.",
      legendTitle: "How to read these",
      checked: "Checked",
      checkedDetail: "In an official register, or on the place's own website",
      orderAssigned: "Your own health centre first, then the closest others. This order is not a quality ranking.",
      publicTitle: "Your health centre",
      publicHealthMap: (name: string, source: string) => `${name} is the centre for your area on the health map published by ${source}.`,
      publicNearest: (name: string) => `${name} is the closest public health centre to you. Your own centre is printed on your health card. If it's a different one, use that one.`,
      publicUnknown: "Your own health centre is printed on your health card.",
      bookOnline: (service: string) => `Book online: ${service}`,
      bookNotListed: "We don't have your region's online booking page yet. You can call your health centre to book.",
      opensOfficialSite: "opens the official website",
      badgeHealthMap: "Your health centre",
      badgeNearest: "Closest public health centre",
      google: "From Google Maps",
      googleDetail: "Listed by Google. Usually right, worth confirming",
      unknown: "Not known",
      unknownDetail: "Ask when you call",
      why: "Why it's here",
      goodToKnow: "Good to know (VYVA's general understanding, not checked for this place)",
      prepare: (name: string) => `Prepare to contact ${name}`,
      openMap: "Open in Google Maps",
      compare: "Compare side by side",
      hideCompare: "Hide comparison",
      usualDoctorTitle: "Your usual doctor",
      usualDoctorDetail: "Saved in your VYVA profile",
      changeAnswers: "Change my answers",
      checkedOn: (when: string) => `Information collected ${when}`,
      noResults: (label: string, place: string) => `We didn't find any ${label.toLowerCase()} near ${place} that we could check.`,
      unavailable: "The search isn't available right now. Nothing has been lost.",
      error: "We couldn't search just now. Your answers are saved.",
      offline: "You seem to be offline. Your answers are saved on this device.",
      retry: "Try the search again",
      tryPlace: "Try a different place",
      tryCare: "Try another kind of care",
      mapsYourself: "Search Google Maps yourself (not checked by VYVA)",
      callUsual: (name: string) => `Call ${name}`,
      facts: {
        distance: "Getting there",
        availability: "Open today",
        accessibility: "Step-free access",
        coverage: "Accepts your cover",
        price: "Price",
        reputation: "Google reviews",
      },
    },
    contact: {
      heading: (name: string) => `Before you contact ${name}`,
      intro: "VYVA doesn't send anything. You decide what to say and when.",
      scriptTitle: "What you could say",
      scriptTranslated: "Said in Spanish, with the English meaning underneath.",
      askTitle: "Questions worth asking",
      shareTitle: "What you'll share",
      shareHelp: "Untick anything you'd rather keep to yourself.",
      shareReason: "Why you need care",
      shareCoverage: "How it's paid for",
      shareAccess: "Access needs",
      shareCompanion: "That someone will come along",
      call: (name: string) => `Call ${name}`,
      noPhone: "No phone number was found for this place.",
      website: "Open their website",
      email: "Email them",
      bookingLink: "Open their booking page",
      confirmTitle: (name: string) => `Call ${name}?`,
      confirmBody: (phone: string) => `Your phone will call ${phone}. VYVA doesn't listen to or record the call.`,
      confirmYes: "Yes, call now",
      confirmNo: "Not yet",
      shareTitleHelper: "Share with someone I trust",
      shareIntro: "This exact message will be shared. Nothing is sent until you choose who to send it to.",
      shareButton: "Choose who to send it to",
      sharePreviewButton: "See the message first",
      copyButton: "Copy the message",
      copied: "Message copied",
      ride: "Arrange a ride there with VYVA",
      rideNote: "You'll confirm the details before anything is booked.",
      outcomeTitle: "How did it go?",
      outcomes: {
        booked: "I booked an appointment",
        call_back: "They'll call me back",
        no_answer: "No answer. I'll try later",
        not_suitable: "It wasn't right. Show other options",
      },
      otherOptions: "Back to the options",
    },
    done: {
      booked: "Well done. This search is complete.",
      bookedNext: "We've closed this search. You can always start a new one.",
      later: "We've kept this search saved, so you can come back to it.",
      health: "Back to Health",
      newSearch: "Start a new search",
      resume: "Back to my options",
    },
    summary: {
      title: "What VYVA understands",
      empty: "Your answers will appear here.",
      change: "Change",
      for: "For",
      self: "You",
      other: "Someone you're helping",
      words: "In your words",
      about: "About",
      warnings: "Warning signs",
      warningsNone: "None right now",
      warningsSeen: "You said it's not happening right now",
      soon: "How soon",
      cover: "Health cover",
      place: "Looking near",
      lookingFor: "Looking for",
      access: "Getting there",
      accessNone: "Nothing extra",
      show: "Show my answers",
      hide: "Hide my answers",
    },
    disclaimer: "VYVA helps you find care. It does not diagnose. In an emergency, call 112.",
  };
}

function spanishCopy(): Copy {
  return {
    title: "Encontrar la atención adecuada",
    back: "Atrás",
    pause: "Seguir luego",
    readAloud: "Léamelo",
    stopReading: "Dejar de leer",
    loading: "Cargando su búsqueda…",
    closed: "Esa búsqueda ya estaba terminada, así que empezamos una nueva.",
    saving: "Guardando…",
    saved: "Sus respuestas están guardadas",
    savedOffline: "Guardado en este dispositivo. Se sincronizará al recuperar la conexión.",
    notDiagnosis: "VYVA le ayuda a encontrar atención. No hace diagnósticos.",
    intro: "Cuéntenos qué pasa y le ayudamos a encontrar el tipo de atención adecuado cerca. No se comparte ni se reserva nada sin su permiso.",
    resume: {
      title: "¿Seguimos donde lo dejó?",
      body: (about: string, when: string) => `Estaba buscando atención${about ? ` por ${about}` : ""} el ${when}.`,
      continue: "Seguir con mi búsqueda",
      startNew: "Empezar una búsqueda nueva",
    },
    legacy: (when: string | null) => `Empezó esta búsqueda${when ? ` el ${when}` : ""}. Hemos mejorado cómo VYVA busca atención sanitaria, así que le haremos unas preguntas rápidas para encontrar mejores opciones. Hemos guardado su descripción.`,
    who: {
      question: "¿Para quién es la atención?",
      self: "Para mí",
      selfDetail: "Busco para mí",
      other: "Para alguien a quien ayudo",
      otherDetail: "Un familiar, pareja o amigo",
    },
    need: {
      question: (self: boolean): string => self ? "¿Qué le pasa?" : "¿Qué le pasa a esa persona?",
      help: "Elija lo más parecido o descríbalo con sus palabras.",
      unmatched: "Gracias, hemos guardado sus palabras. ¿Cuál de estas se parece más?",
      inputLabel: "Descríbalo con sus palabras",
      placeholder: "Por ejemplo: me duele la rodilla al subir escaleras",
      submit: "Usar mi descripción",
      orChoose: "O elija una opción",
    },
    area: {
      question: "¿Dónde lo nota más?",
      help: "Si nada encaja, elija \"Sigo sin estar seguro\". Entonces el médico de familia es el primer paso.",
    },
    describe: {
      question: "Cuéntenos qué pasa",
      help: "Con unas palabras basta. Puede escribir o hablar.",
    },
    voice: {
      speak: "Hablar en lugar de escribir",
      stop: "Dejar de escuchar",
      listening: "Escuchando… hable ahora",
    },
    safety: {
      question: (self: boolean): string => self ? "¿Le está pasando algo de esto ahora mismo?" : "¿Le está pasando algo de esto a esa persona ahora mismo?",
      help: "Pulse una si es así. Si no, pulse \"No pasa nada de esto\".",
      none: "No pasa nada de esto",
    },
    urgent: {
      title: "Esto puede necesitar ayuda ahora mismo",
      body: "Si está pasando ahora, no espere a una cita.",
      unsure: "Si no está seguro, llamar es lo más seguro.",
      notNow: "No está pasando ahora. Continuar",
      selfHarm: "No tiene que pasar por esto solo. Hay personas dispuestas a escucharle, ahora mismo.",
    },
    timing: {
      question: (self: boolean): string => self ? "¿Cuándo le gustaría que le vieran?" : "¿Cuándo le gustaría que le vieran a esa persona?",
    },
    profile: {
      question: "¿Usamos lo que VYVA ya sabe?",
      help: "Solo para esta búsqueda. No se comparte con nadie.",
      cover: "Cobertura",
      place: "Buscar cerca de",
      usualDoctor: "Médico habitual",
      notSaved: "Aún no guardado",
      accept: "Sí, usar estos datos",
      change: "Cambiar algo",
    },
    coverage: {
      question: (self: boolean): string => self ? "¿Cómo se paga su atención sanitaria?" : "¿Cómo se paga la atención sanitaria de esa persona?",
      help: "Esto decide por dónde empezar. En la sanidad pública, el médico de familia suele ser el primer paso.",
    },
    location: {
      question: "¿Dónde buscamos?",
      help: "Un pueblo, barrio o código postal. Solo se usa para encontrar sitios cercanos.",
      label: "Pueblo o código postal",
      submit: "Buscar cerca de aquí",
    },
    route: {
      question: "Por dónde empezar",
      help: "Según lo que nos ha contado, aquí es donde se suele empezar. No es un diagnóstico.",
      suggested: "Un buen punto de partida",
      alternative: "Otra opción",
      choose: (label: string) => `Buscar ${label.toLowerCase()}`,
      publicAccess: "Sanidad pública",
      privateAccess: "Privado, normalmente de pago o con seguro",
      notSure: "Sigo sin estar seguro. Empezar por el médico de familia",
    },
    access: {
      question: "¿Algo que se lo ponga más fácil?",
      help: "Elija lo que necesite. Lo usaremos en la búsqueda y al llamar.",
      suggestedNote: "Hemos marcado \"Sin escaleras\" porque mencionó dificultad con escaleras o al caminar. Púlselo para quitarlo.",
      show: (label: string, place: string) => `Ver ${label.toLowerCase()} cerca de ${place}`,
    },
    results: {
      loading: (label: string, place: string) => `Buscando ${label.toLowerCase()} cerca de ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "opción" : "opciones"} de ${label.toLowerCase()} cerca de ${place}`,
      orderTravel: "La más cercana primero. Este orden no es una valoración de calidad.",
      orderDistanceTown: "La más cercana primero, en línea recta desde su dirección, y después otros centros de su municipio cuya distancia aún no conocemos. Solo se muestran centros autorizados en el registro oficial de centros sanitarios. Este orden no es una valoración de calidad.",
      orderDistance: "La más cercana primero, en línea recta desde su dirección. Solo se muestran centros autorizados en el registro oficial de centros sanitarios. Este orden no es una valoración de calidad.",
      orderRelevance: "En el orden que dio Google Maps. No es una valoración de calidad.",
      legendTitle: "Cómo leer esto",
      checked: "Comprobado",
      checkedDetail: "En un registro oficial o en la web del propio sitio",
      orderAssigned: "Primero su centro de salud y después los más cercanos. Este orden no es una valoración de calidad.",
      publicTitle: "Su centro de salud",
      publicHealthMap: (name: string, source: string) => `${name} es el centro que corresponde a su zona según el mapa sanitario publicado por ${source}.`,
      publicNearest: (name: string) => `${name} es el centro de salud público más cercano. Su centro figura en su tarjeta sanitaria; si es otro, use ese.`,
      publicUnknown: "Su centro de salud figura en su tarjeta sanitaria.",
      bookOnline: (service: string) => `Pedir cita por internet: ${service}`,
      bookNotListed: "Aún no tenemos la página de cita previa de su comunidad. Puede llamar a su centro de salud para pedir cita.",
      opensOfficialSite: "abre la web oficial",
      badgeHealthMap: "Su centro de salud",
      badgeNearest: "Centro de salud público más cercano",
      google: "Según Google Maps",
      googleDetail: "Publicado por Google. Suele ser correcto, conviene confirmarlo",
      unknown: "No se sabe",
      unknownDetail: "Pregúntelo al llamar",
      why: "Por qué aparece",
      goodToKnow: "Conviene saber (información general de VYVA, no comprobada para este sitio)",
      prepare: (name: string) => `Preparar el contacto con ${name}`,
      openMap: "Abrir en Google Maps",
      compare: "Comparar una al lado de otra",
      hideCompare: "Ocultar comparación",
      usualDoctorTitle: "Su médico habitual",
      usualDoctorDetail: "Guardado en su perfil de VYVA",
      changeAnswers: "Cambiar mis respuestas",
      checkedOn: (when: string) => `Información recogida ${when}`,
      noResults: (label: string, place: string) => `No hemos encontrado ${label.toLowerCase()} cerca de ${place} que podamos comprobar.`,
      unavailable: "La búsqueda no está disponible ahora mismo. No se ha perdido nada.",
      error: "No hemos podido buscar ahora. Sus respuestas están guardadas.",
      offline: "Parece que no hay conexión. Sus respuestas están guardadas en este dispositivo.",
      retry: "Volver a buscar",
      tryPlace: "Probar otro lugar",
      tryCare: "Probar otro tipo de atención",
      mapsYourself: "Buscar usted mismo en Google Maps (no comprobado por VYVA)",
      callUsual: (name: string) => `Llamar a ${name}`,
      facts: {
        distance: "Cómo llegar",
        availability: "Abierto hoy",
        accessibility: "Acceso sin escalones",
        coverage: "Acepta su cobertura",
        price: "Precio",
        reputation: "Opiniones en Google",
      },
    },
    contact: {
      heading: (name: string) => `Antes de contactar con ${name}`,
      intro: "VYVA no envía nada. Usted decide qué decir y cuándo.",
      scriptTitle: "Lo que puede decir",
      scriptTranslated: "En español, con el significado en inglés debajo.",
      askTitle: "Preguntas que conviene hacer",
      shareTitle: "Lo que va a compartir",
      shareHelp: "Desmarque lo que prefiera no contar.",
      shareReason: "Por qué necesita atención",
      shareCoverage: "Cómo se paga",
      shareAccess: "Necesidades de acceso",
      shareCompanion: "Que irá acompañado",
      call: (name: string) => `Llamar a ${name}`,
      noPhone: "No hemos encontrado un teléfono para este sitio.",
      website: "Abrir su web",
      email: "Enviarles un correo",
      bookingLink: "Abrir su página de citas",
      confirmTitle: (name: string) => `¿Llamar a ${name}?`,
      confirmBody: (phone: string) => `Su teléfono llamará al ${phone}. VYVA no escucha ni graba la llamada.`,
      confirmYes: "Sí, llamar ahora",
      confirmNo: "Todavía no",
      shareTitleHelper: "Compartir con alguien de confianza",
      shareIntro: "Se compartirá exactamente este mensaje. No se envía nada hasta que elija a quién.",
      shareButton: "Elegir a quién enviarlo",
      sharePreviewButton: "Ver primero el mensaje",
      copyButton: "Copiar el mensaje",
      copied: "Mensaje copiado",
      ride: "Organizar el transporte con VYVA",
      rideNote: "Confirmará los detalles antes de reservar nada.",
      outcomeTitle: "¿Cómo ha ido?",
      outcomes: {
        booked: "He pedido cita",
        call_back: "Me van a llamar",
        no_answer: "No contestan. Lo intentaré luego",
        not_suitable: "No era lo adecuado. Ver otras opciones",
      },
      otherOptions: "Volver a las opciones",
    },
    done: {
      booked: "Muy bien. Esta búsqueda está completa.",
      bookedNext: "Hemos cerrado esta búsqueda. Puede empezar otra cuando quiera.",
      later: "Hemos guardado esta búsqueda para que pueda volver a ella.",
      health: "Volver a Salud",
      newSearch: "Empezar una búsqueda nueva",
      resume: "Volver a mis opciones",
    },
    summary: {
      title: "Lo que VYVA ha entendido",
      empty: "Aquí aparecerán sus respuestas.",
      change: "Cambiar",
      for: "Para",
      self: "Usted",
      other: "Alguien a quien ayuda",
      words: "Con sus palabras",
      about: "Sobre",
      warnings: "Señales de alarma",
      warningsNone: "Ninguna ahora",
      warningsSeen: "Ha dicho que no está pasando ahora",
      soon: "Cuándo",
      cover: "Cobertura",
      place: "Buscando cerca de",
      lookingFor: "Buscando",
      access: "Para llegar",
      accessNone: "Nada especial",
      show: "Ver mis respuestas",
      hide: "Ocultar mis respuestas",
    },
    disclaimer: "VYVA le ayuda a encontrar atención. No hace diagnósticos. En una emergencia, llame al 112.",
  };
}


function frenchCopy(): Copy {
  return {
    title: "Trouver les bons soins",
    back: "Retour",
    pause: "Continuer plus tard",
    readAloud: "Me le lire",
    stopReading: "Arrêter la lecture",
    loading: "Chargement de votre recherche…",
    closed: "Cette recherche était déjà terminée, nous en commençons une nouvelle.",
    saving: "Enregistrement…",
    saved: "Vos réponses sont enregistrées",
    savedOffline: "Enregistré sur cet appareil. La synchronisation se fera au retour de la connexion.",
    notDiagnosis: "VYVA vous aide à trouver des soins. VYVA ne pose pas de diagnostic.",
    intro: "Dites-nous ce qui se passe et nous vous aidons à trouver le bon type de soins près de chez vous. Rien n'est partagé ni réservé sans votre accord.",
    resume: {
      title: "Reprendre là où vous en étiez ?",
      body: (about: string, when: string) => `Vous cherchiez des soins${about ? ` pour ${about}` : ""} le ${when}.`,
      continue: "Reprendre ma recherche",
      startNew: "Commencer une nouvelle recherche",
    },
    legacy: (when: string | null) => `Vous avez commencé cette recherche${when ? ` le ${when}` : ""}. Nous avons amélioré la façon dont VYVA recherche des soins, alors nous allons vous poser quelques questions rapides pour trouver de meilleures options. Nous avons gardé votre description.`,
    who: {
      question: "Pour qui sont les soins ?",
      self: "Pour moi",
      selfDetail: "Je cherche pour moi",
      other: "Pour une personne que j'aide",
      otherDetail: "Un parent, un conjoint ou un ami",
    },
    need: {
      question: (self: boolean): string => self ? "Qu'est-ce qui ne va pas ?" : "Qu'est-ce qui ne va pas pour cette personne ?",
      help: "Choisissez ce qui s'en rapproche le plus, ou décrivez-le avec vos mots.",
      unmatched: "Merci, nous avons gardé vos mots. Laquelle de ces options s'en rapproche le plus ?",
      inputLabel: "Décrivez-le avec vos mots",
      placeholder: "Par exemple : j'ai mal au genou dans les escaliers",
      submit: "Utiliser ma description",
      orChoose: "Ou choisissez une option",
    },
    area: {
      question: "Où le ressentez-vous le plus ?",
      help: "Si rien ne correspond, choisissez « Toujours pas sûr ». Le médecin de famille est alors la bonne première étape.",
    },
    describe: {
      question: "Dites-nous ce qui se passe",
      help: "Quelques mots suffisent. Vous pouvez écrire ou parler.",
    },
    voice: {
      speak: "Parler au lieu d'écrire",
      stop: "Arrêter l'écoute",
      listening: "J'écoute… parlez maintenant",
    },
    safety: {
      question: (self: boolean): string => self ? "Est-ce que l'une de ces choses se produit en ce moment ?" : "Est-ce que l'une de ces choses arrive à cette personne en ce moment ?",
      help: "Touchez-en une si c'est le cas. Sinon, touchez « Rien de tout cela ».",
      none: "Rien de tout cela ne se produit",
    },
    urgent: {
      title: "Cela peut nécessiter de l'aide tout de suite",
      body: "Si cela se produit maintenant, n'attendez pas un rendez-vous.",
      unsure: "Si vous n'êtes pas sûr, appeler est le choix le plus sûr.",
      notNow: "Cela ne se produit pas maintenant. Continuer",
      selfHarm: "Vous n'avez pas à traverser cela seul. Des personnes sont prêtes à vous écouter, maintenant.",
    },
    timing: {
      question: (self: boolean): string => self ? "Dans quel délai aimeriez-vous être vu ?" : "Dans quel délai cette personne aimerait-elle être vue ?",
    },
    profile: {
      question: "Utiliser ce que VYVA sait déjà ?",
      help: "Uniquement pour cette recherche. Rien n'est partagé avec personne.",
      cover: "Couverture santé",
      place: "Chercher près de",
      usualDoctor: "Médecin habituel",
      notSaved: "Pas encore enregistré",
      accept: "Oui, utiliser ces informations",
      change: "Modifier quelque chose",
    },
    coverage: {
      question: (self: boolean): string => self ? "Comment vos soins sont-ils pris en charge ?" : "Comment les soins de cette personne sont-ils pris en charge ?",
      help: "Cela détermine par où commencer. Dans le système public, le médecin de famille est généralement la première étape.",
    },
    location: {
      question: "Où devons-nous chercher ?",
      help: "Une ville, un quartier ou un code postal. Utilisé uniquement pour trouver des lieux proches.",
      label: "Ville ou code postal",
      submit: "Chercher près de cet endroit",
    },
    route: {
      question: "Par où commencer",
      help: "D'après ce que vous nous avez dit, c'est par là que l'on commence généralement. Ce n'est pas un diagnostic.",
      suggested: "Un bon point de départ",
      alternative: "Une autre option",
      choose: (label: string) => `Chercher : ${label.toLowerCase()}`,
      publicAccess: "Système public",
      privateAccess: "Privé, généralement payant ou pris en charge par une assurance",
      notSure: "Je ne suis toujours pas sûr. Commencer par un médecin de famille",
    },
    access: {
      question: "Quelque chose qui vous faciliterait les choses ?",
      help: "Choisissez ce qui s'applique. Nous en tiendrons compte dans la recherche et lors de l'appel.",
      suggestedNote: "Nous avons coché « Sans escaliers » car vous avez mentionné une difficulté avec les escaliers ou la marche. Touchez-le pour le retirer.",
      show: (label: string, place: string) => `Voir : ${label.toLowerCase()} près de ${place}`,
    },
    results: {
      loading: (label: string, place: string) => `Recherche : ${label.toLowerCase()} près de ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "option" : "options"} (${label.toLowerCase()}) près de ${place}`,
      orderTravel: "Les plus proches d'abord. Cet ordre n'est pas un classement de qualité.",
      orderDistanceTown: "Les plus proches d'abord, à vol d'oiseau depuis votre adresse, puis d'autres centres de votre commune dont nous ne connaissons pas encore la distance. Seuls les centres autorisés dans le registre officiel des centres de santé sont affichés. Cet ordre n'est pas un classement de qualité.",
      orderDistance: "Les plus proches d'abord, à vol d'oiseau depuis votre adresse. Seuls les centres autorisés dans le registre officiel des centres de santé sont affichés. Cet ordre n'est pas un classement de qualité.",
      orderRelevance: "Dans l'ordre donné par Google Maps. Ce n'est pas un classement de qualité.",
      legendTitle: "Comment lire ces informations",
      checked: "Vérifié",
      checkedDetail: "Dans un registre officiel, ou sur le site web du lieu lui-même",
      orderAssigned: "D'abord votre centre de santé, puis les plus proches. Cet ordre n'est pas un classement de qualité.",
      publicTitle: "Votre centre de santé",
      publicHealthMap: (name: string, source: string) => `${name} est le centre de votre secteur selon la carte sanitaire publiée par ${source}.`,
      publicNearest: (name: string) => `${name} est le centre de santé public le plus proche. Votre propre centre est indiqué sur votre carte de santé ; si c'est un autre, utilisez celui-là.`,
      publicUnknown: "Votre centre de santé est indiqué sur votre carte de santé.",
      bookOnline: (service: string) => `Prendre rendez-vous en ligne : ${service}`,
      bookNotListed: "Nous n'avons pas encore la page de rendez-vous en ligne de votre région. Vous pouvez appeler votre centre de santé.",
      opensOfficialSite: "ouvre le site officiel",
      badgeHealthMap: "Votre centre de santé",
      badgeNearest: "Centre de santé public le plus proche",
      google: "Selon Google Maps",
      googleDetail: "Publié par Google. Souvent exact, à confirmer",
      unknown: "Inconnu",
      unknownDetail: "À demander lors de l'appel",
      why: "Pourquoi ce lieu apparaît",
      goodToKnow: "Bon à savoir (information générale de VYVA, non vérifiée pour ce lieu)",
      prepare: (name: string) => `Préparer le contact avec ${name}`,
      openMap: "Ouvrir dans Google Maps",
      compare: "Comparer côte à côte",
      hideCompare: "Masquer la comparaison",
      usualDoctorTitle: "Votre médecin habituel",
      usualDoctorDetail: "Enregistré dans votre profil VYVA",
      changeAnswers: "Modifier mes réponses",
      checkedOn: (when: string) => `Informations recueillies ${when}`,
      noResults: (label: string, place: string) => `Nous n'avons trouvé aucun résultat (${label.toLowerCase()}) près de ${place} que nous puissions vérifier.`,
      unavailable: "La recherche n'est pas disponible pour le moment. Rien n'a été perdu.",
      error: "Nous n'avons pas pu lancer la recherche. Vos réponses sont enregistrées.",
      offline: "Vous semblez hors ligne. Vos réponses sont enregistrées sur cet appareil.",
      retry: "Relancer la recherche",
      tryPlace: "Essayer un autre endroit",
      tryCare: "Essayer un autre type de soins",
      mapsYourself: "Chercher vous-même sur Google Maps (non vérifié par VYVA)",
      callUsual: (name: string) => `Appeler ${name}`,
      facts: {
        distance: "Pour y aller",
        availability: "Ouvert aujourd'hui",
        accessibility: "Accès sans marches",
        coverage: "Accepte votre couverture",
        price: "Prix",
        reputation: "Avis Google",
      },
    },
    contact: {
      heading: (name: string) => `Avant de contacter ${name}`,
      intro: "VYVA n'envoie rien. C'est vous qui décidez quoi dire et quand.",
      scriptTitle: "Ce que vous pourriez dire",
      scriptTranslated: "En espagnol, avec la traduction en français en dessous.",
      askTitle: "Questions utiles à poser",
      shareTitle: "Ce que vous allez partager",
      shareHelp: "Décochez ce que vous préférez garder pour vous.",
      shareReason: "Pourquoi vous avez besoin de soins",
      shareCoverage: "Comment c'est pris en charge",
      shareAccess: "Besoins d'accès",
      shareCompanion: "Que quelqu'un vous accompagnera",
      call: (name: string) => `Appeler ${name}`,
      noPhone: "Aucun numéro de téléphone n'a été trouvé pour ce lieu.",
      website: "Ouvrir leur site web",
      email: "Leur écrire un e-mail",
      bookingLink: "Ouvrir leur page de rendez-vous",
      confirmTitle: (name: string) => `Appeler ${name} ?`,
      confirmBody: (phone: string) => `Votre téléphone va appeler le ${phone}. VYVA n'écoute pas et n'enregistre pas l'appel.`,
      confirmYes: "Oui, appeler maintenant",
      confirmNo: "Pas encore",
      shareTitleHelper: "Partager avec une personne de confiance",
      shareIntro: "Ce message exact sera partagé. Rien n'est envoyé tant que vous n'avez pas choisi à qui.",
      shareButton: "Choisir à qui l'envoyer",
      sharePreviewButton: "Voir d'abord le message",
      copyButton: "Copier le message",
      copied: "Message copié",
      ride: "Organiser le trajet avec VYVA",
      rideNote: "Vous confirmerez les détails avant toute réservation.",
      outcomeTitle: "Comment cela s'est-il passé ?",
      outcomes: {
        booked: "J'ai pris rendez-vous",
        call_back: "Ils vont me rappeler",
        no_answer: "Pas de réponse. Je réessaierai plus tard",
        not_suitable: "Ce n'était pas adapté. Voir d'autres options",
      },
      otherOptions: "Retour aux options",
    },
    done: {
      booked: "Très bien. Cette recherche est terminée.",
      bookedNext: "Nous avons clôturé cette recherche. Vous pouvez en commencer une autre à tout moment.",
      later: "Nous avons enregistré cette recherche pour que vous puissiez y revenir.",
      health: "Retour à Santé",
      newSearch: "Commencer une nouvelle recherche",
      resume: "Retour à mes options",
    },
    summary: {
      title: "Ce que VYVA a compris",
      empty: "Vos réponses apparaîtront ici.",
      change: "Modifier",
      for: "Pour",
      self: "Vous",
      other: "Une personne que vous aidez",
      words: "Avec vos mots",
      about: "Sujet",
      warnings: "Signes d'alerte",
      warningsNone: "Aucun en ce moment",
      warningsSeen: "Vous avez dit que cela ne se produit pas maintenant",
      soon: "Délai",
      cover: "Couverture santé",
      place: "Recherche près de",
      lookingFor: "Recherche",
      access: "Pour y aller",
      accessNone: "Rien de particulier",
      show: "Voir mes réponses",
      hide: "Masquer mes réponses",
    },
    disclaimer: "VYVA vous aide à trouver des soins. VYVA ne pose pas de diagnostic. En cas d'urgence, appelez le 112.",
  };
}

// German keeps nouns capitalised, so care names are never lowercased here.
function germanCopy(): Copy {
  return {
    title: "Die passende Versorgung finden",
    back: "Zurück",
    pause: "Später weitermachen",
    readAloud: "Vorlesen",
    stopReading: "Vorlesen beenden",
    loading: "Ihre Suche wird geladen…",
    closed: "Diese Suche war bereits abgeschlossen, daher beginnen wir eine neue.",
    saving: "Wird gespeichert…",
    saved: "Ihre Antworten sind gespeichert",
    savedOffline: "Auf diesem Gerät gespeichert. Wird synchronisiert, sobald Sie wieder online sind.",
    notDiagnosis: "VYVA hilft Ihnen, Versorgung zu finden. VYVA stellt keine Diagnosen.",
    intro: "Erzählen Sie uns, was los ist, und wir helfen Ihnen, die passende Versorgung in Ihrer Nähe zu finden. Nichts wird ohne Ihr Einverständnis geteilt oder gebucht.",
    resume: {
      title: "Dort weitermachen, wo Sie aufgehört haben?",
      body: (about: string, when: string) => `Sie haben am ${when} nach Versorgung gesucht${about ? ` wegen ${about}` : ""}.`,
      continue: "Meine Suche fortsetzen",
      startNew: "Neue Suche beginnen",
    },
    legacy: (when: string | null) => `Sie haben diese Suche${when ? ` am ${when}` : ""} begonnen. Wir haben verbessert, wie VYVA nach Gesundheitsversorgung sucht. Deshalb stellen wir Ihnen ein paar kurze Fragen, um bessere Möglichkeiten zu finden. Ihre Beschreibung haben wir behalten.`,
    who: {
      question: "Für wen ist die Versorgung?",
      self: "Für mich",
      selfDetail: "Ich suche für mich",
      other: "Für jemanden, dem ich helfe",
      otherDetail: "Ein Elternteil, Partner oder Freund",
    },
    need: {
      question: (self: boolean): string => self ? "Was macht Ihnen zu schaffen?" : "Was macht dieser Person zu schaffen?",
      help: "Wählen Sie das Passendste oder beschreiben Sie es mit eigenen Worten.",
      unmatched: "Danke, wir haben Ihre Worte behalten. Was davon passt am besten?",
      inputLabel: "Beschreiben Sie es mit eigenen Worten",
      placeholder: "Zum Beispiel: Mein Knie tut auf der Treppe weh",
      submit: "Meine Beschreibung verwenden",
      orChoose: "Oder wählen Sie eine Option",
    },
    area: {
      question: "Wo spüren Sie es am meisten?",
      help: "Wenn nichts passt, wählen Sie „Immer noch unsicher“. Dann ist die Hausärztin oder der Hausarzt der richtige erste Schritt.",
    },
    describe: {
      question: "Erzählen Sie uns, was los ist",
      help: "Ein paar Worte genügen. Sie können schreiben oder sprechen.",
    },
    voice: {
      speak: "Sprechen statt schreiben",
      stop: "Zuhören beenden",
      listening: "Ich höre zu… sprechen Sie jetzt",
    },
    safety: {
      question: (self: boolean): string => self ? "Passiert gerade etwas davon?" : "Passiert dieser Person gerade etwas davon?",
      help: "Tippen Sie auf eines, wenn ja. Sonst tippen Sie auf „Nichts davon“.",
      none: "Nichts davon passiert gerade",
    },
    urgent: {
      title: "Das braucht vielleicht sofort Hilfe",
      body: "Wenn das gerade passiert, warten Sie bitte nicht auf einen Termin.",
      unsure: "Wenn Sie unsicher sind, ist ein Anruf die sichere Wahl.",
      notNow: "Es passiert gerade nicht. Weiter",
      selfHarm: "Sie müssen das nicht allein durchstehen. Menschen sind bereit, Ihnen jetzt zuzuhören.",
    },
    timing: {
      question: (self: boolean): string => self ? "Wie bald möchten Sie einen Termin?" : "Wie bald möchte diese Person einen Termin?",
    },
    profile: {
      question: "Sollen wir verwenden, was VYVA schon weiß?",
      help: "Nur für diese Suche. Nichts wird mit anderen geteilt.",
      cover: "Krankenversicherung",
      place: "Suchen in der Nähe von",
      usualDoctor: "Hausarzt",
      notSaved: "Noch nicht gespeichert",
      accept: "Ja, diese Angaben verwenden",
      change: "Etwas ändern",
    },
    coverage: {
      question: (self: boolean): string => self ? "Wie wird Ihre Gesundheitsversorgung bezahlt?" : "Wie wird die Gesundheitsversorgung dieser Person bezahlt?",
      help: "Davon hängt ab, wo man anfängt. Im öffentlichen System ist die Hausarztpraxis meist der erste Schritt.",
    },
    location: {
      question: "Wo sollen wir suchen?",
      help: "Ein Ort, Stadtteil oder eine Postleitzahl. Wird nur genutzt, um Angebote in der Nähe zu finden.",
      label: "Ort oder Postleitzahl",
      submit: "In der Nähe dieses Ortes suchen",
    },
    route: {
      question: "Wo man anfängt",
      help: "Nach dem, was Sie uns erzählt haben, fängt man meist hier an. Das ist keine Diagnose.",
      suggested: "Ein guter Anfang",
      alternative: "Eine weitere Möglichkeit",
      choose: (label: string) => `Suchen: ${label}`,
      publicAccess: "Öffentliches System",
      privateAccess: "Privat, meist selbst bezahlt oder über eine Versicherung",
      notSure: "Ich bin immer noch unsicher. Mit der Hausarztpraxis anfangen",
    },
    access: {
      question: "Gibt es etwas, das es Ihnen leichter macht?",
      help: "Wählen Sie, was zutrifft. Wir berücksichtigen es bei der Suche und beim Anruf.",
      suggestedNote: "Wir haben „Ohne Treppen“ ausgewählt, weil Sie Schwierigkeiten mit Treppen oder beim Gehen erwähnt haben. Tippen Sie darauf, um es zu entfernen.",
      show: (label: string, place: string) => `${label} in der Nähe von ${place} anzeigen`,
    },
    results: {
      loading: (label: string, place: string) => `Suche: ${label} in der Nähe von ${place}…`,
      heading: (count: number, label: string, place: string) => `${count} ${count === 1 ? "Möglichkeit" : "Möglichkeiten"} (${label}) in der Nähe von ${place}`,
      orderTravel: "Die nächstgelegenen zuerst. Diese Reihenfolge ist keine Qualitätsbewertung.",
      orderDistanceTown: "Die nächstgelegenen zuerst, Luftlinie von Ihrer Adresse, danach weitere Einrichtungen in Ihrem Ort, deren Entfernung wir noch nicht kennen. Es werden nur Einrichtungen gezeigt, die im offiziellen Register der Gesundheitseinrichtungen zugelassen sind. Diese Reihenfolge ist keine Qualitätsbewertung.",
      orderDistance: "Die nächstgelegenen zuerst, Luftlinie von Ihrer Adresse. Es werden nur Einrichtungen gezeigt, die im offiziellen Register der Gesundheitseinrichtungen zugelassen sind. Diese Reihenfolge ist keine Qualitätsbewertung.",
      orderRelevance: "In der Reihenfolge von Google Maps. Das ist keine Qualitätsbewertung.",
      legendTitle: "So lesen Sie diese Angaben",
      checked: "Geprüft",
      checkedDetail: "In einem amtlichen Register oder auf der eigenen Website des Anbieters",
      orderAssigned: "Zuerst Ihr Gesundheitszentrum, dann die nächstgelegenen. Diese Reihenfolge ist keine Qualitätsbewertung.",
      publicTitle: "Ihr Gesundheitszentrum",
      publicHealthMap: (name: string, source: string) => `${name} ist laut der von ${source} veröffentlichten Gesundheitskarte das Zentrum für Ihr Gebiet.`,
      publicNearest: (name: string) => `${name} ist das nächstgelegene öffentliche Gesundheitszentrum. Ihr eigenes Zentrum steht auf Ihrer Gesundheitskarte. Wenn es ein anderes ist, nehmen Sie dieses.`,
      publicUnknown: "Ihr Gesundheitszentrum steht auf Ihrer Gesundheitskarte.",
      bookOnline: (service: string) => `Online einen Termin buchen: ${service}`,
      bookNotListed: "Die Online-Terminseite Ihrer Region haben wir noch nicht. Sie können Ihr Gesundheitszentrum anrufen.",
      opensOfficialSite: "öffnet die offizielle Website",
      badgeHealthMap: "Ihr Gesundheitszentrum",
      badgeNearest: "Nächstgelegenes öffentliches Gesundheitszentrum",
      google: "Laut Google Maps",
      googleDetail: "Von Google veröffentlicht. Meist richtig, aber besser bestätigen",
      unknown: "Unbekannt",
      unknownDetail: "Beim Anruf nachfragen",
      why: "Warum es hier steht",
      goodToKnow: "Gut zu wissen (allgemeine Einschätzung von VYVA, für diesen Ort nicht geprüft)",
      prepare: (name: string) => `Kontakt mit ${name} vorbereiten`,
      openMap: "In Google Maps öffnen",
      compare: "Nebeneinander vergleichen",
      hideCompare: "Vergleich ausblenden",
      usualDoctorTitle: "Ihr Hausarzt",
      usualDoctorDetail: "In Ihrem VYVA-Profil gespeichert",
      changeAnswers: "Meine Antworten ändern",
      checkedOn: (when: string) => `Angaben erfasst ${when}`,
      noResults: (label: string, place: string) => `Wir haben in der Nähe von ${place} nichts gefunden (${label}), das wir prüfen konnten.`,
      unavailable: "Die Suche ist gerade nicht verfügbar. Es ist nichts verloren gegangen.",
      error: "Die Suche hat gerade nicht geklappt. Ihre Antworten sind gespeichert.",
      offline: "Sie scheinen offline zu sein. Ihre Antworten sind auf diesem Gerät gespeichert.",
      retry: "Suche erneut starten",
      tryPlace: "Einen anderen Ort versuchen",
      tryCare: "Eine andere Art der Versorgung versuchen",
      mapsYourself: "Selbst in Google Maps suchen (nicht von VYVA geprüft)",
      callUsual: (name: string) => `${name} anrufen`,
      facts: {
        distance: "Anfahrt",
        availability: "Heute geöffnet",
        accessibility: "Stufenloser Zugang",
        coverage: "Akzeptiert Ihre Versicherung",
        price: "Preis",
        reputation: "Google-Bewertungen",
      },
    },
    contact: {
      heading: (name: string) => `Bevor Sie ${name} kontaktieren`,
      intro: "VYVA sendet nichts. Sie entscheiden, was Sie sagen und wann.",
      scriptTitle: "Was Sie sagen könnten",
      scriptTranslated: "Auf Spanisch, darunter die Bedeutung auf Deutsch.",
      askTitle: "Fragen, die sich lohnen",
      shareTitle: "Was Sie mitteilen",
      shareHelp: "Entfernen Sie das Häkchen bei allem, was Sie lieber für sich behalten.",
      shareReason: "Warum Sie Versorgung brauchen",
      shareCoverage: "Wie es bezahlt wird",
      shareAccess: "Bedürfnisse beim Zugang",
      shareCompanion: "Dass Sie begleitet werden",
      call: (name: string) => `${name} anrufen`,
      noPhone: "Für diesen Ort wurde keine Telefonnummer gefunden.",
      website: "Website öffnen",
      email: "E-Mail schreiben",
      bookingLink: "Terminseite öffnen",
      confirmTitle: (name: string) => `${name} anrufen?`,
      confirmBody: (phone: string) => `Ihr Telefon ruft ${phone} an. VYVA hört nicht mit und zeichnet nichts auf.`,
      confirmYes: "Ja, jetzt anrufen",
      confirmNo: "Noch nicht",
      shareTitleHelper: "Mit einer Vertrauensperson teilen",
      shareIntro: "Genau diese Nachricht wird geteilt. Es wird nichts gesendet, bis Sie den Empfänger auswählen.",
      shareButton: "Empfänger auswählen",
      sharePreviewButton: "Zuerst die Nachricht ansehen",
      copyButton: "Nachricht kopieren",
      copied: "Nachricht kopiert",
      ride: "Fahrt dorthin mit VYVA organisieren",
      rideNote: "Sie bestätigen die Details, bevor etwas gebucht wird.",
      outcomeTitle: "Wie ist es gelaufen?",
      outcomes: {
        booked: "Ich habe einen Termin vereinbart",
        call_back: "Sie rufen mich zurück",
        no_answer: "Niemand erreicht. Ich versuche es später",
        not_suitable: "Es hat nicht gepasst. Andere Möglichkeiten zeigen",
      },
      otherOptions: "Zurück zu den Möglichkeiten",
    },
    done: {
      booked: "Sehr gut. Diese Suche ist abgeschlossen.",
      bookedNext: "Wir haben diese Suche abgeschlossen. Sie können jederzeit eine neue beginnen.",
      later: "Wir haben diese Suche gespeichert, damit Sie später zurückkommen können.",
      health: "Zurück zu Gesundheit",
      newSearch: "Neue Suche beginnen",
      resume: "Zurück zu meinen Möglichkeiten",
    },
    summary: {
      title: "Was VYVA verstanden hat",
      empty: "Hier erscheinen Ihre Antworten.",
      change: "Ändern",
      for: "Für",
      self: "Sie",
      other: "Jemand, dem Sie helfen",
      words: "In Ihren Worten",
      about: "Thema",
      warnings: "Warnzeichen",
      warningsNone: "Derzeit keine",
      warningsSeen: "Sie sagten, es passiert gerade nicht",
      soon: "Wie bald",
      cover: "Krankenversicherung",
      place: "Suche in der Nähe von",
      lookingFor: "Gesucht",
      access: "Anfahrt",
      accessNone: "Nichts Besonderes",
      show: "Meine Antworten zeigen",
      hide: "Meine Antworten ausblenden",
    },
    disclaimer: "VYVA hilft Ihnen, Versorgung zu finden. VYVA stellt keine Diagnosen. Im Notfall rufen Sie die 112 an.",
  };
}

export type CareFinderCopy = Copy;

const COPY: Record<CareFinderLang, () => CareFinderCopy> = {
  en: englishCopy,
  es: spanishCopy,
  fr: frenchCopy,
  de: germanCopy,
};

export function careFinderCopy(lang: CareFinderLang): CareFinderCopy {
  return COPY[lang]();
}
