export const ORCHESTRATION_CONTRACT_ERROR_CODES = [
  "STALE_QUESTION",
  "STALE_SCENE",
  "STALE_FLOW_VERSION",
  "INVALID_MODALITY",
  "OPTION_NOT_ALLOWED",
  "ANSWER_ID_NOT_ALLOWED",
  "ANSWER_ID_REQUIRED",
  "INVALID_VALUE",
  "INVALID_ASSET_REFERENCE",
  "INVALID_MIME_TYPE",
  "UNEXPECTED_EXPECTED_INPUT",
  "MISSING_EXPECTED_INPUT",
  "INVALID_STATE_TRANSITION",
  "INVALID_EVENT_SOURCE",
  "INVALID_EVENT_MODALITY",
  "INVALID_EVENT_TRIGGER",
  "INVALID_EVENT_PAYLOAD",
  "MISSING_INTERRUPTED_STATE",
  "MISSING_PENDING_TOOL",
  "TERMINAL_STATE_HAS_EXPECTED_INPUT",
  "IDLE_STATE_HAS_ACTIVE_FLOW_DATA",
  "SPECIALIST_REQUEST_INVALID",
  "SPECIALIST_RESPONSE_INVALID",
  "REQUEST_ID_MISMATCH",
  "SPECIALIST_ID_MISMATCH",
  "EMERGENCY_CHECK_REQUIRED",
  "RESPONSE_STATUS_INVARIANT_FAILED",
  "TOOL_NOT_AVAILABLE",
  "TOOL_CONFIRMATION_CANNOT_BE_WEAKENED",
  "TOOL_CONSENT_NOT_ALLOWED",
  "TOOL_IDEMPOTENCY_REQUIRED",
  "INVALID_MEMORY_PROPOSAL",
  "DIRECT_EXECUTION_NOT_ALLOWED",
  "ESCALATION_PROPOSAL_INVALID",
  "FLOW_UPDATE_INVALID",
  "FLOW_PATCH_INVALID",
  "FLOW_CATALOGUE_INVALID",
  "FLOW_ID_DUPLICATE",
  "FLOW_VERSION_INVALID",
  "FLOW_REFERENCE_INVALID",
  "FLOW_REFERENCE_CYCLE",
  "CAPABILITY_ID_DUPLICATE",
  "CAPABILITY_REFERENCE_INVALID",
  "FLOW_SAFETY_POLICY_INVALID",
  "FLOW_CONSENT_POLICY_INVALID",
  "FLOW_EVIDENCE_POLICY_INVALID",
  "FLOW_COMPATIBILITY_INVALID",
  "FLOW_METADATA_INVALID",
  "FLOW_TRIGGER_POLICY_INVALID",
  "FLOW_COLLECTION_INVALID",
  "FLOW_OUTCOME_POLICY_INVALID",
  "FLOW_TOOL_POLICY_INVALID",
  "FLOW_TRUST_POLICY_INVALID",
  "PRESENTATION_REGISTRY_INVALID",
  "PRESENTATION_ID_DUPLICATE",
  "PRESENTATION_VERSION_INVALID",
  "PRESENTATION_REFERENCE_INVALID",
  "PRESENTATION_REFERENCE_CYCLE",
  "PRESENTATION_FAMILY_INVALID",
  "PRESENTATION_SCENE_INVALID",
  "PRESENTATION_FLOW_INCOMPATIBLE",
  "PRESENTATION_CHANNEL_INCOMPATIBLE",
  "PRESENTATION_DEVICE_INCOMPATIBLE",
  "PRESENTATION_INPUT_INCOMPATIBLE",
  "PRESENTATION_INTERACTION_INVALID",
  "PRESENTATION_EVENT_MAPPING_INVALID",
  "PRESENTATION_ACTION_INVALID",
  "PRESENTATION_VOICE_SYNC_INVALID",
  "PRESENTATION_ACCESSIBILITY_INVALID",
  "PRESENTATION_LOCALIZATION_INVALID",
  "PRESENTATION_PRIVACY_INVALID",
  "PRESENTATION_SAFETY_INVALID",
  "PRESENTATION_FALLBACK_INVALID",
  "PRESENTATION_METADATA_INVALID",
  "FOLLOWUP_INVALID",
  "HIDDEN_REASONING_NOT_ALLOWED",
  "ORCHESTRATOR_POLICY_REQUEST_INVALID",
  "ORCHESTRATOR_POLICY_DECISION_INVALID",
  "ORCHESTRATOR_POLICY_STAGE_INVALID",
  "ORCHESTRATOR_CORRELATION_INVALID",
  "ORCHESTRATOR_PRECEDENCE_VIOLATION",
  "ORCHESTRATOR_FINDING_INVALID",
  "ORCHESTRATOR_ADJUDICATION_INVALID",
  "ORCHESTRATOR_CONSTRAINT_INVALID",
  "ORCHESTRATOR_DIRECTIVE_INVALID",
  "ORCHESTRATOR_REVERSE_ADJUDICATION_MISSING",
  "ORCHESTRATOR_VERDICT_INCOMPATIBLE",
  "ORCHESTRATOR_REFERENCE_GRAPH_INVALID",
  "ORCHESTRATOR_REFERENCE_SELF_CYCLE",
  "ORCHESTRATOR_FINDING_COMPATIBILITY_INVALID",
  "ORCHESTRATOR_PROVENANCE_INVALID",
  "ORCHESTRATOR_CONSENT_TARGET_INVALID",
  "ORCHESTRATOR_RETENTION_POLICY_INVALID",
  "ORCHESTRATOR_RETENTION_DESCRIPTOR_REQUIRED",
  "ORCHESTRATOR_SCENE_TRANSITION_INVALID",
  "ORCHESTRATOR_AUDIT_VALUE_INVALID",
  "SAFETY_PRECEDENCE_REQUIRED",
  "SAFETY_DOWNGRADE_ATTEMPTED",
  "FLOW_NOT_ELIGIBLE",
  "FLOW_VERSION_NOT_ELIGIBLE",
  "SPECIALIST_INVOCATION_NOT_ALLOWED",
  "SPECIALIST_CONTEXT_AUTHORIZATION_DENIED",
  "SPECIALIST_RESPONSE_NOT_ALLOWED",
  "CONSENT_AUTHORIZATION_REQUIRED",
  "CONSENT_REVOKED",
  "CONSENT_ACTION_NOT_AUTHORIZED",
  "CHANNEL_AUTHORIZATION_DENIED",
  "MEMORY_AUTHORIZATION_DENIED",
  "TOOL_AUTHORIZATION_DENIED",
  "TOOL_CARDINALITY_VIOLATION",
  "ESCALATION_AUTHORIZATION_DENIED",
  "FLOW_UPDATE_AUTHORIZATION_DENIED",
  "FOLLOWUP_AUTHORIZATION_DENIED",
  "PRESENTATION_AUTHORIZATION_DENIED",
  "PRESENTATION_PRIVACY_DOWNGRADE",
  "PRESENTATION_SAFETY_DOWNGRADE",
  "VOICE_UI_POLICY_MISMATCH",
  "RESPONSE_COMPOSITION_DENIED",
  "SAFE_FAILURE_INVALID",
  "AUDIT_DECISION_INVALID",
  "ORCHESTRATOR_METADATA_INVALID",
  "AUDIT_CONTENT_NOT_MINIMIZED",
  "COMPATIBILITY_SEAM_REGISTRY_INVALID",
  "COMPATIBILITY_REQUEST_INVALID",
  "COMPATIBILITY_DECISION_INVALID",
  "COMPATIBILITY_MODE_INVALID",
  "COMPATIBILITY_VERSION_INVALID",
  "COMPATIBILITY_CORRELATION_INVALID",
  "COMPATIBILITY_REFERENCE_INVALID",
  "COMPATIBILITY_ADAPTER_PLAN_INVALID",
  "COMPATIBILITY_ADAPTER_BROADENING",
  "COMPATIBILITY_EFFECT_UNAUTHORIZED",
  "COMPATIBILITY_COMPARISON_INVALID",
  "COMPATIBILITY_PARITY_INVALID",
  "COMPATIBILITY_GOLDEN_CASE_INVALID",
  "COMPATIBILITY_EVIDENCE_INVALID",
  "COMPATIBILITY_FEATURE_FLAG_INVALID",
  "COMPATIBILITY_ROLLBACK_INVALID",
  "COMPATIBILITY_SAFE_FAILURE_INVALID",
  "COMPATIBILITY_AUDIT_INVALID",
  "COMPATIBILITY_SAFETY_MISMATCH",
  "COMPATIBILITY_CONSENT_MISMATCH",
] as const;

export type OrchestrationContractErrorCode =
  typeof ORCHESTRATION_CONTRACT_ERROR_CODES[number];

const SAFE_ERROR_MESSAGES: Record<OrchestrationContractErrorCode, string> = {
  STALE_QUESTION: "The answer does not match the active question.",
  STALE_SCENE: "The answer does not match the active scene.",
  STALE_FLOW_VERSION: "The answer does not match the active flow version.",
  INVALID_MODALITY: "The submitted modality is not allowed.",
  OPTION_NOT_ALLOWED: "The submitted option is not allowed.",
  ANSWER_ID_NOT_ALLOWED: "An answer ID is not allowed for this input.",
  ANSWER_ID_REQUIRED: "An answer ID is required for this input.",
  INVALID_VALUE: "The submitted value is invalid.",
  INVALID_ASSET_REFERENCE: "The asset reference is invalid.",
  INVALID_MIME_TYPE: "The asset content type is not allowed.",
  UNEXPECTED_EXPECTED_INPUT: "Expected input is not allowed in this state.",
  MISSING_EXPECTED_INPUT: "Expected input is required in this state.",
  INVALID_STATE_TRANSITION: "The flow state transition is not allowed.",
  INVALID_EVENT_SOURCE: "The event source is not allowed for this event type.",
  INVALID_EVENT_MODALITY: "The event modality is not allowed for this event type.",
  INVALID_EVENT_TRIGGER: "The event trigger is not allowed for this event type.",
  INVALID_EVENT_PAYLOAD: "The event payload is invalid for this event type.",
  MISSING_INTERRUPTED_STATE: "Interrupted flow state requires resume metadata.",
  MISSING_PENDING_TOOL: "Waiting-for-tool state requires pending-tool metadata.",
  TERMINAL_STATE_HAS_EXPECTED_INPUT: "A terminal flow state cannot retain expected input.",
  IDLE_STATE_HAS_ACTIVE_FLOW_DATA: "An idle flow cannot retain active-flow data.",
  SPECIALIST_REQUEST_INVALID: "The specialist request is invalid.",
  SPECIALIST_RESPONSE_INVALID: "The specialist response is invalid.",
  REQUEST_ID_MISMATCH: "The specialist response request identifier does not match.",
  SPECIALIST_ID_MISMATCH: "The specialist response specialist identifier does not match.",
  EMERGENCY_CHECK_REQUIRED: "A deterministic emergency check is required before specialist invocation.",
  RESPONSE_STATUS_INVARIANT_FAILED: "The specialist response does not satisfy its status requirements.",
  TOOL_NOT_AVAILABLE: "The specialist proposed a tool that is not available for this request.",
  TOOL_CONFIRMATION_CANNOT_BE_WEAKENED: "The specialist cannot weaken the tool confirmation requirement.",
  TOOL_CONSENT_NOT_ALLOWED: "Consent does not permit the proposed tool call.",
  TOOL_IDEMPOTENCY_REQUIRED: "The proposed tool call requires an idempotency key.",
  INVALID_MEMORY_PROPOSAL: "The specialist memory proposal is invalid.",
  DIRECT_EXECUTION_NOT_ALLOWED: "Specialists may propose actions but may not execute them directly.",
  ESCALATION_PROPOSAL_INVALID: "The specialist escalation proposal is invalid.",
  FLOW_UPDATE_INVALID: "The specialist flow-state update is invalid.",
  FLOW_PATCH_INVALID: "The specialist domain-state patch is invalid.",
  FLOW_CATALOGUE_INVALID: "The Flow catalogue is invalid.",
  FLOW_ID_DUPLICATE: "A Flow ID and version pair is duplicated.",
  FLOW_VERSION_INVALID: "A Flow definition version is invalid.",
  FLOW_REFERENCE_INVALID: "A Flow catalogue reference is invalid.",
  FLOW_REFERENCE_CYCLE: "The Flow catalogue contains a parent cycle.",
  CAPABILITY_ID_DUPLICATE: "A capability ID and version pair is duplicated.",
  CAPABILITY_REFERENCE_INVALID: "A capability reference is invalid.",
  FLOW_SAFETY_POLICY_INVALID: "A Flow safety policy is invalid.",
  FLOW_CONSENT_POLICY_INVALID: "A Flow consent policy is invalid.",
  FLOW_EVIDENCE_POLICY_INVALID: "A Flow evidence policy is invalid.",
  FLOW_COMPATIBILITY_INVALID: "A Flow compatibility policy is invalid.",
  FLOW_METADATA_INVALID: "Flow catalogue metadata is invalid.",
  FLOW_TRIGGER_POLICY_INVALID: "A Flow trigger and Channel policy is invalid.",
  FLOW_COLLECTION_INVALID: "A Flow collection contains invalid duplicate identifiers.",
  FLOW_OUTCOME_POLICY_INVALID: "A Flow outcome policy is invalid.",
  FLOW_TOOL_POLICY_INVALID: "A Flow Tool policy is invalid.",
  FLOW_TRUST_POLICY_INVALID: "A Trust and Safety outcome policy is invalid.",
  PRESENTATION_REGISTRY_INVALID: "The Presentation Registry is invalid.",
  PRESENTATION_ID_DUPLICATE: "A Presentation ID and version pair is duplicated.",
  PRESENTATION_VERSION_INVALID: "A Presentation Registry version is invalid.",
  PRESENTATION_REFERENCE_INVALID: "A Presentation Registry reference is invalid.",
  PRESENTATION_REFERENCE_CYCLE: "The Presentation Registry contains a reference cycle.",
  PRESENTATION_FAMILY_INVALID: "A Presentation Family is invalid.",
  PRESENTATION_SCENE_INVALID: "A Presentation scene binding is invalid.",
  PRESENTATION_FLOW_INCOMPATIBLE: "A Presentation is incompatible with its Flow.",
  PRESENTATION_CHANNEL_INCOMPATIBLE: "A Presentation Channel is incompatible.",
  PRESENTATION_DEVICE_INCOMPATIBLE: "A Presentation device policy is incompatible.",
  PRESENTATION_INPUT_INCOMPATIBLE: "A Presentation expected-input policy is incompatible.",
  PRESENTATION_INTERACTION_INVALID: "A Presentation interaction policy is invalid.",
  PRESENTATION_EVENT_MAPPING_INVALID: "A Presentation event mapping is invalid.",
  PRESENTATION_ACTION_INVALID: "A Presentation action policy is invalid.",
  PRESENTATION_VOICE_SYNC_INVALID: "A Presentation voice synchronization policy is invalid.",
  PRESENTATION_ACCESSIBILITY_INVALID: "A Presentation accessibility policy is invalid.",
  PRESENTATION_LOCALIZATION_INVALID: "A Presentation localization policy is invalid.",
  PRESENTATION_PRIVACY_INVALID: "A Presentation privacy treatment is invalid.",
  PRESENTATION_SAFETY_INVALID: "A Presentation safety treatment is invalid.",
  PRESENTATION_FALLBACK_INVALID: "A Presentation fallback policy is invalid.",
  PRESENTATION_METADATA_INVALID: "Presentation Registry metadata is invalid.",
  FOLLOWUP_INVALID: "The specialist follow-up recommendation is invalid.",
  HIDDEN_REASONING_NOT_ALLOWED: "Hidden reasoning must not cross the specialist boundary.",
  ORCHESTRATOR_POLICY_REQUEST_INVALID: "The Orchestrator policy request is invalid.",
  ORCHESTRATOR_POLICY_DECISION_INVALID: "The Orchestrator policy decision is invalid.",
  ORCHESTRATOR_POLICY_STAGE_INVALID: "The Orchestrator policy stage requirements are invalid.",
  ORCHESTRATOR_CORRELATION_INVALID: "The Orchestrator policy correlation is invalid.",
  ORCHESTRATOR_PRECEDENCE_VIOLATION: "The Orchestrator policy precedence is invalid.",
  ORCHESTRATOR_FINDING_INVALID: "The Orchestrator policy finding is invalid.",
  ORCHESTRATOR_ADJUDICATION_INVALID: "The proposal adjudication is invalid.",
  ORCHESTRATOR_CONSTRAINT_INVALID: "The proposal constraint is invalid.",
  ORCHESTRATOR_DIRECTIVE_INVALID: "The system-owned directive is invalid.",
  ORCHESTRATOR_REVERSE_ADJUDICATION_MISSING: "An approved plan is missing its required adjudication.",
  ORCHESTRATOR_VERDICT_INCOMPATIBLE: "The decision contains fields that are incompatible with its verdict.",
  ORCHESTRATOR_REFERENCE_GRAPH_INVALID: "The decision reference graph is invalid.",
  ORCHESTRATOR_REFERENCE_SELF_CYCLE: "A decision reference must not refer to itself.",
  ORCHESTRATOR_FINDING_COMPATIBILITY_INVALID: "A policy finding severity and outcome are incompatible.",
  ORCHESTRATOR_PROVENANCE_INVALID: "The approved instruction provenance is invalid.",
  ORCHESTRATOR_CONSENT_TARGET_INVALID: "The consent target authorization is invalid.",
  ORCHESTRATOR_RETENTION_POLICY_INVALID: "The evidence retention authorization is invalid.",
  ORCHESTRATOR_RETENTION_DESCRIPTOR_REQUIRED: "A required retention classification is missing.",
  ORCHESTRATOR_SCENE_TRANSITION_INVALID: "The Presentation scene transition is invalid.",
  ORCHESTRATOR_AUDIT_VALUE_INVALID: "The audit value is not permitted.",
  SAFETY_PRECEDENCE_REQUIRED: "Deterministic safety policy must take precedence.",
  SAFETY_DOWNGRADE_ATTEMPTED: "Deterministic safety cannot be downgraded.",
  FLOW_NOT_ELIGIBLE: "The Flow is not eligible for this policy decision.",
  FLOW_VERSION_NOT_ELIGIBLE: "The Flow version is not eligible for this policy decision.",
  SPECIALIST_INVOCATION_NOT_ALLOWED: "The Specialist invocation is not allowed.",
  SPECIALIST_CONTEXT_AUTHORIZATION_DENIED: "The Specialist invocation context is not authorized.",
  SPECIALIST_RESPONSE_NOT_ALLOWED: "The Specialist response is not allowed.",
  CONSENT_AUTHORIZATION_REQUIRED: "Consent authorization is required.",
  CONSENT_REVOKED: "The required consent has been revoked.",
  CONSENT_ACTION_NOT_AUTHORIZED: "The required before-action consent is not authorized.",
  CHANNEL_AUTHORIZATION_DENIED: "The Channel is not authorized.",
  MEMORY_AUTHORIZATION_DENIED: "The memory proposal is not authorized.",
  TOOL_AUTHORIZATION_DENIED: "The Tool proposal is not authorized.",
  TOOL_CARDINALITY_VIOLATION: "Only one pending Tool may be authorized.",
  ESCALATION_AUTHORIZATION_DENIED: "The escalation proposal is not authorized.",
  FLOW_UPDATE_AUTHORIZATION_DENIED: "The Flow-state update is not authorized.",
  FOLLOWUP_AUTHORIZATION_DENIED: "The follow-up proposal is not authorized.",
  PRESENTATION_AUTHORIZATION_DENIED: "The Presentation is not authorized.",
  PRESENTATION_PRIVACY_DOWNGRADE: "The Presentation privacy policy cannot be weakened.",
  PRESENTATION_SAFETY_DOWNGRADE: "The Presentation safety policy cannot be weakened.",
  VOICE_UI_POLICY_MISMATCH: "The voice and UI plan does not match the canonical Presentation policy.",
  RESPONSE_COMPOSITION_DENIED: "The response-composition plan is not authorized.",
  SAFE_FAILURE_INVALID: "The safe-failure plan is invalid.",
  AUDIT_DECISION_INVALID: "The audit decision record is invalid.",
  ORCHESTRATOR_METADATA_INVALID: "The Orchestrator policy metadata is invalid.",
  AUDIT_CONTENT_NOT_MINIMIZED: "Audit content contains prohibited raw or sensitive material.",
  COMPATIBILITY_SEAM_REGISTRY_INVALID: "The compatibility seam registry is invalid.",
  COMPATIBILITY_REQUEST_INVALID: "The compatibility evaluation request is invalid.",
  COMPATIBILITY_DECISION_INVALID: "The compatibility decision record is invalid.",
  COMPATIBILITY_MODE_INVALID: "The compatibility mode is invalid.",
  COMPATIBILITY_VERSION_INVALID: "A compatibility contract version is invalid.",
  COMPATIBILITY_CORRELATION_INVALID: "Compatibility correlation is invalid.",
  COMPATIBILITY_REFERENCE_INVALID: "A compatibility reference is invalid.",
  COMPATIBILITY_ADAPTER_PLAN_INVALID: "The adapter authorization plan is invalid.",
  COMPATIBILITY_ADAPTER_BROADENING: "An adapter may not broaden authorized behavior.",
  COMPATIBILITY_EFFECT_UNAUTHORIZED: "A proposed compatibility effect is not authorized.",
  COMPATIBILITY_COMPARISON_INVALID: "The shadow comparison record is invalid.",
  COMPATIBILITY_PARITY_INVALID: "The compatibility parity classification is invalid.",
  COMPATIBILITY_GOLDEN_CASE_INVALID: "The golden compatibility case is invalid.",
  COMPATIBILITY_EVIDENCE_INVALID: "The compatibility evidence is invalid.",
  COMPATIBILITY_FEATURE_FLAG_INVALID: "The compatibility feature-flag state is invalid.",
  COMPATIBILITY_ROLLBACK_INVALID: "The compatibility rollback plan is invalid.",
  COMPATIBILITY_SAFE_FAILURE_INVALID: "The compatibility safe-failure result is invalid.",
  COMPATIBILITY_AUDIT_INVALID: "Compatibility audit content is invalid.",
  COMPATIBILITY_SAFETY_MISMATCH: "Compatibility safety requirements do not match.",
  COMPATIBILITY_CONSENT_MISMATCH: "Compatibility consent requirements do not match.",
};

export class OrchestrationContractError extends Error {
  readonly code: OrchestrationContractErrorCode;

  constructor(code: OrchestrationContractErrorCode) {
    super(SAFE_ERROR_MESSAGES[code]);
    this.name = "OrchestrationContractError";
    this.code = code;
  }
}

export function contractError(code: OrchestrationContractErrorCode): never {
  throw new OrchestrationContractError(code);
}
