import { useState } from "react";
import { AlertTriangle, Building2, CalendarDays, Car, CircleDollarSign, Clock, ClipboardList, Home, MapPin, Navigation, ShieldCheck, Stethoscope, Truck, UserRoundPlus } from "lucide-react";
import { VoiceCanvasScene, type VoiceCanvasViewModel } from "../../components/voice-canvas";
import "./gallery.css";

const scenes: VoiceCanvasViewModel[] = [
  { sceneId:"listen", kind:"listening", title:"I'm listening", helperText:"Take your time. You can speak whenever you're ready.", status:"listening", statusLabel:"Listening" },
  { sceneId:"choice", kind:"choice", title:"Which would you prefer?", helperText:"Choose one option to continue.", progress:{current:1,total:3,label:"Step 1 of 3"}, choices:[{id:"morning",label:"This morning",icon:Clock},{id:"afternoon",label:"This afternoon",icon:CalendarDays}], primaryAction:{label:"Continue"} },
  { sceneId:"place", kind:"place", title:"Where would you like to go?", helperText:"Choose a saved place or enter somewhere new.", agentPresence:{state:"listening",label:"Listening with you",description:"You can speak or tap a destination.",accessibleLabel:"VYVA is listening while you choose a destination"}, blocks:[{kind:"option-card",id:"home",title:"Home",subtitle:"Saved place",description:"12 Garden Lane",badge:"Recommended",recommended:true,icon:Home,details:[{id:"pickup",label:"Estimated pickup",value:"8-12 min",tone:"good"},{id:"price",label:"Estimated price",value:"Reviewed before confirmation"},{id:"access",label:"Accessibility",value:"Uses saved mobility notes",tone:"good"}]},{kind:"option-card",id:"clinic",title:"Riverside Medical Centre with a deliberately long translated label",subtitle:"Saved place",description:"24 Riverside Road",icon:MapPin,details:[{id:"pickup",label:"Estimated pickup",value:"11 min"},{id:"arrival",label:"Estimated arrival",value:"10:52 AM"},{id:"reputation",label:"Reputation",value:"4.6 / 5",tone:"good"}]},{kind:"option-card",id:"new",title:"A new address",subtitle:"New destination",description:"Tell VYVA where you're going",icon:Navigation}], secondaryAction:{label:"Go back"} },
  { sceneId:"ride-provider", kind:"choice", title:"Which ride option looks best?", helperText:"Compare estimate, reputation, and available help before choosing.", progress:{current:2,total:4,label:"Step 2 of 4"}, agentPresence:{state:"thinking",label:"Checking ride options",description:"VYVA is keeping the options on screen.",accessibleLabel:"VYVA ride voice status"}, blocks:[{kind:"option-card",id:"carecab",title:"CareCab",subtitle:"Best reputation",description:"Good for appointments",badge:"Recommended",recommended:true,icon:Car,details:[{id:"pickup",label:"Estimated pickup",value:"8 min",tone:"good"},{id:"arrival",label:"Estimated arrival",value:"10:48 AM"},{id:"price",label:"Estimated price",value:"$12-$16"},{id:"reputation",label:"Reputation",value:"4.9 / 5",tone:"good"},{id:"access",label:"Accessibility",value:"Wheelchair-friendly on request",tone:"good"}]},{kind:"option-card",id:"cityride",title:"CityRide with a deliberately long company reputation label",subtitle:"Lower estimated price",description:"Standard car",icon:Car,details:[{id:"pickup",label:"Estimated pickup",value:"13 min"},{id:"arrival",label:"Estimated arrival",value:"10:55 AM"},{id:"price",label:"Estimated price",value:"$10-$14",tone:"good"},{id:"reputation",label:"Reputation",value:"4.4 / 5"}]}], secondaryAction:{label:"Go back"} },
  { sceneId:"refill-medication", kind:"choice", title:"Which medication needs a refill?", helperText:"Choose one saved medication, or enter another exactly from the label.", progress:{current:1,total:7,label:"Step 1 of 7"}, agentPresence:{state:"listening",label:"Listening with you",description:"You can say the medication or tap a card.",accessibleLabel:"VYVA refill voice status"}, blocks:[{kind:"option-card",id:"medication:metformin",title:"Metformin",subtitle:"Saved medication",description:"500 mg",badge:"Recommended",recommended:true,icon:ClipboardList,details:[{id:"strength",label:"Strength",value:"500 mg"},{id:"profile",label:"Saved profile",value:"Medication profile",tone:"good"},{id:"review",label:"Review before action",value:"Review before action"}]},{kind:"option-card",id:"medication:long",title:"Hidroclorotiazida con una etiqueta traducida especialmente extensa para probar el ajuste visual",subtitle:"Saved medication",description:"20 mg",icon:ClipboardList,details:[{id:"strength",label:"Strength",value:"20 mg"},{id:"profile",label:"Saved profile",value:"Medication profile",tone:"good"}]},{kind:"option-card",id:"manual-medication",title:"A different medication",subtitle:"Manual entry",description:"Enter the medication name",icon:UserRoundPlus,details:[{id:"review",label:"Review before action",value:"Review before action"}]}], secondaryAction:{label:"Go back"} },
  { sceneId:"refill-safety", kind:"choice", title:"Is this only a routine refill?", helperText:"This flow is for routine refill preparation only.", progress:{current:3,total:7,label:"Step 3 of 7"}, agentPresence:{state:"thinking",label:"Keeping the boundary clear",description:"VYVA will stop if urgent help is needed.",accessibleLabel:"VYVA safety boundary voice status"}, blocks:[{kind:"option-card",id:"routine",title:"Routine refill",subtitle:"Routine refill only",description:"No severe symptoms or possible overdose.",icon:ShieldCheck,details:[{id:"dosing",label:"No dosing changes",value:"No dosing changes",tone:"good"},{id:"review",label:"Review before action",value:"Review before action"}]},{kind:"option-card",id:"urgent",title:"I need urgent help",subtitle:"Urgent issue stops this flow",description:"Severe reaction, possible overdose, or time-critical medicine issue.",icon:AlertTriangle,details:[{id:"urgent",label:"Urgent safety boundary",value:"This path is blocked and safe",tone:"caution"}]}], secondaryAction:{label:"Go back"} },
  { sceneId:"refill-provider", kind:"choice", title:"Who should review the refill?", helperText:"Choose one prescriber or pharmacy for later review.", progress:{current:4,total:7,label:"Step 4 of 7"}, blocks:[{kind:"option-card",id:"provider:gp",title:"Dr Garcia",subtitle:"Prescriber",description:"Saved in your profile",badge:"Recommended",recommended:true,icon:Stethoscope,details:[{id:"type",label:"Provider type",value:"Prescriber"},{id:"review",label:"Review before action",value:"Review before action"}]},{kind:"option-card",id:"provider:pharmacy",title:"Riverside Pharmacy with a deliberately long translated branch and provider label",subtitle:"Pharmacy",description:"Saved pharmacy",icon:Home,details:[{id:"type",label:"Provider type",value:"Pharmacy"},{id:"review",label:"Review before action",value:"Review before action"}]}], secondaryAction:{label:"Go back"} },
  { sceneId:"shopping-retailer", kind:"choice", title:"Which retailer would you like?", helperText:"Choose a saved retailer or add another. Nothing is ordered or paid for here.", progress:{current:1,total:9,label:"Step 1 of 9"}, agentPresence:{state:"listening",label:"Listening with you",description:"You can say the retailer or tap a card.",accessibleLabel:"VYVA shopping voice status"}, blocks:[{kind:"option-card",id:"retailer:market",title:"Neighbourhood Market",subtitle:"Saved retailer",description:"Saved in your profile",badge:"Recommended",recommended:true,icon:Building2,details:[{id:"type",label:"Retailer type",value:"Grocery"},{id:"estimate",label:"Estimate",value:"Unverified",tone:"caution"},{id:"fees",label:"Fees",value:"Unverified",tone:"caution"},{id:"review",label:"Review before action",value:"Review before action"}]},{kind:"option-card",id:"retailer:long",title:"Supermercado Cooperativo de Productos Locales y Entrega Accesible",subtitle:"Saved retailer",description:"Long translated retailer label",icon:Building2,details:[{id:"type",label:"Retailer type",value:"Co-op"},{id:"boundary",label:"No order or payment",value:"No order or payment",tone:"good"}]},{kind:"option-card",id:"retailer:other",title:"Another retailer",subtitle:"Manual entry",description:"Enter the exact name",icon:UserRoundPlus,details:[{id:"review",label:"Review before action",value:"Review before action"}]}], secondaryAction:{label:"Back"} },
  { sceneId:"shopping-fulfillment", kind:"choice", title:"Delivery or collection?", helperText:"Choose one shopping path to prepare.", progress:{current:4,total:9,label:"Step 4 of 9"}, blocks:[{kind:"option-card",id:"fulfillment:delivery",title:"Delivery",subtitle:"Delivery prepared, not ordered",description:"Prepare delivery to an address",icon:Truck,details:[{id:"fulfillment",label:"Fulfilment",value:"Delivery"},{id:"boundary",label:"No order or payment",value:"No order or payment",tone:"good"}]},{kind:"option-card",id:"estimate:unverified",title:"Not yet",subtitle:"Unverified",description:"Costs, fees, and availability stay unverified until reviewed.",icon:CircleDollarSign,details:[{id:"availability",label:"Availability",value:"Unverified",tone:"caution"},{id:"review",label:"Review before action",value:"Review before action"}]}], secondaryAction:{label:"Back"} },
  { sceneId:"date", kind:"date-time", title:"When should it happen?", helperText:"Choose the date first, then the time.", choices:[{id:"today",label:"Today",icon:CalendarDays},{id:"tomorrow",label:"Tomorrow",icon:CalendarDays}], textEntry:{label:"Time",value:"10:30",type:"time",accessibleLabel:"Choose a time"}, primaryAction:{label:"Continue"} },
  { sceneId:"text", kind:"text-entry", title:"What address should we use?", helperText:"You can type the full address or just the postcode.", textEntry:{label:"Address",value:"",placeholder:"Start typing an address",accessibleLabel:"Destination address"},primaryAction:{label:"Continue",disabled:true},secondaryAction:{label:"Go back"} },
  { sceneId:"review", kind:"review", title:"Does everything look right?", helperText:"Nothing will happen until you confirm.", progress:{current:4,total:4,label:"Step 4 of 4"},summaryRows:[{id:"place",label:"Destination",value:"Riverside Medical Centre"},{id:"provider",label:"Ride option",value:"CareCab"},{id:"date",label:"Date",value:"Tuesday, 21 July"},{id:"time",label:"Time",value:"10:30 AM"}],primaryAction:{label:"Confirm details"},secondaryAction:{label:"Make a change"} },
  { sceneId:"waiting", kind:"waiting", title:"Checking the details", helperText:"This may take a moment. You can stay on this screen.", status:"loading",statusLabel:"Please wait",primaryAction:{label:"Checking...",loading:true},secondaryAction:{label:"Cancel"} },
  { sceneId:"done", kind:"completed", title:"Everything is ready", helperText:"Your details have been confirmed.",status:"success",statusLabel:"Completed",summaryRows:[{id:"ref",label:"Reference",value:"VYVA 2486"}],primaryAction:{label:"Done"} },
  { sceneId:"blocked", kind:"blocked", title:"We need one more detail", helperText:"Please add a phone number before continuing.",status:"blocked",statusLabel:"More information needed",primaryAction:{label:"Add phone number"},secondaryAction:{label:"Not now"} },
];

export function VoiceCanvasGallery() {
  const [selected, setSelected] = useState(0);
  const [text, setText] = useState("");
  const scene = scenes[selected];
  const viewModel = scene.sceneId === "text" ? { ...scene, textEntry:{ ...scene.textEntry!, value:text }, primaryAction:{...scene.primaryAction!,disabled:!text.trim()} } : scene;
  return <main className="vc-gallery">
    <header><p>VYVA · Visual Kit v1</p><h1>Voice Canvas scenes</h1><span>Presentation-only component gallery</span></header>
    <nav aria-label="Choose a scene">{scenes.map((item,index)=><button key={item.sceneId} type="button" aria-current={selected===index?"page":undefined} onClick={()=>setSelected(index)}>{index+1}. {item.kind}</button>)}</nav>
    <div className="vc-gallery-stage"><VoiceCanvasScene viewModel={viewModel} onChoice={()=>{}} onPrimary={()=>{}} onSecondary={()=>{}} onTextChange={setText} /></div>
  </main>;
}

export default VoiceCanvasGallery;
