import { useState } from "react";
import { CalendarDays, Car, Clock, Home, MapPin, Navigation } from "lucide-react";
import { VoiceCanvasScene, type VoiceCanvasViewModel } from "../../components/voice-canvas";
import "./gallery.css";

const scenes: VoiceCanvasViewModel[] = [
  { sceneId:"listen", kind:"listening", title:"I'm listening", helperText:"Take your time. You can speak whenever you're ready.", status:"listening", statusLabel:"Listening" },
  { sceneId:"choice", kind:"choice", title:"Which would you prefer?", helperText:"Choose one option to continue.", progress:{current:1,total:3,label:"Step 1 of 3"}, choices:[{id:"morning",label:"This morning",icon:Clock},{id:"afternoon",label:"This afternoon",icon:CalendarDays}], primaryAction:{label:"Continue"} },
  { sceneId:"place", kind:"place", title:"Where would you like to go?", helperText:"Choose a saved place or enter somewhere new.", agentPresence:{state:"listening",label:"Listening with you",description:"You can speak or tap a destination.",accessibleLabel:"VYVA is listening while you choose a destination"}, blocks:[{kind:"option-card",id:"home",title:"Home",subtitle:"Saved place",description:"12 Garden Lane",badge:"Recommended",recommended:true,icon:Home,details:[{id:"pickup",label:"Estimated pickup",value:"8-12 min",tone:"good"},{id:"price",label:"Estimated price",value:"Reviewed before confirmation"},{id:"access",label:"Accessibility",value:"Uses saved mobility notes",tone:"good"}]},{kind:"option-card",id:"clinic",title:"Riverside Medical Centre with a deliberately long translated label",subtitle:"Saved place",description:"24 Riverside Road",icon:MapPin,details:[{id:"pickup",label:"Estimated pickup",value:"11 min"},{id:"arrival",label:"Estimated arrival",value:"10:52 AM"},{id:"reputation",label:"Reputation",value:"4.6 / 5",tone:"good"}]},{kind:"option-card",id:"new",title:"A new address",subtitle:"New destination",description:"Tell VYVA where you're going",icon:Navigation}], secondaryAction:{label:"Go back"} },
  { sceneId:"ride-provider", kind:"choice", title:"Which ride option looks best?", helperText:"Compare estimate, reputation, and available help before choosing.", progress:{current:2,total:4,label:"Step 2 of 4"}, agentPresence:{state:"thinking",label:"Checking ride options",description:"VYVA is keeping the options on screen.",accessibleLabel:"VYVA ride voice status"}, blocks:[{kind:"option-card",id:"carecab",title:"CareCab",subtitle:"Best reputation",description:"Good for appointments",badge:"Recommended",recommended:true,icon:Car,details:[{id:"pickup",label:"Estimated pickup",value:"8 min",tone:"good"},{id:"arrival",label:"Estimated arrival",value:"10:48 AM"},{id:"price",label:"Estimated price",value:"$12-$16"},{id:"reputation",label:"Reputation",value:"4.9 / 5",tone:"good"},{id:"access",label:"Accessibility",value:"Wheelchair-friendly on request",tone:"good"}]},{kind:"option-card",id:"cityride",title:"CityRide with a deliberately long company reputation label",subtitle:"Lower estimated price",description:"Standard car",icon:Car,details:[{id:"pickup",label:"Estimated pickup",value:"13 min"},{id:"arrival",label:"Estimated arrival",value:"10:55 AM"},{id:"price",label:"Estimated price",value:"$10-$14",tone:"good"},{id:"reputation",label:"Reputation",value:"4.4 / 5"}]}], secondaryAction:{label:"Go back"} },
  { sceneId:"date", kind:"date-time", title:"When should it happen?", helperText:"Choose the date first, then the time.", choices:[{id:"today",label:"Today",icon:CalendarDays},{id:"tomorrow",label:"Tomorrow",icon:CalendarDays}], textEntry:{label:"Time",value:"10:30",type:"time",accessibleLabel:"Choose a time"}, primaryAction:{label:"Continue"} },
  { sceneId:"text", kind:"text-entry", title:"What address should we use?", helperText:"You can type the full address or just the postcode.", textEntry:{label:"Address",value:"",placeholder:"Start typing an address",accessibleLabel:"Destination address"},primaryAction:{label:"Continue",disabled:true},secondaryAction:{label:"Go back"} },
  { sceneId:"review", kind:"review", title:"Does everything look right?", helperText:"Nothing will happen until you confirm.", progress:{current:4,total:4,label:"Step 4 of 4"},summaryRows:[{id:"place",label:"Destination",value:"Riverside Medical Centre"},{id:"provider",label:"Ride option",value:"CareCab"},{id:"date",label:"Date",value:"Tuesday, 21 July"},{id:"time",label:"Time",value:"10:30 AM"}],primaryAction:{label:"Confirm details"},secondaryAction:{label:"Make a change"} },
  { sceneId:"waiting", kind:"waiting", title:"Checking the details", helperText:"This may take a moment. You can stay on this screen.", status:"loading",statusLabel:"Please wait",primaryAction:{label:"Checking...",loading:true},secondaryAction:{label:"Cancel"} },
  { sceneId:"done", kind:"completed", title:"Everything is ready", helperText:"Your details have been confirmed.",status:"success",statusLabel:"Completed",summaryRows:[{id:"ref",label:"Reference",value:"VYVA 2486"}],primaryAction:{label:"Done"} },
  { sceneId:"blocked", kind:"blocked", title:"We need one more detail", helperText:"Please add a phone number before continuing.",status:"blocked",statusLabel:"More information needed",primaryAction:{label:"Add phone number"},secondaryAction:{label:"Not now"} },
];

export function VoiceCanvasGallery() {
  const [selected, setSelected] = useState(0);
  const [text, setText] = useState("");
  const scene = scenes[selected];
  const viewModel = scene.sceneId === "text" ? { ...scene, textEntry:{ ...scene.textEntry!, value:text }, primaryAction:{...scene.primaryAction!,disabled:!text.trim()} } : scene;
  return <main className="vc-gallery">
    <header><p>VYVA · Visual Kit v1</p><h1>Voice Canvas scenes</h1><span>Presentation-only component gallery</span></header>
    <nav aria-label="Choose a scene">{scenes.map((item,index)=><button key={item.sceneId} type="button" aria-current={selected===index?"page":undefined} onClick={()=>setSelected(index)}>{index+1}. {item.kind}</button>)}</nav>
    <div className="vc-gallery-stage"><VoiceCanvasScene viewModel={viewModel} onChoice={()=>{}} onPrimary={()=>{}} onSecondary={()=>{}} onTextChange={setText} /></div>
  </main>;
}

export default VoiceCanvasGallery;
