export {
  TRIAGE_PROTOCOLS,
  evaluateTriage,
  evaluateTriageRules,
} from "./engine/evaluateTriage.js";

export {
  CRITICAL_RED_FLAG_IDS,
  applyTriageSafetyFloor,
  buildFallbackTriageReport,
  fallbackReportContent,
  firstAnswerKind,
  hasAnswer,
  nextAdaptiveStage,
  nextStepFor,
  profileConsiderationsFor,
  profileRiskFlags,
  scanNotesFor,
  selectedAnswers,
  selectedSafetyAnswer,
  selectedSymptomId,
  shouldCompleteFromRules,
  symptomLabel,
  uniqueStrings,
  vitalsNotesFor,
  watchSignsFor,
} from "./engine/routeOutcome.js";

export type {
  ProfileRiskFlags,
  LocalizeTriageText,
  ProtocolProfileModifier,
  ProtocolRule,
  RaiseTriageLevel,
  TriageChatMessage,
  TriageHealthMemory,
  TriageProtocol,
  TriageRuleDecision,
  TriageRuleInput,
  TriageRuleLevel,
  TriageRuleRiskFlags,
  TriageSummary,
  TriageUrgency,
  TriageVitals,
  TriageWizardAnswer,
  TriageWizardContext,
  WizardStage,
} from "./types.js";
