create extension if not exists pgcrypto;

create table if not exists concierge_shopping_products (
  id uuid primary key default gen_random_uuid(),
  product_id text not null unique,
  category text not null,
  name jsonb not null default '{}'::jsonb,
  price_label jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,
  benefits jsonb not null default '{}'::jsonb,
  tags text[] not null default '{}'::text[],
  suitability jsonb not null default '{}'::jsonb,
  cautions jsonb not null default '{}'::jsonb,
  accessibility_notes jsonb not null default '{}'::jsonb,
  availability_label jsonb not null default '{}'::jsonb,
  price_tier text not null default 'medium',
  is_enabled boolean not null default true,
  priority integer not null default 50,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists concierge_shopping_packages (
  id uuid primary key default gen_random_uuid(),
  package_id text not null unique,
  label jsonb not null default '{}'::jsonb,
  description jsonb not null default '{}'::jsonb,
  need_text jsonb not null default '{}'::jsonb,
  category text not null default 'safe_home',
  priorities text[] not null default '{}'::text[],
  constraints jsonb not null default '{}'::jsonb,
  cta_label jsonb not null default '{}'::jsonb,
  service_request boolean not null default false,
  is_enabled boolean not null default true,
  priority integer not null default 50,
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists concierge_shopping_package_items (
  id uuid primary key default gen_random_uuid(),
  package_id text not null references concierge_shopping_packages(package_id) on delete cascade,
  product_id text not null references concierge_shopping_products(product_id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint concierge_shopping_package_items_unique unique(package_id, product_id)
);

create index if not exists concierge_shopping_products_enabled_priority_idx on concierge_shopping_products(is_enabled, priority desc);
create index if not exists concierge_shopping_packages_enabled_priority_idx on concierge_shopping_packages(is_enabled, priority desc);
create index if not exists concierge_shopping_package_items_package_idx on concierge_shopping_package_items(package_id);

insert into concierge_shopping_products (product_id, category, name, price_label, description, benefits, tags, suitability, cautions, accessibility_notes, availability_label, price_tier, is_enabled, priority, admin_notes) values
  ('low-sodium-lentil-soup', 'groceries', '{"en":"Low-sodium lentil soup multipack","es":"Pack de sopa de lentejas baja en sal"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A simple warm meal with protein, easy to keep in the cupboard.","es":"Una comida caliente sencilla con proteina, facil de guardar en la despensa."}'::jsonb, '{"en":["Low salt","Ready quickly","Good pantry backup"],"es":["Baja en sal","Lista rapido","Buena reserva de despensa"]}'::jsonb, array['food', 'meal', 'soup', 'protein', 'low_sodium', 'pantry', 'budget', 'easy_meal', 'vegetarian', 'simple']::text[], '{"en":["Good when cooking feels tiring","Useful for a quick lunch"],"es":["Buena cuando cocinar cansa","Util para una comida rapida"]}'::jsonb, '{"en":["Check the label for allergens before choosing."],"es":["Revise la etiqueta por si contiene alergenos antes de elegir."]}'::jsonb, '{"en":["Choose ring-pull cans or cartons if hand strength is limited."],"es":["Elija latas con anilla o envases de carton si tiene poca fuerza en las manos."]}'::jsonb, '{"en":"Usually easy to find in supermarkets","es":"Suele encontrarse en supermercados"}'::jsonb, 'low', true, 100, 'Seeded from VYVA mock catalog'),
  ('ready-cut-soft-fruit', 'groceries', '{"en":"Ready-cut soft fruit cups","es":"Vasos de fruta blanda ya cortada"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"Soft fruit prepared in small portions with no peeling or chopping.","es":"Fruta blanda preparada en porciones pequenas, sin pelar ni cortar."}'::jsonb, '{"en":["No preparation","Soft texture","Small portions"],"es":["Sin preparacion","Textura blanda","Porciones pequenas"]}'::jsonb, array['food', 'fruit', 'soft_food', 'no_prep', 'simple', 'delivery', 'fresh', 'easy_to_eat']::text[], '{"en":["Good for an easy snack","Helpful when chewing is harder"],"es":["Buena para un tentempie facil","Util cuando masticar cuesta mas"]}'::jsonb, '{"en":["Check sugar content if blood sugar is a concern."],"es":["Revise el azucar si la glucosa es una preocupacion."]}'::jsonb, '{"en":["Look for easy-peel lids and clear expiry dates."],"es":["Busque tapas faciles de abrir y fecha de caducidad clara."]}'::jsonb, '{"en":"Best when delivered or bought fresh","es":"Mejor con entrega o compra fresca"}'::jsonb, 'medium', true, 99, 'Seeded from VYVA mock catalog'),
  ('plain-protein-yogurt', 'groceries', '{"en":"Plain high-protein yogurt multipack","es":"Pack de yogur natural alto en proteina"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"A soft, simple breakfast or snack with protein and calcium.","es":"Desayuno o tentempie blando y sencillo con proteina y calcio."}'::jsonb, '{"en":["Soft texture","Protein","No cooking"],"es":["Textura blanda","Proteina","Sin cocinar"]}'::jsonb, array['food', 'protein', 'breakfast', 'soft_food', 'no_prep', 'simple', 'calcium', 'dairy']::text[], '{"en":["Good when appetite is low","Easy with fruit or oats"],"es":["Bueno cuando hay poco apetito","Facil con fruta o avena"]}'::jsonb, '{"en":["Not suitable for dairy allergy or lactose intolerance unless labelled accordingly."],"es":["No adecuado para alergia a lacteos o intolerancia a la lactosa salvo que lo indique la etiqueta."]}'::jsonb, '{"en":["Choose larger print labels and easy-open multipacks."],"es":["Elija etiquetas de letra grande y packs faciles de abrir."]}'::jsonb, '{"en":"Available in most supermarkets","es":"Disponible en la mayoria de supermercados"}'::jsonb, 'medium', true, 98, 'Seeded from VYVA mock catalog'),
  ('wholegrain-porridge-oats', 'groceries', '{"en":"Wholegrain porridge oats","es":"Avena integral para gachas"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A warm, budget-friendly breakfast that can be made soft.","es":"Desayuno caliente y economico que puede prepararse blando."}'::jsonb, '{"en":["Budget friendly","Filling","Easy to soften"],"es":["Economico","Saciante","Facil de ablandar"]}'::jsonb, array['food', 'breakfast', 'budget', 'soft_food', 'pantry', 'simple', 'fiber']::text[], '{"en":["Good for a simple breakfast routine","Works with milk or water"],"es":["Bueno para una rutina de desayuno sencilla","Funciona con leche o agua"]}'::jsonb, '{"en":["Choose gluten-free only if needed and clearly labelled."],"es":["Elija sin gluten solo si lo necesita y esta claramente etiquetado."]}'::jsonb, '{"en":["A lightweight bag or small box is easier to handle."],"es":["Una bolsa ligera o caja pequena es mas facil de manejar."]}'::jsonb, '{"en":"Long shelf life","es":"Caducidad larga"}'::jsonb, 'low', true, 97, 'Seeded from VYVA mock catalog'),
  ('small-water-bottle-multipack', 'groceries', '{"en":"Small water bottle multipack","es":"Pack de botellas pequenas de agua"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"Small bottles of water that are easier to lift, open, and keep nearby.","es":"Botellas pequenas de agua mas faciles de levantar, abrir y tener cerca."}'::jsonb, '{"en":["Easy to keep nearby","Small bottles are lighter","Simple option"],"es":["Facil de tener cerca","Botellas pequenas mas ligeras","Opcion sencilla"]}'::jsonb, array['food', 'water', 'hydration', 'fluids', 'delivery', 'low_lift', 'simple', 'budget']::text[], '{"en":["Good when drinks need to be close at hand","Helpful when large bottles are too heavy"],"es":["Buena cuando las bebidas deben estar a mano","Util si las botellas grandes pesan demasiado"]}'::jsonb, '{"en":["Ask a clinician if you have been told to limit fluids."],"es":["Consulte a un clinico si le han indicado limitar liquidos."]}'::jsonb, '{"en":["Choose easy-open caps if hand strength is limited."],"es":["Elija tapones faciles de abrir si tiene poca fuerza en las manos."]}'::jsonb, '{"en":"Usually easy to order with groceries","es":"Suele pedirse facilmente con la compra"}'::jsonb, 'low', true, 96, 'Seeded from VYVA mock catalog'),
  ('low-sugar-electrolyte-drinks', 'groceries', '{"en":"Low-sugar electrolyte drinks","es":"Bebidas con electrolitos bajas en azucar"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"Ready-to-drink electrolyte bottles for short-term hydration support.","es":"Botellas listas para tomar con electrolitos para apoyo puntual de hidratacion."}'::jsonb, '{"en":["No mixing needed","Easy to sip","Delivery friendly"],"es":["Sin mezclar","Facil de beber a sorbos","Apta para entrega"]}'::jsonb, array['food', 'hydration', 'fluids', 'electrolyte', 'delivery', 'simple', 'sugar']::text[], '{"en":["Good when mixing powders is inconvenient","Helpful for a short support kit"],"es":["Buena si mezclar polvos no es comodo","Util para un kit de apoyo puntual"]}'::jsonb, '{"en":["Check sugar, salt, kidney, heart, or fluid-restriction advice before choosing."],"es":["Revise azucar, sal y consejo sobre rinon, corazon o restriccion de liquidos antes de elegir."]}'::jsonb, '{"en":["Pick smaller bottles if carrying or grip is difficult."],"es":["Elija botellas pequenas si cargar o agarrar cuesta."]}'::jsonb, '{"en":"Common grocery or pharmacy item","es":"Comun en supermercado o farmacia"}'::jsonb, 'medium', true, 95, 'Seeded from VYVA mock catalog'),
  ('oral-rehydration-sachets', 'pharmacy_basics', '{"en":"Oral rehydration salt sachets","es":"Sobres de sales de rehidratacion oral"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"Sachets that mix with water for oral rehydration support.","es":"Sobres que se mezclan con agua para apoyo de rehidratacion oral."}'::jsonb, '{"en":["Small to store","Clear portions","Useful pharmacy basic"],"es":["Ocupan poco","Porciones claras","Basico util de farmacia"]}'::jsonb, array['pharmacy', 'hydration', 'fluids', 'rehydration', 'oral_rehydration', 'electrolyte', 'simple', 'safety']::text[], '{"en":["Good to ask a pharmacist about","Useful when a clinician recommends rehydration support"],"es":["Buena para consultar con farmacia","Util cuando un clinico recomienda apoyo de rehidratacion"]}'::jsonb, '{"en":["Ask a pharmacist or doctor first if symptoms are severe, ongoing, or fluids are difficult."],"es":["Consulte primero a farmacia o medico si los sintomas son fuertes, continuos o cuesta tomar liquidos."]}'::jsonb, '{"en":["Check that mixing instructions are large enough to read."],"es":["Compruebe que las instrucciones de mezcla sean faciles de leer."]}'::jsonb, '{"en":"Common pharmacy item","es":"Articulo comun de farmacia"}'::jsonb, 'medium', true, 94, 'Seeded from VYVA mock catalog'),
  ('large-print-pill-organizer', 'pharmacy_basics', '{"en":"Large-print weekly pill organizer","es":"Pastillero semanal con letra grande"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A simple weekly organizer with large day labels.","es":"Organizador semanal sencillo con etiquetas grandes por dia."}'::jsonb, '{"en":["Large labels","Simple weekly view","Helps reduce confusion"],"es":["Etiquetas grandes","Vista semanal sencilla","Ayuda a reducir confusion"]}'::jsonb, array['pharmacy', 'medicine', 'medication', 'pill', 'large_print', 'simple', 'budget', 'safety', 'memory', 'confusion']::text[], '{"en":["Good if medicines are easy to mix up","Helpful for a weekly routine"],"es":["Bueno si es facil confundir medicinas","Util para una rutina semanal"]}'::jsonb, '{"en":["Ask a pharmacist before changing how medicines are stored."],"es":["Consulte con un farmaceutico antes de cambiar como guarda sus medicinas."]}'::jsonb, '{"en":["Choose lids that open without sharp pressure."],"es":["Elija tapas que abran sin hacer mucha presion."]}'::jsonb, '{"en":"Common pharmacy item","es":"Articulo comun de farmacia"}'::jsonb, 'low', true, 93, 'Seeded from VYVA mock catalog'),
  ('large-display-thermometer', 'pharmacy_basics', '{"en":"Large-display digital thermometer","es":"Termometro digital de pantalla grande"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"A thermometer with a large display and simple one-button use.","es":"Termometro con pantalla grande y uso sencillo de un boton."}'::jsonb, '{"en":["Large display","Quick reading","Simple button"],"es":["Pantalla grande","Lectura rapida","Boton sencillo"]}'::jsonb, array['pharmacy', 'temperature', 'fever', 'large_print', 'simple', 'safety', 'easy_read']::text[], '{"en":["Good for checking fever clearly","Useful for a home health kit"],"es":["Bueno para comprobar fiebre con claridad","Util para un botiquin en casa"]}'::jsonb, '{"en":["Follow the instructions and seek medical advice for concerning symptoms."],"es":["Siga las instrucciones y busque consejo medico ante sintomas preocupantes."]}'::jsonb, '{"en":["Look for an audible beep and a display that lights up."],"es":["Busque pitido audible y pantalla iluminada."]}'::jsonb, '{"en":"Common pharmacy item","es":"Articulo comun de farmacia"}'::jsonb, 'medium', true, 92, 'Seeded from VYVA mock catalog'),
  ('fragrance-free-moisturizer', 'pharmacy_basics', '{"en":"Fragrance-free dry skin moisturizer","es":"Crema hidratante sin perfume para piel seca"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"A gentle moisturizer for dry or sensitive skin.","es":"Crema suave para piel seca o sensible."}'::jsonb, '{"en":["Fragrance-free","Sensitive skin","Easy daily use"],"es":["Sin perfume","Piel sensible","Uso diario facil"]}'::jsonb, array['pharmacy', 'skin', 'dry_skin', 'sensitive', 'fragrance_free', 'allergy', 'simple']::text[], '{"en":["Good when scented products irritate skin","Useful after hand washing"],"es":["Buena cuando los productos perfumados irritan","Util despues de lavarse las manos"]}'::jsonb, '{"en":["Stop using it if irritation starts and ask a pharmacist if unsure."],"es":["Deje de usarla si aparece irritacion y consulte con un farmaceutico si duda."]}'::jsonb, '{"en":["Pump bottles are easier than screw lids."],"es":["Los botes con dosificador son mas faciles que las tapas de rosca."]}'::jsonb, '{"en":"Available in pharmacies and supermarkets","es":"Disponible en farmacias y supermercados"}'::jsonb, 'medium', true, 91, 'Seeded from VYVA mock catalog'),
  ('easy-on-compression-socks', 'pharmacy_basics', '{"en":"Easy-on light compression socks","es":"Calcetines de compresion ligera faciles de poner"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"Light support socks designed to be easier to pull on.","es":"Calcetines de soporte ligero pensados para ponerse con menos esfuerzo."}'::jsonb, '{"en":["Easy-on design","Light support","Comfort cuff"],"es":["Diseno facil de poner","Soporte ligero","Punio comodo"]}'::jsonb, array['pharmacy', 'legs', 'compression', 'mobility', 'accessibility', 'support']::text[], '{"en":["May help with tired legs when appropriate","Easier than firm compression styles"],"es":["Puede ayudar con piernas cansadas cuando sea adecuado","Mas facil que modelos de compresion fuerte"]}'::jsonb, '{"en":["Ask a doctor or pharmacist first if there are circulation, diabetes, or wound concerns."],"es":["Consulte antes con medico o farmaceutico si hay problemas de circulacion, diabetes o heridas."]}'::jsonb, '{"en":["Choose easy-on or zip styles if bending is hard."],"es":["Elija modelos faciles o con cremallera si agacharse cuesta."]}'::jsonb, '{"en":"Pharmacy or mobility shop item","es":"Articulo de farmacia o tienda de movilidad"}'::jsonb, 'medium', true, 90, 'Seeded from VYVA mock catalog'),
  ('laundry-detergent-sheets', 'household', '{"en":"Lightweight laundry detergent sheets","es":"Laminas ligeras de detergente para ropa"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"Small detergent sheets that avoid lifting a heavy bottle.","es":"Laminas pequenas de detergente que evitan levantar una botella pesada."}'::jsonb, '{"en":["Light to carry","No measuring liquid","Less mess"],"es":["Ligero de llevar","Sin medir liquido","Menos derrames"]}'::jsonb, array['household', 'laundry', 'low_lift', 'simple', 'accessibility', 'delivery']::text[], '{"en":["Good if heavy bottles are difficult","Useful for smaller homes"],"es":["Bueno si las botellas pesadas son dificiles","Util para casas pequenas"]}'::jsonb, '{"en":["Keep detergent away from children and pets."],"es":["Mantenga el detergente lejos de ninos y mascotas."]}'::jsonb, '{"en":["Flat packets are easier to store at waist height."],"es":["Los paquetes planos son mas faciles de guardar a la altura de la cintura."]}'::jsonb, '{"en":"Available online and in larger supermarkets","es":"Disponible online y en supermercados grandes"}'::jsonb, 'medium', true, 89, 'Seeded from VYVA mock catalog'),
  ('motion-night-lights', 'household', '{"en":"Plug-in motion night lights","es":"Luces nocturnas con sensor de movimiento"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"Small lights that switch on automatically in dark hallways.","es":"Luces pequenas que se encienden solas en pasillos oscuros."}'::jsonb, '{"en":["Automatic light","Low cost","Helps at night"],"es":["Luz automatica","Precio bajo","Ayuda por la noche"]}'::jsonb, array['household', 'safety', 'fall_prevention', 'night', 'night_trip', 'lighting', 'bathroom', 'trip_hazard', 'home_safety', 'budget', 'simple', 'accessibility']::text[], '{"en":["Good for night-time bathroom trips","Helpful in hallways and bedrooms"],"es":["Buenas para ir al bano de noche","Utiles en pasillos y dormitorios"]}'::jsonb, '{"en":["Do not overload sockets or place lights where they block walking space."],"es":["No sobrecargue enchufes ni coloque luces donde bloqueen el paso."]}'::jsonb, '{"en":["No app or small switch needed once plugged in."],"es":["No necesita app ni interruptor pequeno una vez enchufada."]}'::jsonb, '{"en":"Easy to find online or in hardware shops","es":"Facil de encontrar online o en ferreterias"}'::jsonb, 'low', true, 88, 'Seeded from VYVA mock catalog'),
  ('easy-grip-jar-opener', 'household', '{"en":"Easy-grip jar opener","es":"Abridor de tarros de agarre facil"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A simple grip aid for opening jars with less hand strain.","es":"Ayuda sencilla para abrir tarros con menos esfuerzo en la mano."}'::jsonb, '{"en":["Low cost","Helps hand grip","No batteries"],"es":["Precio bajo","Ayuda al agarre","Sin pilas"]}'::jsonb, array['household', 'arthritis', 'grip', 'hands', 'budget', 'simple', 'accessibility', 'kitchen', 'home_safety']::text[], '{"en":["Good if jars are hard to open","Useful in the kitchen"],"es":["Bueno si cuesta abrir tarros","Util en la cocina"]}'::jsonb, '{"en":["Choose a stable model that does not slip."],"es":["Elija un modelo estable que no resbale."]}'::jsonb, '{"en":["Large handles are easier than thin rubber discs for some hands."],"es":["Los mangos grandes pueden ser mas faciles que discos finos de goma."]}'::jsonb, '{"en":"Common kitchen aid","es":"Ayuda de cocina comun"}'::jsonb, 'low', true, 87, 'Seeded from VYVA mock catalog'),
  ('long-handle-dustpan', 'household', '{"en":"Long-handle dustpan and brush","es":"Recogedor y cepillo de mango largo"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A light cleaning set that reduces bending for small spills.","es":"Set de limpieza ligero que reduce agacharse para pequenos derrames."}'::jsonb, '{"en":["Less bending","Lightweight","Simple storage"],"es":["Menos agacharse","Ligero","Guardado sencillo"]}'::jsonb, array['household', 'cleaning', 'mobility', 'low_lift', 'bending', 'less_bending', 'trip_hazard', 'home_safety', 'budget', 'simple', 'accessibility']::text[], '{"en":["Good when bending is uncomfortable","Useful for quick tidy-ups"],"es":["Bueno si agacharse incomoda","Util para limpiezas rapidas"]}'::jsonb, '{"en":["Store it where it cannot become a trip hazard."],"es":["Guardelo donde no suponga riesgo de tropiezo."]}'::jsonb, '{"en":["Pick a handle height that reaches comfortably without stooping."],"es":["Elija una altura de mango comoda sin encorvarse."]}'::jsonb, '{"en":"Available in household shops","es":"Disponible en tiendas de hogar"}'::jsonb, 'low', true, 86, 'Seeded from VYVA mock catalog'),
  ('non-slip-shower-mat', 'mobility_aids', '{"en":"Non-slip shower mat with drainage holes","es":"Alfombrilla antideslizante de ducha con drenaje"}'::jsonb, '{"en":"Low cost","es":"Precio bajo"}'::jsonb, '{"en":"A textured mat to reduce slipping in the shower.","es":"Alfombrilla con textura para reducir resbalones en la ducha."}'::jsonb, '{"en":["Low cost","Bathroom safety","Easy first step"],"es":["Precio bajo","Seguridad en bano","Primer paso sencillo"]}'::jsonb, array['mobility', 'bathroom', 'shower', 'fall_prevention', 'home_safety', 'safety', 'budget', 'simple', 'accessibility']::text[], '{"en":["Good for a slippery shower floor","Helpful before bigger bathroom changes"],"es":["Buena para suelo de ducha resbaladizo","Util antes de cambios mayores en el bano"]}'::jsonb, '{"en":["Check suction regularly and replace it if it no longer grips."],"es":["Revise la succion con frecuencia y cambiela si ya no agarra."]}'::jsonb, '{"en":["Choose high-contrast color if vision is reduced."],"es":["Elija color de alto contraste si la vision esta reducida."]}'::jsonb, '{"en":"Easy to find in pharmacies and household shops","es":"Facil de encontrar en farmacias y tiendas de hogar"}'::jsonb, 'low', true, 85, 'Seeded from VYVA mock catalog'),
  ('grabber-reacher', 'mobility_aids', '{"en":"Lightweight grabber reacher","es":"Pinza extensible ligera"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"A reacher for picking up light items without bending.","es":"Pinza para coger objetos ligeros sin agacharse."}'::jsonb, '{"en":["Less bending","Lightweight","Useful around home"],"es":["Menos agacharse","Ligera","Util en casa"]}'::jsonb, array['mobility', 'reach', 'bending', 'less_bending', 'home_safety', 'accessibility', 'simple', 'low_lift', 'household']::text[], '{"en":["Good if bending or reaching is hard","Useful for dropped light objects"],"es":["Buena si cuesta agacharse o alcanzar","Util para objetos ligeros caidos"]}'::jsonb, '{"en":["Do not use it for hot, sharp, or heavy objects."],"es":["No la use para objetos calientes, afilados o pesados."]}'::jsonb, '{"en":["Choose a trigger that feels comfortable in the hand."],"es":["Elija un gatillo comodo para la mano."]}'::jsonb, '{"en":"Mobility shop or online item","es":"Articulo de tienda de movilidad u online"}'::jsonb, 'medium', true, 84, 'Seeded from VYVA mock catalog'),
  ('adjustable-folding-walking-stick', 'mobility_aids', '{"en":"Adjustable folding walking stick","es":"Baston plegable ajustable"}'::jsonb, '{"en":"Medium cost","es":"Precio medio"}'::jsonb, '{"en":"A portable walking stick with adjustable height.","es":"Baston portatil con altura ajustable."}'::jsonb, '{"en":["Adjustable height","Folds away","Portable support"],"es":["Altura ajustable","Se pliega","Apoyo portatil"]}'::jsonb, array['mobility', 'walking', 'support', 'fall_prevention', 'home_safety', 'accessibility', 'outdoor', 'simple', 'balance']::text[], '{"en":["Good if a light portable support is needed","Useful for outings"],"es":["Bueno si se necesita apoyo ligero y portatil","Util para salidas"]}'::jsonb, '{"en":["Correct height matters. Ask a professional if unsure about walking support."],"es":["La altura correcta importa. Consulte a un profesional si duda sobre el apoyo para caminar."]}'::jsonb, '{"en":["Look for a comfortable handle and non-slip ferrule."],"es":["Busque mango comodo y contera antideslizante."]}'::jsonb, '{"en":"Mobility shop or pharmacy item","es":"Articulo de tienda de movilidad o farmacia"}'::jsonb, 'medium', true, 83, 'Seeded from VYVA mock catalog'),
  ('raised-toilet-seat-arms', 'mobility_aids', '{"en":"Raised toilet seat with support arms","es":"Elevador de WC con brazos de apoyo"}'::jsonb, '{"en":"Higher cost","es":"Precio mas alto"}'::jsonb, '{"en":"A bathroom aid that can make sitting and standing easier.","es":"Ayuda de bano que puede facilitar sentarse y levantarse."}'::jsonb, '{"en":["Supports standing","Bathroom accessibility","Stable arms"],"es":["Apoya al levantarse","Accesibilidad en bano","Brazos estables"]}'::jsonb, array['mobility', 'bathroom', 'toilet', 'standing', 'home_safety', 'accessibility', 'safety', 'support']::text[], '{"en":["Good when standing from the toilet is hard","Useful after careful measuring"],"es":["Bueno si cuesta levantarse del WC","Util tras medir bien"]}'::jsonb, '{"en":["Measure carefully and consider advice from an occupational therapist or clinician."],"es":["Mida con cuidado y considere consejo de terapeuta ocupacional o clinico."]}'::jsonb, '{"en":["Check toilet shape, seat height, and cleaning access before choosing."],"es":["Compruebe forma del WC, altura del asiento y limpieza antes de elegir."]}'::jsonb, '{"en":"Best from a mobility supplier","es":"Mejor en proveedor de movilidad"}'::jsonb, 'high', true, 82, 'Seeded from VYVA mock catalog')
on conflict (product_id) do update set
  category = excluded.category,
  name = excluded.name,
  price_label = excluded.price_label,
  description = excluded.description,
  benefits = excluded.benefits,
  tags = excluded.tags,
  suitability = excluded.suitability,
  cautions = excluded.cautions,
  accessibility_notes = excluded.accessibility_notes,
  availability_label = excluded.availability_label,
  price_tier = excluded.price_tier,
  priority = excluded.priority,
  admin_notes = coalesce(concierge_shopping_products.admin_notes, excluded.admin_notes),
  updated_at = now();

insert into concierge_shopping_packages (package_id, label, description, need_text, category, priorities, constraints, cta_label, service_request, is_enabled, priority, admin_notes) values
  ('hydration_support', '{"en":"Hydration support","es":"Apoyo de hidratacion"}'::jsonb, '{"en":"Compare water, oral rehydration salts, and electrolyte drinks without starting checkout.","es":"Compare agua, sales de rehidratacion oral y bebidas con electrolitos sin iniciar compra."}'::jsonb, '{"en":"Hydration support: water, oral rehydration salts, or electrolyte drinks that are simple to use and easy to carry.","es":"Apoyo de hidratacion: agua, sales de rehidratacion oral o bebidas con electrolitos que sean sencillas y faciles de llevar."}'::jsonb, 'groceries', array['delivery', 'simplicity']::text[], '{"en":["no heavy lifting","check sugar or fluid restrictions"],"es":["sin cargar peso","revisar azucar o restriccion de liquidos"]}'::jsonb, '{"en":"Compare hydration","es":"Comparar hidratacion"}'::jsonb, false, true, 90, 'Seeded from VYVA support package defaults'),
  ('easy_meals', '{"en":"Easy meals","es":"Comidas faciles"}'::jsonb, '{"en":"Simple groceries and pantry options for low-effort meals.","es":"Compra sencilla y opciones de despensa para comer con poco esfuerzo."}'::jsonb, '{"en":"Easy meals after a health check: soft foods, pantry meals, and simple low-effort choices.","es":"Comidas faciles tras una revision de salud: alimentos blandos, comidas de despensa y opciones sencillas."}'::jsonb, 'groceries', array['simplicity', 'delivery']::text[], '{"en":["easy to open","simple preparation"],"es":["facil de abrir","preparacion sencilla"]}'::jsonb, '{"en":"Compare easy meals","es":"Comparar comidas"}'::jsonb, false, true, 80, 'Seeded from VYVA support package defaults'),
  ('pharmacy_basics', '{"en":"Pharmacy basics","es":"Basicos de farmacia"}'::jsonb, '{"en":"Basic supplies with a reminder to ask a pharmacist or doctor when unsure.","es":"Suministros basicos con recordatorio de consultar a farmacia o medico si hay dudas."}'::jsonb, '{"en":"Pharmacy basics for a health support kit: simple, clearly labelled items and no medication advice.","es":"Basicos de farmacia para un kit de apoyo: articulos sencillos, bien etiquetados y sin consejo de medicacion."}'::jsonb, 'pharmacy_basics', array['simplicity', 'safety']::text[], '{"en":["check with a pharmacist","do not change medicines"],"es":["consultar con farmacia","no cambiar medicinas"]}'::jsonb, '{"en":"Compare basics","es":"Comparar basicos"}'::jsonb, false, true, 70, 'Seeded from VYVA support package defaults'),
  ('home_support', '{"en":"Home support","es":"Apoyo en casa"}'::jsonb, '{"en":"Prepare a support request for help at home, with confirmation before anyone is contacted.","es":"Prepare una solicitud de apoyo en casa, con confirmacion antes de contactar a nadie."}'::jsonb, '{"en":"Home support after a health recommendation: someone to check in, help at home, or stay nearby.","es":"Apoyo en casa tras una recomendacion de salud: alguien que revise, ayude en casa o este cerca."}'::jsonb, 'safe_home', array['safety', 'accessibility']::text[], '{"en":["confirm before contacting anyone","no product checkout"],"es":["confirmar antes de contactar a nadie","sin compra de productos"]}'::jsonb, '{"en":"Prepare support","es":"Preparar apoyo"}'::jsonb, true, true, 60, 'Seeded from VYVA support package defaults')
on conflict (package_id) do update set
  label = excluded.label,
  description = excluded.description,
  need_text = excluded.need_text,
  category = excluded.category,
  priorities = excluded.priorities,
  constraints = excluded.constraints,
  cta_label = excluded.cta_label,
  service_request = excluded.service_request,
  priority = excluded.priority,
  admin_notes = coalesce(concierge_shopping_packages.admin_notes, excluded.admin_notes),
  updated_at = now();

delete from concierge_shopping_package_items where package_id = 'hydration_support';
insert into concierge_shopping_package_items (package_id, product_id, sort_order) values
  ('hydration_support', 'small-water-bottle-multipack', 0),
  ('hydration_support', 'low-sugar-electrolyte-drinks', 1),
  ('hydration_support', 'oral-rehydration-sachets', 2)
on conflict (package_id, product_id) do update set sort_order = excluded.sort_order;

delete from concierge_shopping_package_items where package_id = 'easy_meals';
insert into concierge_shopping_package_items (package_id, product_id, sort_order) values
  ('easy_meals', 'low-sodium-lentil-soup', 0),
  ('easy_meals', 'ready-cut-soft-fruit', 1),
  ('easy_meals', 'plain-protein-yogurt', 2),
  ('easy_meals', 'wholegrain-porridge-oats', 3)
on conflict (package_id, product_id) do update set sort_order = excluded.sort_order;

delete from concierge_shopping_package_items where package_id = 'pharmacy_basics';
insert into concierge_shopping_package_items (package_id, product_id, sort_order) values
  ('pharmacy_basics', 'large-print-pill-organizer', 0),
  ('pharmacy_basics', 'large-display-thermometer', 1),
  ('pharmacy_basics', 'oral-rehydration-sachets', 2),
  ('pharmacy_basics', 'fragrance-free-moisturizer', 3)
on conflict (package_id, product_id) do update set sort_order = excluded.sort_order;

delete from concierge_shopping_package_items where package_id = 'home_support';
insert into concierge_shopping_package_items (package_id, product_id, sort_order) values
  ('home_support', 'motion-night-lights', 0),
  ('home_support', 'non-slip-shower-mat', 1),
  ('home_support', 'grabber-reacher', 2),
  ('home_support', 'raised-toilet-seat-arms', 3)
on conflict (package_id, product_id) do update set sort_order = excluded.sort_order;

