const normalizeLanguage = (language: string | undefined) => (language ?? "en").split("-")[0].toLowerCase();

const FRENCH_QUESTIONS: Record<string, string> = {
  "What is bothering you?": "Qu’est-ce qui vous gêne ?",
  "Where is the main pain?": "Où se situe la douleur principale ?",
  "Is the pain sudden, severe, or with these warning signs?": "La douleur est-elle soudaine, intense ou accompagnée de l’un de ces signes d’alerte ?",
  "Is the chest feeling happening now or with warning signs?": "La gêne thoracique est-elle présente maintenant ou accompagnée de signes d’alerte ?",
  "How is your breathing right now?": "Comment respirez-vous en ce moment ?",
  "Do any fever warning signs apply?": "Présentez-vous l’un de ces signes d’alerte avec la fièvre ?",
  "Did you faint, nearly faint, or feel unsafe walking?": "Vous êtes-vous évanoui(e), avez-vous failli vous évanouir ou vous sentez-vous instable en marchant ?",
  "Which statement fits the weakness or tiredness right now?": "Quelle phrase décrit le mieux votre faiblesse ou votre fatigue actuelle ?",
  "Do stomach or bowel symptoms include these warning signs?": "Vos symptômes digestifs comprennent-ils l’un de ces signes d’alerte ?",
  "What urine problem is happening?": "Quel problème urinaire avez-vous ?",
  "Did the fall include any safety warning signs?": "La chute s’accompagne-t-elle de l’un de ces signes d’alerte ?",
  "Does the skin or wound have any warning signs?": "La peau ou la plaie présente-t-elle l’un de ces signes d’alerte ?",
  "Is this confusion sudden, worse, or unsafe?": "Cette confusion est-elle soudaine, plus importante ou dangereuse ?",
  "Do any of these warning signs apply?": "Présentez-vous l’un de ces signes d’alerte ?",
  "Does the head or neck pain include any warning signs?": "La douleur à la tête ou au cou s’accompagne-t-elle de signes d’alerte ?",
  "Does the back pain include any warning signs?": "Le mal de dos s’accompagne-t-il de signes d’alerte ?",
  "Does the belly or side pain include any warning signs?": "La douleur au ventre ou sur le côté s’accompagne-t-elle de signes d’alerte ?",
  "Does the arm, leg, or joint pain include any warning signs?": "La douleur au bras, à la jambe ou à l’articulation s’accompagne-t-elle de signes d’alerte ?",
  "When did the pain start?": "Quand la douleur a-t-elle commencé ?",
  "When did the chest feeling start?": "Quand la gêne thoracique a-t-elle commencé ?",
  "When did the breathing change start?": "Quand ce changement de respiration a-t-il commencé ?",
  "When did the fever start?": "Quand la fièvre a-t-elle commencé ?",
  "When did the dizziness start?": "Quand les vertiges ont-ils commencé ?",
  "When did the tiredness or weakness start?": "Quand la fatigue ou la faiblesse a-t-elle commencé ?",
  "Which timing or pattern fits the stomach or bowel problem?": "Quelle durée ou évolution décrit le mieux votre problème digestif ?",
  "When did the urine problem start?": "Quand le problème urinaire a-t-il commencé ?",
  "When did the fall or injury happen?": "Quand la chute ou la blessure s’est-elle produite ?",
  "When did the skin or wound change start?": "Quand ce changement de la peau ou de la plaie a-t-il commencé ?",
  "When did this change start?": "Quand ce changement a-t-il commencé ?",
  "When did this start?": "Quand cela a-t-il commencé ?",
  "Which chest pattern fits best?": "Quelle description correspond le mieux à votre gêne thoracique ?",
  "Does breathing come with any of these problems?": "La gêne respiratoire s’accompagne-t-elle de l’un de ces problèmes ?",
  "Do you notice where the fever may be coming from?": "Avez-vous remarqué d’où pourrait venir la fièvre ?",
  "Does dizziness come with any of these problems?": "Les vertiges s’accompagnent-ils de l’un de ces problèmes ?",
  "What else is happening with the tiredness or weakness?": "Qu’avez-vous remarqué d’autre avec la fatigue ou la faiblesse ?",
  "Which stomach or bowel problem is the main one?": "Quel est votre principal problème digestif ?",
  "What comes with the urine problem?": "Quels autres signes accompagnent le problème urinaire ?",
  "Can you stand, walk, and use the injured part?": "Pouvez-vous vous lever, marcher et utiliser la partie blessée ?",
  "Does it look like painful blisters or shingles?": "Voyez-vous des cloques douloureuses évoquant un zona ?",
  "Do any safety, medicine, or mood concerns apply?": "Avez-vous un problème de sécurité, de médicament ou d’humeur ?",
  "Where is the main problem?": "Où se situe le problème principal ?",
  "Which best describes the pain now?": "Quelle phrase décrit le mieux la douleur maintenant ?",
  "Has anything else happened with the chest feeling?": "Avez-vous remarqué autre chose avec la gêne thoracique ?",
  "Which best describes the breathing change now?": "Quelle phrase décrit le mieux votre respiration maintenant ?",
  "Which best describes the fever now?": "Quelle phrase décrit le mieux la fièvre maintenant ?",
  "How is the dizziness behaving now?": "Comment évoluent les vertiges maintenant ?",
  "Which best describes the tiredness or weakness now?": "Quelle phrase décrit le mieux votre fatigue ou votre faiblesse maintenant ?",
  "Do you have whole-body signs with the stomach problem?": "Avez-vous des signes généraux avec le problème digestif ?",
  "Which best fits the urine problem?": "Quelle phrase décrit le mieux le problème urinaire ?",
  "How is pain or movement now?": "Comment sont la douleur et les mouvements maintenant ?",
  "Is the skin or wound spreading or getting worse?": "L’atteinte de la peau ou la plaie s’étend-elle ou s’aggrave-t-elle ?",
  "How is this confusion or memory change behaving?": "Comment évolue cette confusion ou ce trouble de mémoire ?",
  "Which best describes what is happening now?": "Quelle phrase décrit le mieux ce qui se passe maintenant ?",
  "Does the anxiety feeling include any urgent warning signs?": "Cette sensation d’anxiété s’accompagne-t-elle de signes d’alerte urgents ?",
  "What else is happening with the anxiety feeling?": "Qu’avez-vous remarqué d’autre avec cette sensation d’anxiété ?",
  "Which best describes the anxiety or panic feeling now?": "Quelle phrase décrit le mieux l’anxiété ou la panique maintenant ?",
  "Could this medicine change be causing any urgent warning signs?": "Ce changement de médicament pourrait-il provoquer un signe d’alerte urgent ?",
  "What changed with the medicine?": "Qu’est-ce qui a changé avec le médicament ?",
  "How is the medicine-related feeling changing?": "Comment évolue la sensation liée au médicament ?",
  "Has anything made it better or worse?": "Quelque chose l’a-t-il améliorée ou aggravée ?",
  "Does the back pain have any of these signs?": "Le mal de dos s’accompagne-t-il de l’un de ces signes ?",
  "Can you use the sore limb or joint safely?": "Pouvez-vous utiliser le membre ou l’articulation douloureuse sans danger ?",
  "Does this look right?": "Est-ce correct ?",
  "How strong is it?": "Quelle est son intensité ?",
  "Here is what to do next.": "Voici ce que vous pouvez faire maintenant.",
};

const FRENCH_ANSWER_LABELS: Record<string, string> = {
  "Pain": "Douleur",
  "Chest discomfort": "Gêne thoracique",
  "Breathing": "Respiration",
  "Fever": "Fièvre",
  "Dizzy or faint": "Vertiges ou malaise",
  "Dizzy": "Vertiges",
  "Very tired or weak": "Très fatigué(e) ou faible",
  "Very tired": "Très fatigué(e)",
  "Stomach or bowel": "Estomac ou intestins",
  "Urine problem": "Problème urinaire",
  "Fall or injury": "Chute ou blessure",
  "Skin or wound": "Peau ou plaie",
  "Confusion or memory": "Confusion ou mémoire",
  "Confusion": "Confusion",
  "Something else": "Autre chose",
  "Anxiety or panic": "Anxiété ou panique",
  "Medicine change": "Changement de médicament",
  "Head or neck": "Tête ou cou",
  "Back": "Dos",
  "Back pain": "Mal de dos",
  "Belly or side": "Ventre ou côté",
  "Arm, leg, or joint": "Bras, jambe ou articulation",
  "Arm, leg, joint, or other": "Bras, jambe, articulation ou autre",
  "Somewhere else": "Ailleurs",
  "Sudden worst pain": "Douleur soudaine, la pire ressentie",
  "Sudden or worst-ever pain": "Douleur soudaine ou la pire ressentie",
  "Sudden or extremely severe": "Soudaine ou extrêmement intense",
  "Sudden or severe belly pain": "Douleur abdominale soudaine ou intense",
  "Sudden or severe": "Soudaine ou intense",
  "Weakness, speech, vision, or confusion": "Faiblesse, trouble de la parole, de la vue ou confusion",
  "Weakness, speech, or vision change": "Faiblesse ou trouble de la parole ou de la vue",
  "Weakness, speech or vision trouble, seizure, or fainted": "Faiblesse, trouble de la parole ou de la vue, convulsion ou évanouissement",
  "Face/arm weakness, speech or vision trouble, seizure, or fainting": "Faiblesse du visage ou du bras, trouble de la parole ou de la vue, convulsion ou évanouissement",
  "Weakness, face droop, or speech trouble": "Faiblesse, visage affaissé ou trouble de la parole",
  "Weak on one side": "Faiblesse d’un côté",
  "Weakness or speech trouble": "Faiblesse ou trouble de la parole",
  "Back pain with bladder, bowel, or leg weakness": "Mal de dos avec trouble urinaire, intestinal ou faiblesse des jambes",
  "Bladder, bowel, numbness, or leg weakness": "Trouble urinaire ou intestinal, engourdissement ou faiblesse des jambes",
  "Bladder/bowel problem or leg weakness": "Trouble urinaire ou intestinal, ou faiblesse des jambes",
  "No, none of these": "Non, aucun de ces signes",
  "No, anxiety feeling without those warning signs": "Non, de l’anxiété sans ces signes d’alerte",
  "No, light-headed but steady": "Non, un peu étourdi(e) mais stable",
  "No, mild feverish feeling only": "Non, seulement une légère sensation de fièvre",
  "No, mild and not sudden": "Non, c’est léger et non soudain",
  "No, just tired or weak": "Non, seulement fatigué(e) ou faible",
  "No, only a small bruise or soreness": "Non, seulement un petit bleu ou une douleur légère",
  "No, small and not spreading": "Non, c’est petit et ne s’étend pas",
  "No clear source": "Aucune cause évidente",
  "No painful blister pattern": "Pas de cloques douloureuses typiques",
  "No safety, medicine, or mood concern": "Aucun problème de sécurité, de médicament ou d’humeur",
  "Tight, heavy, crushing, or spreading": "Serrement, lourdeur, écrasement ou douleur qui s’étend",
  "Sweaty, sick, faint, or hard to breathe": "Sueurs, nausée, malaise ou difficulté à respirer",
  "It happened today but stopped": "C’est arrivé aujourd’hui puis s’est arrêté",
  "Mild sore spot or not sure": "Point légèrement douloureux ou doute",
  "Gasping or cannot speak": "Je halète ou ne peux pas parler",
  "Blue, grey, pale, or confused": "Bleu(e), gris(e), pâle ou confus(e)",
  "Worse than usual, but I can speak": "Pire que d’habitude, mais je peux parler",
  "Mild or only with activity": "Léger ou seulement à l’effort",
  "Confused, very sleepy, fast breathing, pale, or little urine": "Confusion, forte somnolence, respiration rapide, pâleur ou peu d’urines",
  "Cancer treatment or weak immune system": "Traitement contre le cancer ou immunité faible",
  "38 C or higher, or shaking chills": "38 °C ou plus, ou frissons intenses",
  "Fainted and not fully normal": "Évanouissement sans retour complet à la normale",
  "Fainted with chest, breathing, heartbeat, seizure, or injury": "Évanouissement avec problème thoracique, respiratoire, cardiaque, convulsion ou blessure",
  "Very dizzy now or might fall": "Très étourdi(e) maintenant ou risque de chute",
  "I have sudden weakness, speech, or vision trouble": "J’ai une faiblesse soudaine ou un trouble de la parole ou de la vue",
  "I cannot stand or walk safely": "Je ne peux pas me tenir debout ou marcher sans danger",
  "I feel weak with chest pain or hard breathing": "Je me sens faible avec une douleur thoracique ou une difficulté à respirer",
  "I am alert and can stand safely": "Je suis alerte et peux me tenir debout sans danger",
  "Severe belly pain": "Douleur abdominale intense",
  "Vomiting blood, or black/bloody stool": "Vomissements de sang ou selles noires/sanglantes",
  "Vomiting blood or black/bloody stool": "Vomissements de sang ou selles noires/sanglantes",
  "Cannot keep fluids down or pass stool/gas/urine": "Impossible de garder les liquides ou d’évacuer selles, gaz ou urine",
  "Cannot pass urine": "Impossible d’uriner",
  "Burning with fever, side pain, vomiting, or confusion": "Brûlures avec fièvre, douleur sur le côté, vomissements ou confusion",
  "Blood in urine or clots": "Sang ou caillots dans les urines",
  "Burning, urgency, cloudy, or smelly only": "Seulement brûlures, envies pressantes, urine trouble ou malodorante",
  "Hit head, confused, vomiting, or bad headache": "Choc à la tête, confusion, vomissements ou fort mal de tête",
  "Knocked out, stairs, height, or high speed": "Perte de connaissance, escaliers, hauteur ou vitesse importante",
  "I am alone and no one can check on me": "Je suis seul(e) et personne ne peut veiller sur moi",
  "Face, lip, tongue, or throat swelling": "Gonflement du visage, des lèvres, de la langue ou de la gorge",
  "Hot red skin with fever, confusion, fast breathing, or dizziness": "Peau rouge et chaude avec fièvre, confusion, respiration rapide ou vertiges",
  "Open wound, drainage, surgery wound, or spreading redness": "Plaie ouverte, écoulement, plaie opératoire ou rougeur qui s’étend",
  "Suddenly confused or hard to wake": "Confusion soudaine ou difficulté à se réveiller",
  "Fever, urine change, new weakness, or low urine": "Fièvre, changement urinaire, nouvelle faiblesse ou peu d’urines",
  "Chest pain, breathing trouble, or pale/blue skin": "Douleur thoracique, difficulté à respirer ou peau pâle/bleutée",
  "Confusion, hard to wake, heavy bleeding, severe pain, or swelling": "Confusion, difficulté à se réveiller, saignement important, douleur intense ou gonflement",
  "Very confused, hard to wake, severe pain, bleeding, or allergy swelling": "Forte confusion, difficulté à se réveiller, douleur intense, saignement ou gonflement allergique",
  "Fever, stiff neck, confusion, or injury": "Fièvre, raideur de la nuque, confusion ou blessure",
  "After a fall, or unable to stand": "Après une chute ou impossibilité de se tenir debout",
  "Fainted, very pale, or cannot keep fluids down": "Évanouissement, forte pâleur ou impossibilité de garder les liquides",
  "Cannot use it or it looks deformed": "Impossible de l’utiliser ou aspect déformé",
  "Cold, blue, numb, or very swollen": "Froid, bleu, engourdi ou très gonflé",
  "One leg suddenly swollen, red, or hot": "Une jambe soudainement gonflée, rouge ou chaude",
  "Started today": "Aujourd’hui",
  "Happened today": "Aujourd’hui",
  "New today": "Nouveau aujourd’hui",
  "2-3 days": "2 à 3 jours",
  "Few days": "Quelques jours",
  "Few days ago": "Il y a quelques jours",
  "Past few days": "Ces derniers jours",
  "A week or more": "Une semaine ou plus",
  "Weeks or months": "Des semaines ou des mois",
  "Longer than a few days": "Plus de quelques jours",
  "Comes and goes": "Cela va et vient",
  "Keeps returning": "Cela revient régulièrement",
  "I am not sure": "Je ne suis pas sûr(e)",
  "I am not sure how it is changing": "Je ne sais pas comment cela évolue",
  "I am not sure how long it has been changing": "Je ne sais pas depuis combien de temps cela évolue",
  "It is getting worse today": "Cela s’aggrave aujourd’hui",
  "Vomiting or diarrhea has lasted over 24 hours": "Les vomissements ou la diarrhée durent depuis plus de 24 heures",
  "I am constipated but passing gas": "Je suis constipé(e), mais j’évacue des gaz",
  "It is mild and improving": "C’est léger et cela s’améliore",
  "At rest, woke me, or over 5 minutes": "Au repos, m’a réveillé(e) ou dure plus de 5 minutes",
  "With walking, stairs, or activity": "En marchant, dans les escaliers ou à l’effort",
  "Only when I press, twist, cough, or lift": "Seulement en appuyant, tournant, toussant ou soulevant",
  "Chest tightness, heaviness, or spreading pain": "Oppression, lourdeur ou douleur thoracique qui s’étend",
  "Coughing blood or one swollen calf": "Toux avec du sang ou un mollet gonflé",
  "Fast heartbeat, fainting, or severe weakness": "Battements rapides, évanouissement ou faiblesse intense",
  "Cough, chest pain, or shortness of breath": "Toux, douleur thoracique ou essoufflement",
  "Burning pee, side pain, vomiting, or confusion": "Brûlures urinaires, douleur sur le côté, vomissements ou confusion",
  "Red painful skin, wound, or surgery cut": "Peau rouge et douloureuse, plaie ou incision chirurgicale",
  "Face, arm, speech, or vision change": "Changement du visage, du bras, de la parole ou de la vue",
  "Chest pain, hard breathing, or fast heartbeat": "Douleur thoracique, difficulté à respirer ou rythme cardiaque rapide",
  "Low sugar symptoms or diabetes medicine": "Signes d’hypoglycémie ou médicament pour le diabète",
  "Fever, chills, cough, wound, or urine pain": "Fièvre, frissons, toux, plaie ou douleur urinaire",
  "Vomiting, diarrhea, not drinking, or hardly peeing": "Vomissements, diarrhée, peu de boisson ou peu d’urines",
  "Diabetes medicine or possible sugar problem": "Médicament pour le diabète ou possible problème de glycémie",
  "Mostly vomiting": "Surtout des vomissements",
  "Mostly diarrhea": "Surtout de la diarrhée",
  "Mostly constipation": "Surtout de la constipation",
  "Belly pain, bloating, or nausea": "Douleur au ventre, ballonnements ou nausées",
  "Fever or shaking chills": "Fièvre ou frissons intenses",
  "Back or side pain": "Douleur dans le dos ou sur le côté",
  "New confusion or very weak": "Nouvelle confusion ou forte faiblesse",
  "No, urine symptoms only": "Non, seulement des symptômes urinaires",
  "No, I cannot stand, walk, or use it": "Non, je ne peux pas me tenir debout, marcher ou l’utiliser",
  "Hip, back, or severe pain": "Douleur à la hanche, au dos ou douleur intense",
  "Yes, but it is painful": "Oui, mais c’est douloureux",
  "Yes, normal movement and mild soreness": "Oui, mouvements normaux et douleur légère",
  "Painful blisters near eye/nose or vision change": "Cloques douloureuses près de l’œil/du nez ou trouble de la vue",
  "Painful blisters and weak immune system": "Cloques douloureuses et immunité faible",
  "Painful blisters started within 3 days": "Cloques douloureuses apparues depuis moins de 3 jours",
  "Stove, wandering, fall, or medicine safety problem": "Risque avec la cuisinière, errance, chute ou médicament",
  "New medicine or dose change": "Nouveau médicament ou changement de dose",
  "Very low mood or self-harm talk": "Humeur très basse ou propos d’automutilation",
  "Chest or breathing": "Poitrine ou respiration",
  "Head, weakness, dizziness, confusion, or fall": "Tête, faiblesse, vertiges, confusion ou chute",
  "Fever, urine, stomach, skin, or wound": "Fièvre, urines, estomac, peau ou plaie",
  "Fever, stomach, urine, skin, or wound symptoms": "Fièvre ou symptômes digestifs, urinaires, cutanés ou de plaie",
  "Other or not sure": "Autre ou incertain",
  "Pain is easing": "La douleur diminue",
  "Pain is the same": "La douleur ne change pas",
  "Pain is worse": "La douleur s’aggrave",
  "New symptoms appeared": "De nouveaux symptômes sont apparus",
  "Sudden shortness of breath": "Essoufflement soudain",
  "Coughing blood": "Toux avec du sang",
  "One calf painful, red, or swollen": "Un mollet douloureux, rouge ou gonflé",
  "It is new or suddenly worse today": "C’est nouveau ou soudainement pire aujourd’hui",
  "It comes with fever, cough, or more phlegm": "Avec fièvre, toux ou davantage de glaires",
  "It is worse lying flat, or ankles are swollen": "C’est pire en position allongée ou les chevilles sont gonflées",
  "It is worse lying flat, or my ankles are swollen": "C’est pire en position allongée ou mes chevilles sont gonflées",
  "It is mild, usual for me, and improving": "C’est léger, habituel pour moi et cela s’améliore",
  "I am peeing less, very weak, dizzy, or cannot drink": "J’urine moins, je suis très faible ou étourdi(e), ou je ne peux pas boire",
  "It has been 38 C or higher for more than 24 hours": "La température est d’au moins 38 °C depuis plus de 24 heures",
  "It is mild, improving, and I am drinking and peeing": "C’est léger, cela s’améliore et je bois et urine normalement",
  "Happens when standing up": "Cela arrive en me levant",
  "Happens with head movement": "Cela arrive en bougeant la tête",
  "All the time or getting worse": "En permanence ou en aggravation",
  "One brief episode, gone now": "Un épisode bref, maintenant terminé",
  "I have more energy": "J’ai plus d’énergie",
  "It feels about the same": "C’est à peu près pareil",
  "I am feeling weaker": "Je me sens plus faible",
  "Very weak, dizzy, confused, dry mouth, or hardly peeing": "Forte faiblesse, vertiges, confusion, bouche sèche ou très peu d’urines",
  "Fever or severe pain": "Fièvre ou douleur intense",
  "Diabetes and vomiting or high sugar": "Diabète avec vomissements ou glycémie élevée",
  "Burning or pain when peeing": "Brûlure ou douleur en urinant",
  "Needing to pee often or urgently": "Besoin d’uriner souvent ou en urgence",
  "Cloudy or smelly only, no pain or fever": "Urine seulement trouble ou malodorante, sans douleur ni fièvre",
  "I have a catheter": "J’ai une sonde urinaire",
  "Pain is worse or swelling fast": "La douleur s’aggrave ou le gonflement augmente rapidement",
  "Can move it, but painful": "Je peux bouger, mais c’est douloureux",
  "Small bruise or scrape, improving": "Petit bleu ou égratignure en amélioration",
  "Spreading quickly": "Cela s’étend rapidement",
  "Pus, bad smell, or increasing pain": "Pus, mauvaise odeur ou douleur croissante",
  "Small, same area, improving": "Petite zone stable, en amélioration",
  "It started today or suddenly": "Cela a commencé aujourd’hui ou soudainement",
  "It has been changing over a few days": "Cela évolue depuis quelques jours",
  "It has been gradual over weeks or months": "Cela évolue progressivement depuis des semaines ou des mois",
  "It started suddenly or is worse today": "Cela a commencé soudainement ou s’aggrave aujourd’hui",
  "It started suddenly, is worse today, or feels unusual": "Cela a commencé soudainement, s’aggrave aujourd’hui ou paraît inhabituel",
  "It started after medicine, surgery, hospital, or a fall": "Cela a commencé après un médicament, une opération, une hospitalisation ou une chute",
  "It started after medicine, caffeine, alcohol/drugs, hospital, or a fall": "Cela a commencé après un médicament, de la caféine, de l’alcool/des drogues, une hospitalisation ou une chute",
  "It is ongoing and not improving": "Cela persiste sans s’améliorer",
  "It is ongoing and not settling": "Cela persiste sans se calmer",
  "It is mild, brief, and improving": "C’est léger, bref et cela s’améliore",
  "It is mild, brief, and settling": "C’est léger, bref et cela se calme",
  "Chest pain, hard breathing, or blue/grey/pale skin": "Douleur thoracique, respiration difficile ou peau bleue, grise ou pâle",
  "Chest tightness, breathing trouble, or racing heart": "Oppression thoracique, difficulté à respirer ou cœur qui s’emballe",
  "Dizzy, faint, confused, weak, or after a fall": "Vertiges, malaise, confusion, faiblesse ou après une chute",
  "Anxiety feeling without those body warning signs": "Sensation d’anxiété sans ces signes physiques d’alerte",
  "Started soon after a dose or medicine change": "Peu après une dose ou un changement de médicament",
  "It is getting worse": "Cela s’aggrave",
  "It is settling": "Cela se calme",
  "Face or throat swelling": "Gonflement du visage ou de la gorge",
  "Very sleepy or breathing slowly": "Très somnolent(e) ou respiration lente",
  "Unusual bleeding or black stool": "Saignement inhabituel ou selles noires",
  "I may have taken extra": "J’ai peut-être pris une dose en trop",
  "I missed an important dose": "J’ai oublié une dose importante",
  "New medicine or new side effect": "Nouveau médicament ou nouvel effet indésirable",
  "Mild question about medicine": "Question légère concernant un médicament",
  "Rest or medicine helped": "Le repos ou un médicament a aidé",
  "Activity, light, or noise made it worse": "L’activité, la lumière ou le bruit l’a aggravée",
  "An injury or other symptoms affected it": "Une blessure ou d’autres symptômes l’ont influencée",
  "Nothing clearly changed it": "Rien ne l’a clairement modifiée",
  "Fever, fall, cancer history, or night pain": "Fièvre, chute, antécédent de cancer ou douleur nocturne",
  "Mild strain and improving": "Légère élongation en amélioration",
  "Painful but usable": "Douloureux mais utilisable",
  "Mild and improving": "Léger et en amélioration",
  "Call doctor": "Appeler un médecin",
  "Yes, show my guidance": "Oui, afficher mes conseils",
  "Edit": "Modifier",
  "Make report": "Créer un rapport",
  "Keep asking": "Continuer les questions",
  "Low sugar signs": "Signes d’hypoglycémie",
  "High sugar and sick": "Glycémie élevée avec malaise",
  "Low oxygen": "Oxygène bas",
  "Swelling or weight gain": "Gonflement ou prise de poids",
  "Irregular heartbeat": "Rythme cardiaque irrégulier",
  "Very high blood pressure": "Tension artérielle très élevée",
  "Hit my head": "Choc à la tête",
  "Unusual bleeding": "Saignement inhabituel",
  "Fever with low immunity": "Fièvre avec immunité faible",
  "New confusion": "Nouvelle confusion",
  "Low urine or swelling": "Peu d’urines ou gonflement",
  "Fall with hip or back pain": "Chute avec douleur à la hanche ou au dos",
  "Trouble swallowing": "Difficulté à avaler",
  "Fever after surgery": "Fièvre après une opération",
  "Calf swelling": "Mollet gonflé",
  "Urine change or confusion": "Changement urinaire ou confusion",
  "Confusion or bleeding": "Confusion ou saignement",
  "Very sleepy or unsteady": "Très somnolent(e) ou instable",
  "Slow breathing": "Respiration lente",
  "Dehydration signs": "Signes de déshydratation",
  "Chest pain": "Douleur thoracique",
  "Confused or blue lips": "Confusion ou lèvres bleutées",
  "Fainted": "Évanouissement",
};

export function localizeTriageQuestion(language: string | undefined, value: string): string {
  if (normalizeLanguage(language) !== "fr") return value;
  return FRENCH_QUESTIONS[value.trim()] ?? value;
}

export function localizeTriageAnswerLabel(language: string | undefined, value: string): string {
  if (normalizeLanguage(language) !== "fr") return value;
  return FRENCH_ANSWER_LABELS[value.trim()] ?? value;
}
