
INSERT INTO curious_minds_hooks
  (fact_prompt, fact_answer, category, language, source, is_active)
VALUES
('¿Por qué crees que los girasoles jóvenes se van girando durante el día?', 'Cuando son jóvenes, los girasoles orientan sus flores siguiendo el movimiento del sol de este a oeste.', 'nature', 'es', 'ai_generated', false),
('¿Por qué crees que un pulpo necesita tres corazones?', 'Dos corazones bombean sangre a las branquias y el tercero la envía al resto del cuerpo.', 'animals', 'es', 'ai_generated', false),
('¿Cuántos olores diferentes crees que puede distinguir la nariz humana?', 'El olfato humano es mucho más preciso de lo que solemos imaginar y reconoce una enorme variedad de aromas.', 'body', 'es', 'ai_generated', false),
('¿Por qué crees que los arcoíris aparecen en dirección opuesta al sol?', 'Para ver un arcoíris, el sol debe estar a tu espalda mientras la lluvia cae delante de ti.', 'weather', 'es', 'ai_generated', false),
('¿Por qué crees que la miel puede conservarse durante tanto tiempo?', 'Gracias a su composición natural, la miel se mantiene en buen estado durante muchísimo tiempo si se almacena correctamente.', 'food', 'es', 'ai_generated', false),
('¿Qué número crees que no usaban los romanos en su sistema de numeración?', 'El sistema de numeración romano funcionaba sin necesidad del número cero tal como lo conocemos hoy.', 'history', 'es', 'ai_generated', false),
('¿Qué objeto cotidiano dirías que ya existía hace más de 3.000 años?', 'Las primeras versiones de las tijeras aparecieron en la antigüedad y han evolucionado muy poco en su función básica.', 'everyday_objects', 'es', 'ai_generated', false),
('¿Cuánto crees que tarda la luz del Sol en llegar hasta la Tierra?', 'Aunque viaja a una velocidad enorme, la luz solar necesita aproximadamente 8 minutos y 20 segundos para alcanzarnos.', 'science', 'es', 'ai_generated', false),
('¿Por qué crees que algunas semillas pueden esperar años antes de germinar?', 'Ciertas semillas permanecen inactivas durante mucho tiempo hasta que encuentran las condiciones adecuadas para crecer.', 'nature', 'es', 'ai_generated', false),
('¿Cómo crees que se reconocen los pingüinos entre miles de compañeros?', 'En colonias con miles de individuos, los pingüinos identifican a su pareja o a sus crías mediante sonidos únicos.', 'animals', 'es', 'ai_generated', false),
('¿Por qué crees que los flamencos no nacen ya con las plumas rosadas?', 'Su característico color rosado aparece con el tiempo gracias a los pigmentos presentes en su alimentación.', 'animals', 'es', 'ai_generated', false),
('¿Cuánto crees que puede pesar una nube aunque parezca tan ligera?', 'Aunque parecen ligeras, las nubes contienen enormes cantidades de diminutas gotas de agua.', 'weather', 'es', 'ai_generated', false),
('¿Cómo crees que una abeja puede decirle a otras dónde encontrar flores?', 'Las abejas realizan movimientos específicos para indicar a otras dónde encontrar flores.', 'animals', 'es', 'ai_generated', false),
('¿Dónde crees que crecen más rápido las uñas: en las manos o en los pies?', 'Las uñas de las manos suelen renovarse varias veces más rápido que las de los pies.', 'body', 'es', 'ai_generated', false),
('¿Cómo crees que se tomaba el chocolate antes de convertirse en tableta?', 'Durante siglos se tomó como una bebida, a menudo mezclada con especias.', 'food', 'es', 'ai_generated', false),
('¿Qué tipo de reloj crees que usaba la mayoría de la gente antes del reloj de pulsera?', 'Antes, la mayoría de las personas utilizaban relojes de bolsillo. Los relojes de pulsera se popularizaron hace poco más de un siglo.', 'history', 'es', 'ai_generated', false),
('¿Cuántas palabras crees que puede escribir un lápiz antes de gastarse?', 'La cantidad de grafito de un lápiz permite trazar una línea sorprendentemente larga y escribir decenas de miles de palabras.', 'everyday_objects', 'es', 'ai_generated', false),
('¿Qué fruta común crees que los botánicos clasifican como una baya?', 'Según la clasificación botánica, los plátanos pertenecen al grupo de las bayas.', 'food', 'es', 'ai_generated', false),
('¿Qué crees que pasaría si Saturno pudiera colocarse en una piscina gigantesca de agua?', 'Saturno flotaría, porque su densidad media es menor que la del agua, algo único entre los planetas del sistema solar.', 'science', 'es', 'ai_generated', false),
('¿Cómo crees que algunos árboles pueden compartir señales bajo tierra?', 'A través de redes de hongos y raíces pueden intercambiar nutrientes y señales sencillas con su entorno.', 'nature', 'es', 'ai_generated', false),
('¿Cómo crees que algunos caballitos de mar refuerzan el vínculo con su pareja cada día?', 'Algunas especies realizan pequeños rituales diarios para reforzar el vínculo con su pareja.', 'animals', 'es', 'ai_generated', false),
('¿Qué forma crees que tienen realmente las gotas de lluvia cuando caen?', 'Las gotas pequeñas son casi esféricas y las grandes se parecen más a un panecillo aplastado.', 'weather', 'es', 'ai_generated', false),
('¿Para qué crees que sirven las pequeñas papilas de la lengua?', 'Estas pequeñas estructuras ayudan a identificar distintos sabores en los alimentos.', 'body', 'es', 'ai_generated', false),
('¿Cuánto crees que puede crecer el bambú en un solo día?', 'Algunas especies de bambú están entre las plantas de crecimiento más rápido del mundo y pueden crecer más de medio metro en un solo día.', 'nature', 'es', 'ai_generated', false),
('¿De qué colores crees que eran comunes las zanahorias antes de que se popularizara la naranja?', 'Antiguamente eran comunes las variedades moradas, blancas y amarillas.', 'food', 'es', 'ai_generated', false),
('¿Cómo crees que se sujetaban las primeras gafas antes de tener patillas?', 'Se sujetaban con la mano o se apoyaban sobre la nariz de formas muy diferentes a las actuales.', 'history', 'es', 'ai_generated', false),
('¿Por qué crees que una cremallera puede abrir y cerrar con tanta facilidad?', 'Sus dientes, perfectamente alineados, permiten unir y separar tejidos de forma rápida y fiable.', 'everyday_objects', 'es', 'ai_generated', false),
('¿Qué crees que ocurre con el aire alrededor de un relámpago?', 'Durante una descarga, el aire se calienta muchísimo por un instante, incluso más que la superficie del Sol.', 'science', 'es', 'ai_generated', false),
('¿Cuántas bellotas crees que puede producir un roble maduro a lo largo de su vida?', 'Un solo árbol maduro puede generar miles de bellotas durante décadas.', 'nature', 'es', 'ai_generated', false),
('¿Cómo crees que algunos delfines se reconocen dentro de su grupo?', 'Cada delfín desarrolla sonidos distintivos, parecidos a una firma, que ayudan a identificarlo dentro del grupo.', 'animals', 'es', 'ai_generated', false),
('¿Con qué parte del cuerpo crees que las mariposas prueban los alimentos?', 'Sus patas tienen receptores que les ayudan a identificar plantas adecuadas para alimentarse o poner huevos.', 'animals', 'es', 'ai_generated', false),
('¿Dónde crees que viaja más rápido el sonido: en el aire o en el agua?', 'El sonido viaja más rápido en el agua porque sus moléculas están más juntas, lo que facilita la transmisión de las vibraciones.', 'science', 'es', 'ai_generated', false),
('¿Por qué crees que algunas flores cambian de color con el tiempo?', 'Este cambio puede ayudar a los insectos a identificar qué flores tienen más néctar.', 'nature', 'es', 'ai_generated', false),
('¿Por qué crees que a veces se nos pega un bostezo al ver bostezar a otro?', 'Se ha observado un efecto parecido en varias especies, incluidos perros y chimpancés.', 'body', 'es', 'ai_generated', false),
('¿Por qué crees que explotan las palomitas de maíz al calentarse?', 'Cada grano contiene agua en su interior. Al calentarse, el agua se convierte en vapor y hace que el grano reviente.', 'food', 'es', 'ai_generated', false),
('¿Por qué crees que algunos mapas antiguos incluían dibujos de seres fantásticos?', 'Al representar zonas desconocidas, algunos cartógrafos añadían dibujos de seres fantásticos.', 'history', 'es', 'ai_generated', false),
('¿Qué objeto pequeño de oficina crees que apenas ha cambiado en más de cien años?', 'El clip de papel tiene un diseño sencillo y eficaz, por eso sigue utilizándose de forma muy parecida hoy en día.', 'everyday_objects', 'es', 'ai_generated', false),
('¿Por qué crees que cada copo de nieve puede tener una estructura distinta?', 'Aunque comparten patrones similares, cada copo se forma con pequeñas variaciones de temperatura y humedad que le dan una estructura propia.', 'weather', 'es', 'ai_generated', false),
('¿Qué crees que puede aparecer al mismo tiempo en un limonero: flores, frutos o ambas cosas?', 'Es habitual ver en un mismo árbol limones maduros junto a nuevas flores.', 'nature', 'es', 'ai_generated', false),
('¿Qué crees que pueden recordar los cuervos de las personas durante años?', 'Estos inteligentes animales son capaces de reconocer y recordar rostros humanos durante años.', 'animals', 'es', 'ai_generated', false),
('¿Cómo crees que los castores pueden cambiar el curso de pequeños arroyos?', 'Al construir presas con ramas y troncos, crean estanques que transforman su entorno.', 'animals', 'es', 'ai_generated', false),
('¿Por qué crees que algunas naranjas maduras pueden verse algo verdosas?', 'En climas cálidos, algunas naranjas maduras conservan tonos verdes porque la piel no siempre pierde toda la clorofila.', 'food', 'es', 'ai_generated', false),
('¿Qué crees que ocurre con las capas superficiales de la piel con el paso de las semanas?', 'A lo largo de las semanas, las capas superficiales de la piel son reemplazadas por células nuevas.', 'body', 'es', 'ai_generated', false),
('¿Cómo crees que algunas semillas pueden viajar largas distancias antes de germinar?', 'Algunas semillas tienen formas ligeras o pequeñas alas naturales que les ayudan a dejarse llevar por el viento.', 'nature', 'es', 'ai_generated', false),
('¿Desde cuándo crees que existen instrumentos parecidos al termómetro?', 'Existen desde hace más de 400 años, aunque los primeros modelos eran muy diferentes de los que utilizamos hoy en día.', 'history', 'es', 'ai_generated', false),
('¿Por qué crees que una cuchara moderna tiene una forma tan práctica?', 'Su forma actual combina siglos de pequeños cambios en comodidad, resistencia y facilidad de fabricación.', 'everyday_objects', 'es', 'ai_generated', false),
('¿De dónde crees que sale parte del olor fresco después de una tormenta?', 'Las descargas eléctricas pueden formar ozono y otros compuestos que aportan parte de ese aroma, junto con los olores que libera la lluvia al tocar el suelo.', 'weather', 'es', 'ai_generated', false),
('¿Por dónde crees que parecería salir el Sol si estuvieras en Venus?', 'En Venus, el Sol parecería salir por el oeste y ponerse por el este, porque el planeta gira en sentido contrario a la mayoría.', 'science', 'es', 'ai_generated', false),
('¿Qué animales tranquilos crees que pueden vivir más de cien años en algunas especies?', 'Algunas tortugas destacan por su extraordinaria longevidad y pueden vivir más de cien años.', 'animals', 'es', 'ai_generated', false),
('¿Qué dos tipos de conos crees que puede producir un mismo pino?', 'Muchos pinos reúnen conos masculinos y femeninos en un único ejemplar.', 'nature', 'es', 'ai_generated', false);

INSERT INTO curious_minds_prompts
  (prompt_type, prompt_text, topic, language, source, is_active)
VALUES
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una silla, además de sentarse?', 'silla', 'es', 'ai_generated', false),
('what_if', '¿Cómo crees que cambiarían nuestras rutinas si los días duraran 30 horas en lugar de 24?', 'días de 30 horas', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común un paraguas y una biblioteca?', 'paraguas y biblioteca', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántas maneras distintas se te ocurren para aprovechar una caja de cartón vacía?', 'caja de cartón', 'es', 'ai_generated', false),
('what_if', 'Si pudieras añadir una nueva estación del año, ¿cómo sería y qué tendría de especial?', 'nueva estación del año', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una receta de cocina y un viaje?', 'receta de cocina y viaje', 'es', 'ai_generated', false),
('alternate_uses', '¿Qué usos originales podría tener una linterna durante el día?', 'linterna', 'es', 'ai_generated', false),
('what_if', 'Si los animales pudieran asistir a clases, ¿qué asignaturas crees que les interesarían más?', 'animales en clase', 'es', 'ai_generated', false),
('connections', '¿Qué conexión inesperada podrías encontrar entre un reloj y un jardín?', 'reloj y jardín', 'es', 'ai_generated', false),
('what_if', 'Si pudieras diseñar una plaza perfecta para reunir a vecinos y amigos, ¿qué incluirías?', 'plaza vecinal', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para un sombrero, además de llevarlo puesto?', 'sombrero', 'es', 'ai_generated', false),
('what_if', 'Si pudieras añadir una nueva norma divertida para todos los parques, ¿cuál sería?', 'norma divertida para parques', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una receta de cocina y una partida de cartas?', 'receta de cocina y partida de cartas', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una cuerda muy larga, además de atar cosas?', 'cuerda larga', 'es', 'ai_generated', false),
('what_if', '¿Cómo sería una ciudad diseñada completamente para fomentar las conversaciones entre vecinos?', 'ciudad para conversar', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una bicicleta y una taza de café?', 'bicicleta y taza de café', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos podría tener una escalera, además de subir o bajar?', 'escalera', 'es', 'ai_generated', false),
('what_if', 'Si los árboles pudieran elegir dónde crecer, ¿qué lugares crees que preferirían?', 'árboles eligiendo lugar', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común un mercado y una colmena?', 'mercado y colmena', 'es', 'ai_generated', false),
('what_if', 'Si pudieras inventar una nueva tradición para celebrar el comienzo de cada mes, ¿cómo sería?', 'tradición mensual', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una manta, además de abrigar?', 'manta', 'es', 'ai_generated', false),
('what_if', 'Si pudieras añadir una habitación especial a todas las casas, ¿qué función tendría?', 'habitación especial en casa', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una panadería y una biblioteca?', 'panadería y biblioteca', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántas cosas podrías construir o crear con diez pinzas de la ropa?', 'pinzas de la ropa', 'es', 'ai_generated', false),
('what_if', '¿Cómo sería una plaza diseñada por niñas y niños? ¿Y una diseñada por vecinos que llevan décadas viviendo allí?', 'plaza diseñada por vecinos', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una maleta y una semilla?', 'maleta y semilla', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos podría tener una cuchara, además de comer?', 'cuchara', 'es', 'ai_generated', false),
('what_if', 'Si las calles de tu barrio llevaran nombres elegidos por los vecinos, ¿qué nombres propondrías?', 'calles con nombres vecinales', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común cuidar un jardín y mantener una amistad?', 'jardín y amistad', 'es', 'ai_generated', false),
('what_if', 'Si pudieras inventar una fiesta dedicada a algo cotidiano, ¿qué celebrarías y cómo?', 'fiesta de lo cotidiano', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una mesa, además de apoyar cosas?', 'mesa', 'es', 'ai_generated', false),
('what_if', 'Si los bancos de los parques pudieran hablar, ¿qué historias crees que contarían?', 'bancos de parque que hablan', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una llave y una canción?', 'llave y canción', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una cesta grande, además de llevar cosas?', 'cesta grande', 'es', 'ai_generated', false),
('what_if', 'Si pudieras crear una nueva tradición para los domingos, ¿cómo sería?', 'tradición de domingo', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común un reloj de cocina y una planta?', 'reloj de cocina y planta', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una docena de globos, además de decorar?', 'globos', 'es', 'ai_generated', false),
('what_if', '¿Cómo sería una cafetería diseñada para fomentar nuevas amistades?', 'cafetería para hacer amistades', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una receta y un mapa?', 'receta y mapa', 'es', 'ai_generated', false),
('what_if', 'Si pudieras añadir un nuevo sentido a las personas, ¿qué permitiría percibir?', 'nuevo sentido humano', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos creativos se te ocurren para una maleta antigua, además de viajar?', 'maleta antigua', 'es', 'ai_generated', false),
('what_if', 'Si pudieras diseñar un parque temático dedicado a recuerdos felices, ¿qué atracciones tendría?', 'parque de recuerdos felices', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una ventana y un libro?', 'ventana y libro', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántas cosas distintas podrías crear con una gran cantidad de botones?', 'botones', 'es', 'ai_generated', false),
('what_if', '¿Cómo sería una calle donde cada vecino pudiera añadir algo especial para compartir con los demás?', 'calle compartida por vecinos', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una bicicleta y una receta de cocina?', 'bicicleta y receta de cocina', 'es', 'ai_generated', false),
('alternate_uses', '¿Cuántos usos distintos se te ocurren para una alfombra, además de colocarla en el suelo?', 'alfombra', 'es', 'ai_generated', false),
('what_if', 'Si pudieras inventar una nueva forma de saludar, ¿cómo sería?', 'nueva forma de saludar', 'es', 'ai_generated', false),
('connections', '¿Qué tienen en común una estación de tren y una colmena?', 'estación de tren y colmena', 'es', 'ai_generated', false),
('what_if', 'Si cada barrio tuviera una mascota simbólica, ¿cuál elegirías para el tuyo y por qué?', 'mascota simbólica del barrio', 'es', 'ai_generated', false);
