import{CalendarDays,Stethoscope,UserRoundPlus}from"lucide-react";
import type{VoiceCanvasAgentPresenceCopy,VoiceCanvasViewModel}from"./types";
import type{AppointmentCanvasState,AppointmentProvider}from"./appointmentCanvasMachine";
export interface AppointmentCanvasCopy{
 agentPresence:VoiceCanvasAgentPresenceCopy;
 listening:{status:string;title:string;helper:string;start:string;cancel:string};provider:{title:string;helper:string;newProvider:string;newProviderHelper:string;back:string};providerEntry:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};reason:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};dateTime:{title:string;helper:string;timeLabel:string;continue:string;back:string};review:{title:string;helper:string;provider:string;reason:string;date:string;time:string;confirm:string;change:string};waiting:{status:string;title:string;helper:string;action:string};completed:{status:string;title:string;helper:string;reference:string;done:string};blocked:{status:string;title:string;helper:string;retry:string;cancel:string};cancelled:{status:string;title:string;helper:string;restart:string};progress:(current:number,total:number)=>string}
export interface AppointmentDateChoice{id:string;label:string;value:string}
export function appointmentCanvasViewModel(state:AppointmentCanvasState,copy:AppointmentCanvasCopy,providers:AppointmentProvider[],dates:AppointmentDateChoice[]):VoiceCanvasViewModel{
 const progress=(current:number)=>({current,total:4,label:copy.progress(current,4)});
 switch(state.step){
 case"listening":return{sceneId:"appointment-listening",kind:"listening",title:copy.listening.title,helperText:copy.listening.helper,status:"listening",statusLabel:copy.listening.status,primaryAction:{label:copy.listening.start},secondaryAction:{label:copy.listening.cancel}};
 case"provider":return{sceneId:"appointment-provider",kind:"choice",title:copy.provider.title,helperText:copy.provider.helper,progress:progress(1),choices:[...providers.map(provider=>({id:`provider:${provider.id}`,label:provider.label,description:provider.description,accessibleLabel:provider.label,selected:state.draft.providerId===provider.id,icon:Stethoscope})),{id:"new-provider",label:copy.provider.newProvider,description:copy.provider.newProviderHelper,accessibleLabel:copy.provider.newProvider,icon:UserRoundPlus}],secondaryAction:{label:copy.provider.back}};
 case"providerEntry":return{sceneId:"appointment-provider-entry",kind:"text-entry",title:copy.providerEntry.title,helperText:copy.providerEntry.helper,progress:progress(1),textEntry:{label:copy.providerEntry.label,value:state.draft.providerName,placeholder:copy.providerEntry.placeholder,accessibleLabel:copy.providerEntry.label},primaryAction:{label:copy.providerEntry.continue,disabled:!state.draft.providerName.trim()},secondaryAction:{label:copy.providerEntry.back}};
 case"reason":return{sceneId:"appointment-reason",kind:"text-entry",title:copy.reason.title,helperText:copy.reason.helper,progress:progress(2),textEntry:{label:copy.reason.label,value:state.draft.reason,placeholder:copy.reason.placeholder,accessibleLabel:copy.reason.label,multiline:true},primaryAction:{label:copy.reason.continue,disabled:!state.draft.reason.trim()},secondaryAction:{label:copy.reason.back}};
 case"dateTime":return{sceneId:"appointment-date-time",kind:"date-time",title:copy.dateTime.title,helperText:copy.dateTime.helper,progress:progress(3),choices:dates.map(date=>({id:`date:${date.id}`,label:date.label,accessibleLabel:date.label,selected:state.draft.dateChoice===date.value,icon:CalendarDays})),textEntry:{label:copy.dateTime.timeLabel,value:state.draft.time,type:"time",accessibleLabel:copy.dateTime.timeLabel},primaryAction:{label:copy.dateTime.continue,disabled:!state.draft.dateChoice||!state.draft.time},secondaryAction:{label:copy.dateTime.back}};
 case"review":return{sceneId:"appointment-review",kind:"review",title:copy.review.title,helperText:copy.review.helper,progress:progress(4),summaryRows:[{id:"provider",label:copy.review.provider,value:state.draft.providerName},{id:"reason",label:copy.review.reason,value:state.draft.reason},{id:"date",label:copy.review.date,value:state.draft.dateChoice},{id:"time",label:copy.review.time,value:state.draft.time}],primaryAction:{label:copy.review.confirm},secondaryAction:{label:copy.review.change}};
 case"waiting":return{sceneId:"appointment-waiting",kind:"waiting",title:copy.waiting.title,helperText:copy.waiting.helper,status:"loading",statusLabel:copy.waiting.status,primaryAction:{label:copy.waiting.action,loading:true}};
 case"completed":return{sceneId:"appointment-completed",kind:"completed",title:copy.completed.title,helperText:copy.completed.helper,status:"success",statusLabel:copy.completed.status,summaryRows:state.resultReference?[{id:"reference",label:copy.completed.reference,value:state.resultReference}]:[],primaryAction:{label:copy.completed.done}};
 case"blocked":return{sceneId:"appointment-blocked",kind:"blocked",title:copy.blocked.title,helperText:state.errorMessage||copy.blocked.helper,status:"blocked",statusLabel:copy.blocked.status,primaryAction:{label:copy.blocked.retry},secondaryAction:{label:copy.blocked.cancel}};
 case"cancelled":return{sceneId:"appointment-cancelled",kind:"blocked",title:copy.cancelled.title,helperText:copy.cancelled.helper,status:"idle",statusLabel:copy.cancelled.status,primaryAction:{label:copy.cancelled.restart}};
 }
}
