import{act,fireEvent,render,screen,waitFor}from"@testing-library/react";import{beforeEach,describe,expect,it,vi}from"vitest";import AppointmentVoiceCanvas,{type AppointmentVoiceCanvasProps}from"./AppointmentVoiceCanvas";import{VYVA_VOICE_USER_MESSAGE_EVENT,type VoiceUserMessageDetail}from"@/lib/voiceNavigation";
const copy:AppointmentVoiceCanvasProps["copy"]={agentPresence:{idleLabel:"Voice ready",idleDescription:"Use voice or touch.",listeningLabel:"Listening with you",listeningDescription:"Say or tap an appointment detail.",speakingLabel:"VYVA is speaking",speakingDescription:"Follow the screen.",thinkingLabel:"Thinking through appointment details",thinkingDescription:"Checking appointment details.",accessibleLabel:"VYVA appointment voice status"},listening:{status:"Listening",title:"Prepare appointment",helper:"Voice or touch",start:"Start",cancel:"Not now"},provider:{title:"Which provider?",helper:"Choose one",newProvider:"Different provider",newProviderHelper:"Enter name",back:"Back"},providerEntry:{title:"Provider name",helper:"Enter name",label:"Provider",placeholder:"Provider name",continue:"Continue",back:"Back"},reason:{title:"What for?",helper:"Helpful details",label:"Reason",placeholder:"Reason",continue:"Continue",back:"Back"},dateTime:{title:"When?",helper:"Day and time",timeLabel:"Time",continue:"Review",back:"Back"},review:{title:"Review preparation",helper:"Nothing is sent until confirmation",provider:"Provider",reason:"Reason",date:"Date",time:"Time",confirm:"Confirm preparation",change:"Change"},waiting:{status:"Please wait",title:"Preparing",helper:"Stay here",action:"Preparing…"},completed:{status:"Completed",title:"Ready",helper:"Review next steps",reference:"Reference",done:"Done"},blocked:{status:"Needs attention",title:"Could not prepare",helper:"Try again",retry:"Review and retry",cancel:"Cancel"},cancelled:{status:"Cancelled",title:"Nothing prepared",helper:"Nothing sent",restart:"Restart"},progress:(a,b)=>`Step ${a} of ${b}`};
const base:AppointmentVoiceCanvasProps={copy,providers:[{id:"clinic",label:"Riverside Clinic"}],dateChoices:[{id:"tomorrow",label:"Tomorrow",value:"tomorrow"}],voiceCommands:{start:["start"],back:["back"],cancel:["cancel"],confirm:["confirm"],retry:["retry"]},onConfirmPrepare:vi.fn().mockResolvedValue({reference:"APT-42"}),storageKey:"appointment-test"};const click=(name:string)=>fireEvent.click(screen.getByRole("button",{name}));function review(){click("Start");click("Riverside Clinic");fireEvent.change(screen.getByLabelText("Reason"),{target:{value:"Medication review"}});click("Continue");click("Tomorrow");fireEvent.change(screen.getByLabelText("Time"),{target:{value:"10:30"}});click("Review")}
beforeEach(()=>sessionStorage.clear());
it("does not act before explicit confirmation",async()=>{const confirm=vi.fn().mockResolvedValue({reference:"APT-42"});render(<AppointmentVoiceCanvas {...base} onConfirmPrepare={confirm}/>);review();expect(confirm).not.toHaveBeenCalled();click("Confirm preparation");expect(await screen.findByText("APT-42")).toBeInTheDocument();expect(confirm).toHaveBeenCalledOnce()});
it("handles new provider, missing fields, and backtracking",()=>{render(<AppointmentVoiceCanvas {...base}/>);click("Start");click("Different provider");expect(screen.getByRole("button",{name:"Continue"})).toBeDisabled();fireEvent.change(screen.getByLabelText("Provider"),{target:{value:"A very long translated provider label"}});click("Continue");click("Back");expect(screen.getByDisplayValue("A very long translated provider label")).toBeInTheDocument()});
it("prevents duplicate confirmation",()=>{const confirm=vi.fn(()=>new Promise(()=>{}));render(<AppointmentVoiceCanvas {...base} onConfirmPrepare={confirm}/>);review();click("Confirm preparation");fireEvent.click(screen.getByRole("button",{name:"Preparing…"}));expect(confirm).toHaveBeenCalledOnce()});
it("supports failure and retry",async()=>{const confirm=vi.fn().mockRejectedValueOnce(new Error("Unavailable")).mockResolvedValueOnce({reference:"RETRY"});render(<AppointmentVoiceCanvas {...base} onConfirmPrepare={confirm}/>);review();click("Confirm preparation");expect(await screen.findByText("Unavailable")).toBeInTheDocument();click("Review and retry");click("Confirm preparation");expect(await screen.findByText("RETRY")).toBeInTheDocument()});
it("cancels without action",()=>{const confirm=vi.fn();render(<AppointmentVoiceCanvas {...base} onConfirmPrepare={confirm}/>);click("Not now");expect(screen.getByRole("heading",{name:"Nothing prepared"})).toBeInTheDocument();expect(confirm).not.toHaveBeenCalled()});
it("restores drafts but never restores waiting",()=>{sessionStorage.setItem("appointment-test",JSON.stringify({step:"reason",requestId:0,draft:{providerId:"clinic",providerName:"Riverside Clinic",reason:"Restored",dateChoice:"",time:""}}));const{unmount}=render(<AppointmentVoiceCanvas {...base}/>);expect(screen.getByDisplayValue("Restored")).toBeInTheDocument();unmount();sessionStorage.setItem("appointment-test",JSON.stringify({step:"waiting",requestId:4,draft:{providerId:"clinic",providerName:"Riverside Clinic",reason:"x",dateChoice:"tomorrow",time:"10:30"}}));render(<AppointmentVoiceCanvas {...base}/>);expect(screen.getByRole("heading",{name:"Prepare appointment"})).toBeInTheDocument()});
it("emits privacy-safe resumed telemetry for a restored draft",()=>{const events:unknown[]=[];sessionStorage.setItem("appointment-test",JSON.stringify({step:"reason",requestId:0,draft:{providerId:"clinic",providerName:"Riverside Clinic",reason:"Private appointment reason",dateChoice:"",time:""}}));render(<AppointmentVoiceCanvas {...base} onTelemetry={event=>events.push(event)}/>);expect(events).toContainEqual(expect.objectContaining({name:"scene_viewed",step:"reason",restored:true,input:"system",attempt:0}));const serialized=JSON.stringify(events);expect(serialized).not.toContain("Riverside Clinic");expect(serialized).not.toContain("Private appointment reason")});
it("supports voice",()=>{render(<AppointmentVoiceCanvas {...base}/>);const say=(text:string)=>act(()=>window.dispatchEvent(new CustomEvent<VoiceUserMessageDetail>(VYVA_VOICE_USER_MESSAGE_EVENT,{detail:{text,transcriptEntry:{from:"user",text}}})));say("start");say("Riverside Clinic");expect(screen.getByRole("heading",{name:"What for?"})).toBeInTheDocument()});
it("moves focus and announces status",()=>{render(<AppointmentVoiceCanvas {...base}/>);expect(screen.getByRole("heading",{name:"Prepare appointment"})).toHaveFocus();click("Start");expect(screen.getByRole("heading",{name:"Which provider?"})).toHaveFocus()});
describe.each([390,768,1440])("%s px",width=>it("keeps controls available",()=>{Object.defineProperty(window,"innerWidth",{value:width,configurable:true});render(<AppointmentVoiceCanvas {...base}/>);expect(screen.getByRole("button",{name:"Start"})).toBeVisible()}));
it("telemetry excludes personal fields",async()=>{const events:unknown[]=[];render(<AppointmentVoiceCanvas {...base} onTelemetry={event=>events.push(event)}/>);review();click("Confirm preparation");await waitFor(()=>expect(events).toContainEqual(expect.objectContaining({name:"completed"})));expect(JSON.stringify(events)).not.toContain("Riverside");expect(JSON.stringify(events)).not.toContain("Medication")});
