import{Building2,ClipboardCheck,FilePenLine,Stethoscope}from"lucide-react";import type{VoiceCanvasAgentPresenceCopy,VoiceCanvasViewModel}from"./types";import type{PrescriptionFollowUpAction,PrescriptionFollowUpState}from"./prescriptionFollowUpMachine";
export interface PrescriptionFollowUpCopy{agentPresence:VoiceCanvasAgentPresenceCopy;listening:{status:string;title:string;helper:string;start:string;cancel:string};nextStep:{title:string;helper:string;clinician:string;clinicianHelper:string;pharmacy:string;pharmacyHelper:string;status:string;statusHelper:string;update:string;updateHelper:string;back:string};missingInfo:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};review:{title:string;helper:string;nextStep:string;medication:string;reviewer:string;contact?:string;information:string;prepared:string;confirm:string;back:string;actionLabels:Record<Exclude<PrescriptionFollowUpAction,"">,string>};waiting:{status:string;title:string;helper:string;action:string};completed:{status:string;title:string;helper:string;reference:string;done:string};pending:{status:string;title:string;helper:string;reference:string;done:string};blocked:{status:string;title:string;helper:string;retry:string;cancel:string};cancelled:{status:string;title:string;helper:string;restart:string};progress:(current:number,total:number)=>string}
export function prescriptionFollowUpViewModel(state:PrescriptionFollowUpState,copy:PrescriptionFollowUpCopy):VoiceCanvasViewModel{const progress=(current:number)=>({current,total:3,label:copy.progress(current,3)}),action=state.draft.action&&copy.review.actionLabels[state.draft.action];switch(state.step){
 case"listening":return{sceneId:"prescription-follow-up-listening",kind:"listening",title:copy.listening.title,helperText:copy.listening.helper,status:"listening",statusLabel:copy.listening.status,primaryAction:{label:copy.listening.start},secondaryAction:{label:copy.listening.cancel}};
 case"nextStep":return{sceneId:"prescription-follow-up-next-step",kind:"choice",title:copy.nextStep.title,helperText:copy.nextStep.helper,progress:progress(1),choices:[{id:"clinician",label:copy.nextStep.clinician,description:copy.nextStep.clinicianHelper,accessibleLabel:copy.nextStep.clinician,icon:Stethoscope},{id:"pharmacy",label:copy.nextStep.pharmacy,description:copy.nextStep.pharmacyHelper,accessibleLabel:copy.nextStep.pharmacy,icon:Building2},{id:"status",label:copy.nextStep.status,description:copy.nextStep.statusHelper,accessibleLabel:copy.nextStep.status,icon:ClipboardCheck},{id:"update",label:copy.nextStep.update,description:copy.nextStep.updateHelper,accessibleLabel:copy.nextStep.update,icon:FilePenLine}],secondaryAction:{label:copy.nextStep.back}};
 case"missingInfo":return{sceneId:"prescription-follow-up-missing-info",kind:"text-entry",title:copy.missingInfo.title,helperText:copy.missingInfo.helper,progress:progress(2),textEntry:{label:copy.missingInfo.label,value:state.draft.missingInformation,placeholder:copy.missingInfo.placeholder,accessibleLabel:copy.missingInfo.label,multiline:true},primaryAction:{label:copy.missingInfo.continue,disabled:!state.draft.missingInformation.trim()},secondaryAction:{label:copy.missingInfo.back}};
 case"review":return{sceneId:"prescription-follow-up-review",kind:"review",title:copy.review.title,helperText:copy.review.helper,progress:progress(3),summaryRows:[{id:"status",label:copy.review.prepared,value:copy.review.prepared},{id:"action",label:copy.review.nextStep,value:action||""},{id:"medication",label:copy.review.medication,value:state.source.draft.medicationName},{id:"reviewer",label:copy.review.reviewer,value:state.source.draft.providerName},{id:"contact",label:copy.review.contact||copy.review.reviewer,value:state.source.draft.contactMethod},...(state.draft.missingInformation?[{id:"information",label:copy.review.information,value:state.draft.missingInformation}]:[])],primaryAction:{label:copy.review.confirm},secondaryAction:{label:copy.review.back}};
 case"waiting":return{sceneId:"prescription-follow-up-waiting",kind:"waiting",title:copy.waiting.title,helperText:copy.waiting.helper,status:"loading",statusLabel:copy.waiting.status,primaryAction:{label:copy.waiting.action,loading:true}};
 case"completed":return{sceneId:"prescription-follow-up-completed",kind:"completed",title:copy.completed.title,helperText:copy.completed.helper,status:"success",statusLabel:copy.completed.status,summaryRows:state.resultReference?[{id:"reference",label:copy.completed.reference,value:state.resultReference}]:[],primaryAction:{label:copy.completed.done}};
 case"pending":return{sceneId:"prescription-follow-up-pending",kind:"completed",title:copy.pending.title,helperText:copy.pending.helper,status:"idle",statusLabel:copy.pending.status,summaryRows:state.resultReference?[{id:"reference",label:copy.pending.reference,value:state.resultReference}]:[],primaryAction:{label:copy.pending.done}};
 case"blocked":return{sceneId:"prescription-follow-up-blocked",kind:"blocked",title:copy.blocked.title,helperText:state.errorMessage||copy.blocked.helper,status:"blocked",statusLabel:copy.blocked.status,primaryAction:{label:copy.blocked.retry},secondaryAction:{label:copy.blocked.cancel}};
 case"cancelled":return{sceneId:"prescription-follow-up-cancelled",kind:"blocked",title:copy.cancelled.title,helperText:copy.cancelled.helper,status:"idle",statusLabel:copy.cancelled.status,primaryAction:{label:copy.cancelled.restart}};
}}
