import{AlertTriangle,Building2,CircleHelp,ClipboardList,MessageCircle,Phone,ShieldCheck,Stethoscope,UserRoundPlus}from"lucide-react";
import type{VoiceCanvasViewModel}from"./types";import type{RefillCanvasState,RefillMedication,RefillProvider}from"./refillCanvasMachine";
export interface RefillContactChoice{id:string;label:string;description?:string}
export interface RefillCanvasCopy{
 listening:{status:string;title:string;helper:string;start:string;cancel:string};medication:{title:string;helper:string;manual:string;manualHelper:string;cannotIdentify:string;cannotIdentifyHelper:string;back:string};medicationEntry:{title:string;helper:string;label:string;placeholder:string;continue:string;cannotIdentify:string;back:string};strength:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};safety:{title:string;helper:string;routine:string;routineHelper:string;urgent:string;urgentHelper:string;back:string};provider:{title:string;helper:string;manual:string;manualHelper:string;back:string};providerEntry:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};quantity:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};notes:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};contact:{title:string;helper:string;back:string};review:{title:string;helper:string;medication:string;strength:string;provider:string;quantity:string;notes:string;contact:string;noNotes:string;confirm:string;change:string};waiting:{status:string;title:string;helper:string;action:string};completed:{status:string;title:string;helper:string;reference:string;done:string};blocked:{status:string;title:string;helper:string;identificationTitle:string;identificationHelper:string;retry:string;cancel:string};urgent:{status:string;title:string;helper:string;primary:string;secondary:string};cancelled:{status:string;title:string;helper:string;restart:string};progress:(current:number,total:number)=>string}
export function refillCanvasViewModel(state:RefillCanvasState,copy:RefillCanvasCopy,medications:RefillMedication[],providers:RefillProvider[],contacts:RefillContactChoice[]):VoiceCanvasViewModel{
 const progress=(current:number)=>({current,total:7,label:copy.progress(current,7)});
 switch(state.step){
 case"listening":return{sceneId:"refill-listening",kind:"listening",title:copy.listening.title,helperText:copy.listening.helper,status:"listening",statusLabel:copy.listening.status,primaryAction:{label:copy.listening.start},secondaryAction:{label:copy.listening.cancel}};
 case"medication":return{sceneId:"refill-medication",kind:"choice",title:copy.medication.title,helperText:copy.medication.helper,progress:progress(1),choices:[...medications.map(item=>({id:`medication:${item.id}`,label:item.label,description:item.description||item.strength,accessibleLabel:item.label,selected:state.draft.medicationId===item.id,icon:ClipboardList})),{id:"manual-medication",label:copy.medication.manual,description:copy.medication.manualHelper,accessibleLabel:copy.medication.manual,icon:UserRoundPlus},{id:"cannot-identify",label:copy.medication.cannotIdentify,description:copy.medication.cannotIdentifyHelper,accessibleLabel:copy.medication.cannotIdentify,icon:CircleHelp}],secondaryAction:{label:copy.medication.back}};
 case"medicationEntry":return{sceneId:"refill-medication-entry",kind:"text-entry",title:copy.medicationEntry.title,helperText:copy.medicationEntry.helper,progress:progress(1),textEntry:{label:copy.medicationEntry.label,value:state.draft.medicationName,placeholder:copy.medicationEntry.placeholder,accessibleLabel:copy.medicationEntry.label},primaryAction:{label:copy.medicationEntry.continue,disabled:!state.draft.medicationName.trim()},secondaryAction:{label:copy.medicationEntry.back}};
 case"strength":return{sceneId:"refill-strength",kind:"text-entry",title:copy.strength.title,helperText:copy.strength.helper,progress:progress(2),textEntry:{label:copy.strength.label,value:state.draft.strength,placeholder:copy.strength.placeholder,accessibleLabel:copy.strength.label},primaryAction:{label:copy.strength.continue,disabled:!state.draft.strength.trim()},secondaryAction:{label:copy.strength.back}};
 case"safety":return{sceneId:"refill-safety",kind:"choice",title:copy.safety.title,helperText:copy.safety.helper,progress:progress(3),choices:[{id:"routine",label:copy.safety.routine,description:copy.safety.routineHelper,accessibleLabel:copy.safety.routine,icon:ShieldCheck},{id:"urgent",label:copy.safety.urgent,description:copy.safety.urgentHelper,accessibleLabel:copy.safety.urgent,icon:AlertTriangle}],secondaryAction:{label:copy.safety.back}};
 case"provider":return{sceneId:"refill-provider",kind:"choice",title:copy.provider.title,helperText:copy.provider.helper,progress:progress(4),choices:[...providers.map(item=>({id:`provider:${item.id}`,label:item.label,description:item.description,accessibleLabel:item.label,selected:state.draft.providerId===item.id,icon:item.kind==="pharmacy"?Building2:Stethoscope})),{id:"manual-provider",label:copy.provider.manual,description:copy.provider.manualHelper,accessibleLabel:copy.provider.manual,icon:UserRoundPlus}],secondaryAction:{label:copy.provider.back}};
 case"providerEntry":return{sceneId:"refill-provider-entry",kind:"text-entry",title:copy.providerEntry.title,helperText:copy.providerEntry.helper,progress:progress(4),textEntry:{label:copy.providerEntry.label,value:state.draft.providerName,placeholder:copy.providerEntry.placeholder,accessibleLabel:copy.providerEntry.label},primaryAction:{label:copy.providerEntry.continue,disabled:!state.draft.providerName.trim()},secondaryAction:{label:copy.providerEntry.back}};
 case"quantity":return{sceneId:"refill-quantity",kind:"text-entry",title:copy.quantity.title,helperText:copy.quantity.helper,progress:progress(5),textEntry:{label:copy.quantity.label,value:state.draft.quantity,placeholder:copy.quantity.placeholder,accessibleLabel:copy.quantity.label},primaryAction:{label:copy.quantity.continue,disabled:!state.draft.quantity.trim()},secondaryAction:{label:copy.quantity.back}};
 case"notes":return{sceneId:"refill-notes",kind:"text-entry",title:copy.notes.title,helperText:copy.notes.helper,progress:progress(5),textEntry:{label:copy.notes.label,value:state.draft.notes,placeholder:copy.notes.placeholder,accessibleLabel:copy.notes.label,multiline:true},primaryAction:{label:copy.notes.continue},secondaryAction:{label:copy.notes.back}};
 case"contact":return{sceneId:"refill-contact",kind:"choice",title:copy.contact.title,helperText:copy.contact.helper,progress:progress(6),choices:contacts.map(item=>({id:`contact:${item.id}`,label:item.label,description:item.description,accessibleLabel:item.label,selected:state.draft.contactMethod===item.label,icon:item.id==="phone"?Phone:MessageCircle})),secondaryAction:{label:copy.contact.back}};
 case"review":return{sceneId:"refill-review",kind:"review",title:copy.review.title,helperText:copy.review.helper,progress:progress(7),summaryRows:[{id:"medication",label:copy.review.medication,value:state.draft.medicationName},{id:"strength",label:copy.review.strength,value:state.draft.strength},{id:"provider",label:copy.review.provider,value:state.draft.providerName},{id:"quantity",label:copy.review.quantity,value:state.draft.quantity},{id:"notes",label:copy.review.notes,value:state.draft.notes||copy.review.noNotes},{id:"contact",label:copy.review.contact,value:state.draft.contactMethod}],primaryAction:{label:copy.review.confirm},secondaryAction:{label:copy.review.change}};
 case"waiting":return{sceneId:"refill-waiting",kind:"waiting",title:copy.waiting.title,helperText:copy.waiting.helper,status:"loading",statusLabel:copy.waiting.status,primaryAction:{label:copy.waiting.action,loading:true}};
 case"completed":return{sceneId:"refill-completed",kind:"completed",title:copy.completed.title,helperText:copy.completed.helper,status:"success",statusLabel:copy.completed.status,summaryRows:state.resultReference?[{id:"reference",label:copy.completed.reference,value:state.resultReference}]:[],primaryAction:{label:copy.completed.done}};
 case"blocked":return{sceneId:"refill-blocked",kind:"blocked",title:state.blockedReason==="identification"?copy.blocked.identificationTitle:copy.blocked.title,helperText:state.errorMessage||(state.blockedReason==="identification"?copy.blocked.identificationHelper:copy.blocked.helper),status:"blocked",statusLabel:copy.blocked.status,primaryAction:{label:copy.blocked.retry},secondaryAction:{label:copy.blocked.cancel}};
 case"urgent":return{sceneId:"refill-urgent",kind:"blocked",title:copy.urgent.title,helperText:copy.urgent.helper,status:"blocked",statusLabel:copy.urgent.status,primaryAction:{label:copy.urgent.primary},secondaryAction:{label:copy.urgent.secondary}};
 case"cancelled":return{sceneId:"refill-cancelled",kind:"blocked",title:copy.cancelled.title,helperText:copy.cancelled.helper,status:"idle",statusLabel:copy.cancelled.status,primaryAction:{label:copy.cancelled.restart}};
 }
}
