import{AlertTriangle,Building2,CircleHelp,ClipboardList,MessageCircle,PackageCheck,Phone,ShieldCheck,Stethoscope,UserRoundPlus}from"lucide-react";
import type{VoiceCanvasAgentPresenceCopy,VoiceCanvasOptionCardDetail,VoiceCanvasViewModel}from"./types";import type{RefillCanvasState,RefillMedication,RefillProvider}from"./refillCanvasMachine";
export interface RefillContactChoice{id:string;label:string;description?:string;reviewReminder?:string}
export interface RefillCanvasCopy{
 agentPresence:VoiceCanvasAgentPresenceCopy;
 listening:{status:string;title:string;helper:string;start:string;cancel:string};medication:{title:string;helper:string;manual:string;manualHelper:string;cannotIdentify:string;cannotIdentifyHelper:string;back:string};medicationEntry:{title:string;helper:string;label:string;placeholder:string;continue:string;cannotIdentify:string;back:string};strength:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};safety:{title:string;helper:string;routine:string;routineHelper:string;urgent:string;urgentHelper:string;back:string};provider:{title:string;helper:string;manual:string;manualHelper:string;back:string};providerEntry:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};quantity:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};notes:{title:string;helper:string;label:string;placeholder:string;continue:string;back:string};contact:{title:string;helper:string;back:string};details:{savedProfile:string;strength:string;providerType:string;quantity:string;routineBoundary:string;urgentBoundary:string;noDosingChanges:string;reviewBeforeAction:string;manualEntry:string;recommended:string};review:{title:string;helper:string;medication:string;strength:string;provider:string;quantity:string;notes:string;contact:string;noNotes:string;confirm:string;change:string};waiting:{status:string;title:string;helper:string;action:string};completed:{status:string;title:string;helper:string;reference:string;done:string};blocked:{status:string;title:string;helper:string;identificationTitle:string;identificationHelper:string;retry:string;cancel:string};urgent:{status:string;title:string;helper:string;primary:string;secondary:string};cancelled:{status:string;title:string;helper:string;restart:string};progress:(current:number,total:number)=>string}
const detail=(id:string,label:string,value?:string,tone?:"good"|"neutral"|"caution"):VoiceCanvasOptionCardDetail[]=>value?[{id,label,value,tone}]:[];
export function refillCanvasViewModel(state:RefillCanvasState,copy:RefillCanvasCopy,medications:RefillMedication[],providers:RefillProvider[],contacts:RefillContactChoice[]):VoiceCanvasViewModel{
 const progress=(current:number)=>({current,total:7,label:copy.progress(current,7)});
 switch(state.step){
 case"listening":return{sceneId:"refill-listening",kind:"listening",title:copy.listening.title,helperText:copy.listening.helper,status:"listening",statusLabel:copy.listening.status,primaryAction:{label:copy.listening.start},secondaryAction:{label:copy.listening.cancel}};
 case"medication":return{sceneId:"refill-medication",kind:"choice",title:copy.medication.title,helperText:copy.medication.helper,progress:progress(1),blocks:[...medications.map(item=>({kind:"option-card"as const,id:`medication:${item.id}`,title:item.label,subtitle:item.savedLabel||copy.details.savedProfile,description:item.description||item.strength,badge:item.recommended?copy.details.recommended:undefined,recommended:item.recommended,accessibleLabel:[item.label,item.description,item.strength].filter(Boolean).join(". "),selected:state.draft.medicationId===item.id,icon:ClipboardList,voiceAliases:item.voiceAliases,details:[...detail("strength",copy.details.strength,item.strength),...detail("profile",copy.details.savedProfile,item.profileLabel,"good"),...detail("review",copy.details.reviewBeforeAction,item.reviewReminder||copy.details.reviewBeforeAction)]})),{kind:"option-card"as const,id:"manual-medication",title:copy.medication.manual,subtitle:copy.details.manualEntry,description:copy.medication.manualHelper,accessibleLabel:copy.medication.manual,icon:UserRoundPlus,details:detail("review",copy.details.reviewBeforeAction,copy.details.reviewBeforeAction)},{kind:"option-card"as const,id:"cannot-identify",title:copy.medication.cannotIdentify,subtitle:copy.details.urgentBoundary,description:copy.medication.cannotIdentifyHelper,accessibleLabel:copy.medication.cannotIdentify,icon:CircleHelp,details:detail("boundary",copy.details.urgentBoundary,copy.details.urgentBoundary,"caution")}],secondaryAction:{label:copy.medication.back}};
 case"medicationEntry":return{sceneId:"refill-medication-entry",kind:"text-entry",title:copy.medicationEntry.title,helperText:copy.medicationEntry.helper,progress:progress(1),textEntry:{label:copy.medicationEntry.label,value:state.draft.medicationName,placeholder:copy.medicationEntry.placeholder,accessibleLabel:copy.medicationEntry.label},primaryAction:{label:copy.medicationEntry.continue,disabled:!state.draft.medicationName.trim()},secondaryAction:{label:copy.medicationEntry.back}};
 case"strength":return{sceneId:"refill-strength",kind:"text-entry",title:copy.strength.title,helperText:copy.strength.helper,progress:progress(2),blocks:[{kind:"option-card",id:"strength-guidance",title:copy.details.strength,subtitle:copy.details.noDosingChanges,description:copy.details.reviewBeforeAction,icon:ClipboardList,details:[...detail("medication",copy.review.medication,state.draft.medicationName),...detail("boundary",copy.details.noDosingChanges,copy.details.noDosingChanges,"good")],disabled:true}],textEntry:{label:copy.strength.label,value:state.draft.strength,placeholder:copy.strength.placeholder,accessibleLabel:copy.strength.label},primaryAction:{label:copy.strength.continue,disabled:!state.draft.strength.trim()},secondaryAction:{label:copy.strength.back}};
 case"safety":return{sceneId:"refill-safety",kind:"choice",title:copy.safety.title,helperText:copy.safety.helper,progress:progress(3),blocks:[{kind:"option-card",id:"routine",title:copy.safety.routine,subtitle:copy.details.routineBoundary,description:copy.safety.routineHelper,accessibleLabel:copy.safety.routine,icon:ShieldCheck,details:[...detail("dosing",copy.details.noDosingChanges,copy.details.noDosingChanges,"good"),...detail("review",copy.details.reviewBeforeAction,copy.details.reviewBeforeAction)]},{kind:"option-card",id:"urgent",title:copy.safety.urgent,subtitle:copy.details.urgentBoundary,description:copy.safety.urgentHelper,accessibleLabel:copy.safety.urgent,icon:AlertTriangle,details:detail("urgent",copy.details.urgentBoundary,copy.details.urgentBoundary,"caution")}],secondaryAction:{label:copy.safety.back}};
 case"provider":return{sceneId:"refill-provider",kind:"choice",title:copy.provider.title,helperText:copy.provider.helper,progress:progress(4),blocks:[...providers.map(item=>({kind:"option-card"as const,id:`provider:${item.id}`,title:item.label,subtitle:item.typeLabel||copy.details.providerType,description:item.description,badge:item.recommended?copy.details.recommended:undefined,recommended:item.recommended,accessibleLabel:[item.label,item.description,item.kind].filter(Boolean).join(". "),selected:state.draft.providerId===item.id,icon:item.kind==="pharmacy"?Building2:Stethoscope,voiceAliases:item.voiceAliases,details:[...detail("type",copy.details.providerType,item.typeLabel||item.kind),...detail("review",copy.details.reviewBeforeAction,item.reviewReminder||copy.details.reviewBeforeAction)]})),{kind:"option-card"as const,id:"manual-provider",title:copy.provider.manual,subtitle:copy.details.manualEntry,description:copy.provider.manualHelper,accessibleLabel:copy.provider.manual,icon:UserRoundPlus,details:detail("review",copy.details.reviewBeforeAction,copy.details.reviewBeforeAction)}],secondaryAction:{label:copy.provider.back}};
 case"providerEntry":return{sceneId:"refill-provider-entry",kind:"text-entry",title:copy.providerEntry.title,helperText:copy.providerEntry.helper,progress:progress(4),textEntry:{label:copy.providerEntry.label,value:state.draft.providerName,placeholder:copy.providerEntry.placeholder,accessibleLabel:copy.providerEntry.label},primaryAction:{label:copy.providerEntry.continue,disabled:!state.draft.providerName.trim()},secondaryAction:{label:copy.providerEntry.back}};
 case"quantity":return{sceneId:"refill-quantity",kind:"text-entry",title:copy.quantity.title,helperText:copy.quantity.helper,progress:progress(5),blocks:[{kind:"option-card",id:"quantity-guidance",title:copy.details.quantity,subtitle:copy.details.noDosingChanges,description:copy.details.reviewBeforeAction,icon:PackageCheck,details:[...detail("provider",copy.review.provider,state.draft.providerName),...detail("boundary",copy.details.noDosingChanges,copy.details.noDosingChanges,"good")],disabled:true}],textEntry:{label:copy.quantity.label,value:state.draft.quantity,placeholder:copy.quantity.placeholder,accessibleLabel:copy.quantity.label},primaryAction:{label:copy.quantity.continue,disabled:!state.draft.quantity.trim()},secondaryAction:{label:copy.quantity.back}};
 case"notes":return{sceneId:"refill-notes",kind:"text-entry",title:copy.notes.title,helperText:copy.notes.helper,progress:progress(5),textEntry:{label:copy.notes.label,value:state.draft.notes,placeholder:copy.notes.placeholder,accessibleLabel:copy.notes.label,multiline:true},primaryAction:{label:copy.notes.continue},secondaryAction:{label:copy.notes.back}};
 case"contact":return{sceneId:"refill-contact",kind:"choice",title:copy.contact.title,helperText:copy.contact.helper,progress:progress(6),blocks:contacts.map(item=>({kind:"option-card"as const,id:`contact:${item.id}`,title:item.label,subtitle:copy.details.reviewBeforeAction,description:item.description,accessibleLabel:item.label,selected:state.draft.contactMethod===item.label,icon:item.id==="phone"?Phone:MessageCircle,details:detail("review",copy.details.reviewBeforeAction,item.reviewReminder||copy.details.reviewBeforeAction)})),secondaryAction:{label:copy.contact.back}};
 case"review":return{sceneId:"refill-review",kind:"review",title:copy.review.title,helperText:copy.review.helper,progress:progress(7),summaryRows:[{id:"medication",label:copy.review.medication,value:state.draft.medicationName},{id:"strength",label:copy.review.strength,value:state.draft.strength},{id:"provider",label:copy.review.provider,value:state.draft.providerName},{id:"quantity",label:copy.review.quantity,value:state.draft.quantity},{id:"notes",label:copy.review.notes,value:state.draft.notes||copy.review.noNotes},{id:"contact",label:copy.review.contact,value:state.draft.contactMethod}],primaryAction:{label:copy.review.confirm},secondaryAction:{label:copy.review.change}};
 case"waiting":return{sceneId:"refill-waiting",kind:"waiting",title:copy.waiting.title,helperText:copy.waiting.helper,status:"loading",statusLabel:copy.waiting.status,primaryAction:{label:copy.waiting.action,loading:true}};
 case"completed":return{sceneId:"refill-completed",kind:"completed",title:copy.completed.title,helperText:copy.completed.helper,status:"success",statusLabel:copy.completed.status,summaryRows:state.resultReference?[{id:"reference",label:copy.completed.reference,value:state.resultReference}]:[],primaryAction:{label:copy.completed.done}};
 case"blocked":return{sceneId:"refill-blocked",kind:"blocked",title:state.blockedReason==="identification"?copy.blocked.identificationTitle:copy.blocked.title,helperText:state.errorMessage||(state.blockedReason==="identification"?copy.blocked.identificationHelper:copy.blocked.helper),status:"blocked",statusLabel:copy.blocked.status,primaryAction:{label:copy.blocked.retry},secondaryAction:{label:copy.blocked.cancel}};
 case"urgent":return{sceneId:"refill-urgent",kind:"blocked",title:copy.urgent.title,helperText:copy.urgent.helper,status:"blocked",statusLabel:copy.urgent.status,primaryAction:{label:copy.urgent.primary},secondaryAction:{label:copy.urgent.secondary}};
 case"cancelled":return{sceneId:"refill-cancelled",kind:"blocked",title:copy.cancelled.title,helperText:copy.cancelled.helper,status:"idle",statusLabel:copy.cancelled.status,primaryAction:{label:copy.cancelled.restart}};
 }
}
