export type PreventionContentFocus =
  | "Heart"
  | "Diabetes"
  | "Falls"
  | "Medicine"
  | "Follow-up"
  | "Plan";

export type PreventionContentActionType =
  | "Eat"
  | "Move"
  | "Calm"
  | "Check"
  | "Protect"
  | "Home safety"
  | "Medicine"
  | "Review"
  | "Plan"
  | "Sleep"
  | "Learn"
  | "Avoid";

export type PreventionContentRoute = {
  label: string;
  route:
    | "recipes"
    | "concierge.shopping"
    | "vyva.chat"
    | "activities.breathing"
    | "activities.seated_strength"
    | "activities.sit_to_stand"
    | "activities.balance"
    | "health.vitals"
    | "health.check_in"
    | "health.symptoms"
    | "health.report"
    | "meds"
    | "safe_home"
    | "concierge"
    | "concierge.schedule"
    | "concierge.transport"
    | "community";
  type: "content" | "concierge" | "voice" | "route";
};

export type PreventionContentRecipe = {
  title: string;
  prepTime: string;
  ingredients: string[];
  seniorFriendlyWhy: string;
  allergyNotes?: string[];
};

export type PreventionSourceRef = {
  name: string;
  url: string;
  dateChecked: string;
};

export type PreventionContentEntry = {
  id: string;
  focus: PreventionContentFocus;
  actionType: PreventionContentActionType;
  severityTier: 1 | 2 | 3 | 4 | 5;
  medicalBoundary: "general_wellness";
  title: string;
  shortText: string;
  seniorMessage: string;
  why: string;
  caregiverRationale: string;
  bestFor: string[];
  avoidIf: string[];
  doNotSay: string[];
  redFlags: string[];
  escalationRule: string;
  actionRoutes: PreventionContentRoute[];
  recipes?: PreventionContentRecipe[];
  shoppingList?: string[];
  voiceVersion: string;
  cardVersion: {
    title: string;
    detail: string;
    evidenceLabel: string;
  };
  sourceRefs: PreventionSourceRef[];
  clinicalRisk: "low" | "moderate" | "high";
  reviewDate: string;
  locale: "en";
  tags: string[];
};

const REVIEW_DATE = "2026-07-02";

export const PREVENTION_SOURCE_REFS = {
  cdcOlderActivity: {
    name: "CDC What Counts as Physical Activity for Older Adults",
    url: "https://www.cdc.gov/physical-activity-basics/adding-older-adults/what-counts.html",
    dateChecked: REVIEW_DATE,
  },
  nhlbiDash: {
    name: "NHLBI DASH Eating Plan",
    url: "https://www.nhlbi.nih.gov/health/dash-eating-plan",
    dateChecked: REVIEW_DATE,
  },
  ahaHomeBp: {
    name: "American Heart Association Home Blood Pressure Monitoring",
    url: "https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/monitoring-your-blood-pressure-at-home",
    dateChecked: REVIEW_DATE,
  },
  ahaStress: {
    name: "American Heart Association Managing Stress to Control High Blood Pressure",
    url: "https://www.heart.org/en/health-topics/high-blood-pressure/changes-you-can-make-to-manage-high-blood-pressure/managing-stress-to-control-high-blood-pressure",
    dateChecked: REVIEW_DATE,
  },
  ahaEmergencyBp: {
    name: "American Heart Association When To Call 911 About High Blood Pressure",
    url: "https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings/when-to-call-911-for-high-blood-pressure",
    dateChecked: REVIEW_DATE,
  },
  cdcHeartAttack: {
    name: "CDC Heart Attack Symptoms",
    url: "https://www.cdc.gov/heart-disease/about/heart-attack.html",
    dateChecked: REVIEW_DATE,
  },
  cdcStroke: {
    name: "CDC Signs and Symptoms of Stroke",
    url: "https://www.cdc.gov/stroke/signs-symptoms/index.html",
    dateChecked: REVIEW_DATE,
  },
  cdcDiabetesMeals: {
    name: "CDC Diabetes Meal Planning",
    url: "https://www.cdc.gov/diabetes/healthy-eating/diabetes-meal-planning.html",
    dateChecked: REVIEW_DATE,
  },
  adaEating: {
    name: "American Diabetes Association Eating Well and Managing Diabetes",
    url: "https://diabetes.org/food-nutrition/eating-healthy",
    dateChecked: REVIEW_DATE,
  },
  adaExercise: {
    name: "American Diabetes Association Understanding Blood Glucose and Exercise",
    url: "https://diabetes.org/health-wellness/fitness/blood-glucose-and-exercise",
    dateChecked: REVIEW_DATE,
  },
  cdcDiabetesSymptoms: {
    name: "CDC Symptoms of Diabetes",
    url: "https://www.cdc.gov/diabetes/signs-symptoms/index.html",
    dateChecked: REVIEW_DATE,
  },
  cdcHypoglycemia: {
    name: "CDC Low Blood Sugar Hypoglycemia",
    url: "https://www.cdc.gov/diabetes/about/low-blood-sugar-hypoglycemia.html",
    dateChecked: REVIEW_DATE,
  },
  niddkDiabetes: {
    name: "NIDDK Managing Diabetes",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/managing-diabetes",
    dateChecked: REVIEW_DATE,
  },
  uspstfFalls: {
    name: "USPSTF Falls Prevention in Community-Dwelling Older Adults",
    url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/falls-prevention-community-dwelling-older-adults-interventions",
    dateChecked: REVIEW_DATE,
  },
  cdcFalls: {
    name: "CDC Facts About Falls",
    url: "https://www.cdc.gov/falls/data-research/facts-stats/index.html",
    dateChecked: REVIEW_DATE,
  },
  niaFallsHome: {
    name: "National Institute on Aging Preventing Falls at Home",
    url: "https://www.nia.nih.gov/health/falls-and-falls-prevention/preventing-falls-home-room-room",
    dateChecked: REVIEW_DATE,
  },
  niaMedsSafe: {
    name: "National Institute on Aging Taking Medicines Safely as You Age",
    url: "https://www.nia.nih.gov/health/medicines-and-medication-management/taking-medicines-safely-you-age",
    dateChecked: REVIEW_DATE,
  },
  fdaMedList: {
    name: "FDA Create and Keep a Medication List for Your Health",
    url: "https://www.fda.gov/consumers/consumer-updates/create-and-keep-medication-list-your-health",
    dateChecked: REVIEW_DATE,
  },
  medlineQuestions: {
    name: "MedlinePlus Taking Medicines What to Ask Your Provider",
    url: "https://medlineplus.gov/ency/patientinstructions/000535.htm",
    dateChecked: REVIEW_DATE,
  },
  medlineOrganize: {
    name: "MedlinePlus Keeping Your Medicines Organized",
    url: "https://medlineplus.gov/ency/patientinstructions/000600.htm",
    dateChecked: REVIEW_DATE,
  },
  medlineMultiple: {
    name: "MedlinePlus Taking Multiple Medicines Safely",
    url: "https://medlineplus.gov/ency/patientinstructions/000883.htm",
    dateChecked: REVIEW_DATE,
  },
  fdaDisposal: {
    name: "FDA Disposal of Unused Medicines",
    url: "https://www.fda.gov/drugs/safe-disposal-medicines/disposal-unused-medicines-what-you-should-know",
    dateChecked: REVIEW_DATE,
  },
  nhsDoctorQuestions: {
    name: "NHS What to Ask Your Doctor or Other Healthcare Professional",
    url: "https://www.nhs.uk/nhs-services/gps/what-to-ask-your-doctor/",
    dateChecked: REVIEW_DATE,
  },
  cdcVaccines: {
    name: "CDC Recommended Vaccinations for Adults",
    url: "https://www.cdc.gov/vaccines/imz-schedules/adult-easyread.html",
    dateChecked: REVIEW_DATE,
  },
  uspstfAB: {
    name: "USPSTF A and B Recommendations",
    url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation-topics/uspstf-a-and-b-recommendations",
    dateChecked: REVIEW_DATE,
  },
  niaSleep: {
    name: "NIA Sleep and Older Adults",
    url: "https://www.nia.nih.gov/health/sleep/sleep-and-older-adults",
    dateChecked: REVIEW_DATE,
  },
  niaSocial: {
    name: "NIA Loneliness and Social Isolation",
    url: "https://www.nia.nih.gov/health/loneliness-and-social-isolation",
    dateChecked: REVIEW_DATE,
  },
  niaCognitive: {
    name: "NIA Cognitive Health and Older Adults",
    url: "https://www.nia.nih.gov/health/brain-health/cognitive-health-and-older-adults",
    dateChecked: REVIEW_DATE,
  },
  cdcOral: {
    name: "CDC About Oral Health",
    url: "https://www.cdc.gov/oral-health/about/index.html",
    dateChecked: REVIEW_DATE,
  },
  niaEyes: {
    name: "NIA Aging and Your Eyes",
    url: "https://www.nia.nih.gov/health/vision-and-vision-loss/aging-and-your-eyes",
    dateChecked: REVIEW_DATE,
  },
  niaHearing: {
    name: "NIA Hearing and Hearing Loss",
    url: "https://www.nia.nih.gov/health/hearing-and-hearing-loss",
    dateChecked: REVIEW_DATE,
  },
  niaMeals: {
    name: "NIA Healthy Meal Planning Tips for Older Adults",
    url: "https://www.nia.nih.gov/health/healthy-eating-nutrition-and-diet/healthy-meal-planning-tips-older-adults",
    dateChecked: REVIEW_DATE,
  },
  cdcWater: {
    name: "CDC About Water and Healthier Drinks",
    url: "https://www.cdc.gov/healthy-weight-growth/water-healthy-drinks/index.html",
    dateChecked: REVIEW_DATE,
  },
} satisfies Record<string, PreventionSourceRef>;

const DEFAULT_DO_NOT_SAY = [
  "This diagnoses or treats a condition.",
  "Change, stop, double, or skip prescribed medicine.",
  "This is safe for everyone.",
];

const DEFAULT_REDFLAGS = [
  "chest pain",
  "trouble breathing",
  "new confusion",
];

function uniqueList(items: string[]) {
  return Array.from(new Set(items.filter(Boolean)));
}

function route(label: PreventionContentRoute["label"], routeName: PreventionContentRoute["route"], type: PreventionContentRoute["type"]): PreventionContentRoute {
  return { label, route: routeName, type };
}

function entry(config: Omit<PreventionContentEntry, "medicalBoundary" | "clinicalRisk" | "reviewDate" | "locale" | "doNotSay" | "redFlags" | "avoidIf" | "escalationRule" | "caregiverRationale"> & {
  clinicalRisk?: PreventionContentEntry["clinicalRisk"];
  doNotSay?: string[];
  redFlags?: string[];
  avoidIf?: string[];
  escalationRule?: string;
  caregiverRationale?: string;
}): PreventionContentEntry {
  return {
    ...config,
    medicalBoundary: "general_wellness",
    clinicalRisk: config.clinicalRisk ?? (config.severityTier >= 4 ? "high" : "low"),
    reviewDate: REVIEW_DATE,
    locale: "en",
    doNotSay: config.doNotSay ? uniqueList([...DEFAULT_DO_NOT_SAY, ...config.doNotSay]) : DEFAULT_DO_NOT_SAY,
    redFlags: config.redFlags ?? DEFAULT_REDFLAGS,
    avoidIf: config.avoidIf ?? ["specific allergy", "clinician advised restriction", "feeling unwell or unsafe"],
    escalationRule: config.escalationRule ?? "Do not escalate from this item alone. Escalate only if paired with red-flag symptoms or repeated concerning readings.",
    caregiverRationale: config.caregiverRationale ?? `${config.title} is a low-risk lifestyle or organisation action for ${config.focus.toLowerCase()} wellness support.`,
  };
}

const foodRoutes = [
  route("Show recipes", "recipes", "content"),
  route("Get groceries", "concierge.shopping", "concierge"),
  route("Ask VYVA", "vyva.chat", "voice"),
];

const breathingRoutes = [
  route("Start breathing", "activities.breathing", "route"),
  route("Ask VYVA", "vyva.chat", "voice"),
];

const vitalsRoutes = [
  route("Open Vitals", "health.vitals", "route"),
  route("Ask VYVA", "vyva.chat", "voice"),
];

const medicineRoutes = [
  route("Review medicine", "meds", "route"),
  route("Ask pharmacist", "vyva.chat", "voice"),
];

const sleepRoutes = [
  route("Start breathing", "activities.breathing", "route"),
  route("Ask VYVA", "vyva.chat", "voice"),
];

const homeSafetyRoutes = [
  route("Home safety", "safe_home", "route"),
  route("Home help", "concierge", "concierge"),
  route("Ask VYVA", "vyva.chat", "voice"),
];

export const PREVENTION_CONTENT_LIBRARY: PreventionContentEntry[] = [
  entry({
    id: "heart_low_salt_meal_001",
    focus: "Heart",
    actionType: "Eat",
    severityTier: 1,
    title: "Low-salt meal",
    shortText: "Choose vegetables, protein, fruit, and water. Skip salty sauces.",
    seniorMessage: "A lower-salt meal is a good move for your heart today.",
    why: "Supports blood pressure wellness.",
    bestFor: ["high blood pressure", "heart disease", "recent high blood pressure reading"],
    actionRoutes: foodRoutes,
    recipes: [
      {
        title: "Lemon chicken with vegetables",
        prepTime: "25 min",
        ingredients: ["chicken", "vegetables", "lemon", "olive oil"],
        seniorFriendlyWhy: "Simple, flavorful, and lower in salt.",
        allergyNotes: ["Check ingredients against saved allergies."],
      },
      {
        title: "White bean vegetable soup",
        prepTime: "20 min",
        ingredients: ["no-salt-added beans", "vegetables", "low-salt stock", "herbs"],
        seniorFriendlyWhy: "Soft, filling, and easy to prepare.",
      },
    ],
    shoppingList: ["fresh or frozen vegetables", "lean protein", "fruit", "no-salt-added beans"],
    voiceVersion: "Try a simple lower-salt meal today. Vegetables, protein, fruit, and water are enough.",
    cardVersion: { title: "Low-salt meal", detail: "Recipe, groceries, or meal help.", evidenceLabel: "DASH-style food" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhlbiDash],
    tags: ["sodium", "dash", "food", "heart"],
  }),
  entry({
    id: "heart_fruit_veg_plate_002",
    focus: "Heart",
    actionType: "Eat",
    severityTier: 1,
    title: "Fruit and veg",
    shortText: "Add fruit or vegetables to one meal today.",
    seniorMessage: "Adding fruit or vegetables is a simple heart-friendly choice.",
    why: "Fits a heart-healthy eating pattern.",
    bestFor: ["high blood pressure", "heart disease", "low appetite"],
    actionRoutes: foodRoutes,
    shoppingList: ["berries", "bananas", "leafy greens", "frozen vegetables"],
    voiceVersion: "Add one fruit or vegetable today. Small counts.",
    cardVersion: { title: "Fruit and veg", detail: "Add one simple side.", evidenceLabel: "Heart food" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhlbiDash],
    tags: ["fruit", "vegetables", "dash", "food"],
  }),
  entry({
    id: "heart_potassium_question_003",
    focus: "Heart",
    actionType: "Learn",
    severityTier: 3,
    title: "Potassium question",
    shortText: "Ask if potassium-rich foods fit your care plan.",
    seniorMessage: "If your clinician has not restricted potassium, ask whether potassium-rich foods fit you.",
    why: "Some diets need clinician guidance.",
    bestFor: ["high blood pressure", "kidney disease context", "diet questions"],
    avoidIf: ["kidney disease unless clinician-approved", "potassium restriction", "specific food allergy"],
    doNotSay: ["Everyone should increase potassium.", "Potassium foods treat hypertension.", "Ignore kidney-related diet advice."],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Ask your doctor or nurse whether potassium-rich foods are right for you.",
    cardVersion: { title: "Potassium question", detail: "Ask before changing diet.", evidenceLabel: "Diet safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhlbiDash],
    tags: ["potassium", "kidney", "doctor", "diet"],
  }),
  entry({
    id: "heart_water_swap_004",
    focus: "Heart",
    actionType: "Eat",
    severityTier: 1,
    title: "Water swap",
    shortText: "Choose water instead of a sugary drink.",
    seniorMessage: "Water is a simple, steady choice today.",
    why: "Supports hydration without added sugar.",
    bestFor: ["heart profile", "diabetes profile", "hydration"],
    actionRoutes: [route("Get essentials", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["water", "unsweetened tea", "sugar-free flavour drops"],
    voiceVersion: "Keep water nearby today. A small glass is enough to start.",
    cardVersion: { title: "Water swap", detail: "Choose water today.", evidenceLabel: "Hydration" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["water", "hydration", "sugar"],
  }),
  entry({
    id: "heart_bp_technique_005",
    focus: "Heart",
    actionType: "Check",
    severityTier: 2,
    title: "BP technique",
    shortText: "Rest quietly, keep arm supported, and avoid talking.",
    seniorMessage: "A calm blood pressure check can be more useful.",
    why: "Improves home reading quality.",
    bestFor: ["recent high blood pressure reading", "home blood pressure", "heart disease"],
    actionRoutes: vitalsRoutes,
    voiceVersion: "Rest quietly first. Keep your arm supported and try not to talk during the reading.",
    cardVersion: { title: "BP technique", detail: "Rest, support arm, no talking.", evidenceLabel: "AHA check" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaHomeBp],
    tags: ["blood pressure", "vitals", "reading"],
  }),
  entry({
    id: "heart_two_readings_006",
    focus: "Heart",
    actionType: "Check",
    severityTier: 2,
    title: "Two readings",
    shortText: "Take two readings one minute apart if you are checking.",
    seniorMessage: "If you check blood pressure today, two quiet readings can help.",
    why: "Supports a clearer pattern.",
    bestFor: ["recent high blood pressure reading", "home blood pressure"],
    actionRoutes: vitalsRoutes,
    voiceVersion: "If you are checking blood pressure, take two quiet readings one minute apart.",
    cardVersion: { title: "Two readings", detail: "Repeat after one minute.", evidenceLabel: "AHA check" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaHomeBp],
    tags: ["blood pressure", "vitals", "repeat"],
  }),
  entry({
    id: "heart_calm_breath_007",
    focus: "Heart",
    actionType: "Calm",
    severityTier: 1,
    title: "Calm breathing",
    shortText: "Try three minutes of slow, comfortable breathing.",
    seniorMessage: "A short breathing reset can make the next step feel calmer.",
    why: "Supports calm pacing.",
    bestFor: ["high blood pressure", "stress", "recent high reading"],
    actionRoutes: breathingRoutes,
    voiceVersion: "Try three quiet minutes of breathing. Stop if you feel unwell.",
    cardVersion: { title: "Calm breathing", detail: "Open a calm routine.", evidenceLabel: "Calm routine" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaStress],
    tags: ["breathing", "stress", "heart"],
  }),
  entry({
    id: "heart_easy_walk_008",
    focus: "Heart",
    actionType: "Move",
    severityTier: 1,
    title: "Easy walk",
    shortText: "Take a short easy walk if you feel steady.",
    seniorMessage: "A gentle walk is enough. Keep the pace easy.",
    why: "Supports regular activity.",
    bestFor: ["heart profile", "high blood pressure", "no urgent symptoms"],
    actionRoutes: [route("Start movement", "activities.seated_strength", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "If you feel steady, try a short easy walk. Stop if anything feels wrong.",
    cardVersion: { title: "Easy walk", detail: "Keep the pace easy.", evidenceLabel: "Gentle activity" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOlderActivity],
    tags: ["walking", "activity", "heart"],
  }),
  entry({
    id: "heart_slow_start_009",
    focus: "Heart",
    actionType: "Protect",
    severityTier: 1,
    title: "Slow start",
    shortText: "Avoid rushing before checks or activity.",
    seniorMessage: "Start slowly today. Rushing can make things feel harder.",
    why: "Keeps the day calmer.",
    bestFor: ["recent high blood pressure reading", "heart profile", "dizziness"],
    actionRoutes: breathingRoutes,
    voiceVersion: "Start slowly today. A calm pace is the goal.",
    cardVersion: { title: "Slow start", detail: "Avoid rushing today.", evidenceLabel: "Pacing" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaStress],
    tags: ["pacing", "breathing", "heart"],
  }),
  entry({
    id: "heart_skip_salty_foods_010",
    focus: "Heart",
    actionType: "Avoid",
    severityTier: 1,
    title: "Skip salty foods",
    shortText: "Choose fresh or simple foods over salty packaged foods.",
    seniorMessage: "A simple lower-salt swap is a helpful choice today.",
    why: "Supports lower-sodium eating.",
    bestFor: ["high blood pressure", "salty diet", "heart profile"],
    actionRoutes: foodRoutes,
    shoppingList: ["fresh fruit", "plain yogurt", "unsalted nuts", "low-salt soup"],
    voiceVersion: "Try one lower-salt swap today. Simple food is fine.",
    cardVersion: { title: "Lower-salt swap", detail: "Swap one salty food.", evidenceLabel: "Sodium swap" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhlbiDash],
    tags: ["sodium", "avoid", "food"],
  }),
  entry({
    id: "heart_sleep_winddown_011",
    focus: "Heart",
    actionType: "Sleep",
    severityTier: 1,
    title: "Sleep winddown",
    shortText: "Plan a quiet winddown before bed.",
    seniorMessage: "A quiet winddown may help the day settle.",
    why: "Supports rest and routine.",
    bestFor: ["heart profile", "stress", "poor sleep"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Start breathing", "activities.breathing", "route")],
    voiceVersion: "Pick one quiet winddown tonight. Keep it simple.",
    cardVersion: { title: "Sleep winddown", detail: "Plan a quiet bedtime.", evidenceLabel: "Rest" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaStress, PREVENTION_SOURCE_REFS.niaSleep],
    tags: ["sleep", "stress", "routine"],
  }),
  entry({
    id: "heart_dinner_salt_scan_013",
    focus: "Heart",
    actionType: "Avoid",
    severityTier: 1,
    title: "Salt scan",
    shortText: "Before dinner, avoid one salty shortcut such as soup, sauce, or deli meat.",
    seniorMessage: "One salt scan before dinner can make today easier on your heart.",
    why: "Supports lower-sodium eating when blood pressure is the focus.",
    bestFor: ["high blood pressure", "salty diet", "ready meals", "heart profile"],
    actionRoutes: foodRoutes,
    shoppingList: ["low-salt soup", "fresh vegetables", "herbs", "plain protein"],
    voiceVersion: "Before dinner, swap one salty shortcut for a simpler option.",
    cardVersion: { title: "Salt scan", detail: "Swap one salty shortcut.", evidenceLabel: "Sodium swap" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhlbiDash],
    tags: ["sodium", "low salt", "dinner", "heart"],
  }),
  entry({
    id: "heart_after_meal_stroll_014",
    focus: "Heart",
    actionType: "Move",
    severityTier: 1,
    title: "Easy stroll",
    shortText: "Take a short easy stroll after a meal if you feel steady.",
    seniorMessage: "A gentle after-meal stroll can be enough for today.",
    why: "Supports regular activity without pushing intensity.",
    bestFor: ["heart profile", "high blood pressure", "diabetes profile", "older adult"],
    actionRoutes: [route("Start movement", "activities.seated_strength", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Try a short easy stroll after a meal if you feel steady.",
    cardVersion: { title: "Easy stroll", detail: "Keep it gentle.", evidenceLabel: "Light activity" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOlderActivity],
    tags: ["walking", "after meal", "activity", "heart"],
  }),
  entry({
    id: "heart_quiet_winddown_015",
    focus: "Heart",
    actionType: "Sleep",
    severityTier: 1,
    title: "Quiet winddown",
    shortText: "Pick one quiet bedtime cue and keep the room calm.",
    seniorMessage: "A quiet bedtime cue can help the day settle.",
    why: "Supports regular rest and calmer pacing.",
    bestFor: ["heart profile", "stress", "poor sleep", "high blood pressure"],
    actionRoutes: sleepRoutes,
    voiceVersion: "Pick one quiet bedtime cue tonight. Keep it simple.",
    cardVersion: { title: "Quiet winddown", detail: "Choose one bedtime cue.", evidenceLabel: "Rest routine" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaSleep, PREVENTION_SOURCE_REFS.ahaStress],
    tags: ["sleep", "routine", "stress", "heart"],
  }),
  entry({
    id: "heart_seek_help_012",
    focus: "Heart",
    actionType: "Protect",
    severityTier: 5,
    title: "Urgent signs",
    shortText: "Get urgent help for chest pain, breathlessness, or sudden weakness.",
    seniorMessage: "If chest pain, trouble breathing, or sudden weakness happens, get urgent help now.",
    why: "Official red flags need fast help.",
    bestFor: ["red flag symptoms", "very high blood pressure with symptoms", "possible heart attack or stroke"],
    avoidIf: [],
    doNotSay: ["Wait and see with chest pain.", "This is probably fine.", "Drive yourself if you feel faint."],
    redFlags: ["chest pain", "shortness of breath", "sudden weakness", "difficulty speaking", "vision change"],
    escalationRule: "Escalate immediately if any listed red flag is present.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Call help", "vyva.chat", "voice")],
    voiceVersion: "For chest pain, trouble breathing, or sudden weakness, get urgent help now.",
    cardVersion: { title: "Urgent signs", detail: "Know when to get help.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.ahaEmergencyBp, PREVENTION_SOURCE_REFS.cdcHeartAttack, PREVENTION_SOURCE_REFS.cdcStroke],
    clinicalRisk: "high",
    tags: ["urgent", "red flags", "heart"],
  }),

  entry({
    id: "diabetes_steady_plate_001",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Steady plate",
    shortText: "Use vegetables, protein, and a smaller carb portion.",
    seniorMessage: "A steady plate is a useful food move today.",
    why: "Supports blood sugar wellness.",
    bestFor: ["diabetes", "recent high glucose", "meal planning"],
    actionRoutes: foodRoutes,
    recipes: [
      {
        title: "Egg and vegetable plate",
        prepTime: "15 min",
        ingredients: ["eggs", "spinach", "tomatoes", "wholegrain toast"],
        seniorFriendlyWhy: "Protein and vegetables first, with a simple carb.",
      },
    ],
    shoppingList: ["non-starchy vegetables", "eggs", "lean protein", "wholegrain bread"],
    voiceVersion: "Try vegetables and protein first, then a smaller carb portion.",
    cardVersion: { title: "Steady plate", detail: "Protein and veg first.", evidenceLabel: "Plate method" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals, PREVENTION_SOURCE_REFS.adaEating],
    tags: ["plate method", "food", "diabetes"],
  }),
  entry({
    id: "diabetes_half_veg_002",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Half vegetables",
    shortText: "Make half the plate non-starchy vegetables.",
    seniorMessage: "Half a plate of vegetables is a simple diabetes-friendly pattern.",
    why: "Fits the plate method.",
    bestFor: ["diabetes", "meal planning", "high glucose"],
    actionRoutes: foodRoutes,
    shoppingList: ["broccoli", "green beans", "salad leaves", "peppers"],
    voiceVersion: "If you can, make half the plate non-starchy vegetables.",
    cardVersion: { title: "Half vegetables", detail: "Build the plate simply.", evidenceLabel: "Plate method" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals],
    tags: ["vegetables", "plate method", "food"],
  }),
  entry({
    id: "diabetes_slow_carb_003",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Slow carb",
    shortText: "Choose a smaller portion of wholegrain or beans.",
    seniorMessage: "A smaller slow-carb portion can fit a steady plate.",
    why: "Supports steadier meals.",
    bestFor: ["diabetes", "carb choices", "meal planning"],
    actionRoutes: foodRoutes,
    shoppingList: ["beans", "oats", "brown rice", "wholegrain bread"],
    voiceVersion: "Choose a smaller portion of wholegrain or beans if it fits your plan.",
    cardVersion: { title: "Slow carb", detail: "Choose a smaller portion.", evidenceLabel: "Carb choice" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals, PREVENTION_SOURCE_REFS.adaEating],
    tags: ["carbs", "wholegrain", "beans"],
  }),
  entry({
    id: "diabetes_lower_sugar_swap_004",
    focus: "Diabetes",
    actionType: "Avoid",
    severityTier: 1,
    title: "Lower-sugar swap",
    shortText: "Swap a sugary drink or dessert for a simpler option.",
    seniorMessage: "One lower-sugar swap is enough for today.",
    why: "Reduces added sugar.",
    bestFor: ["diabetes", "high glucose", "sugary drinks"],
    actionRoutes: [route("Get groceries", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["water", "unsweetened yogurt", "berries", "unsweetened tea"],
    voiceVersion: "Try one lower-sugar swap today. Water, yogurt, or fruit can be enough.",
    cardVersion: { title: "Sugar swap", detail: "Swap one sweet item.", evidenceLabel: "Lower sugar" },
    sourceRefs: [PREVENTION_SOURCE_REFS.adaEating, PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["sugar", "swap", "drinks"],
  }),
  entry({
    id: "diabetes_water_first_005",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Water first",
    shortText: "Keep water nearby and take small sips.",
    seniorMessage: "Water is a good first move today.",
    why: "Supports hydration.",
    bestFor: ["recent high glucose", "diabetes", "thirst"],
    actionRoutes: [route("Get essentials", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["water", "unsweetened tea"],
    voiceVersion: "Keep water nearby and take small sips.",
    cardVersion: { title: "Water first", detail: "Keep water nearby.", evidenceLabel: "Hydration" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcWater, PREVENTION_SOURCE_REFS.cdcDiabetesSymptoms],
    tags: ["water", "thirst", "hydration"],
  }),
  entry({
    id: "diabetes_after_meal_walk_006",
    focus: "Diabetes",
    actionType: "Move",
    severityTier: 1,
    title: "After-meal move",
    shortText: "Try an easy walk or seated movement after eating.",
    seniorMessage: "A gentle after-meal move can be a useful habit.",
    why: "Supports activity after meals.",
    bestFor: ["diabetes", "recent high glucose", "after meals"],
    actionRoutes: [route("Start exercise", "activities.seated_strength", "route"), route("Start breathing", "activities.breathing", "route")],
    voiceVersion: "After eating, try a gentle walk or seated movement if you feel steady.",
    cardVersion: { title: "After-meal move", detail: "Gentle movement after eating.", evidenceLabel: "Gentle activity" },
    sourceRefs: [PREVENTION_SOURCE_REFS.adaExercise, PREVENTION_SOURCE_REFS.cdcOlderActivity],
    tags: ["movement", "after meal", "diabetes"],
  }),
  entry({
    id: "diabetes_snack_pair_007",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Snack pair",
    shortText: "Pair a small carb with protein if you snack.",
    seniorMessage: "If you need a snack, keep it simple and steady.",
    why: "Supports steadier choices.",
    bestFor: ["diabetes", "snacking", "low appetite"],
    actionRoutes: foodRoutes,
    shoppingList: ["plain yogurt", "berries", "cheese", "wholegrain crackers"],
    voiceVersion: "If you snack, try a small carb with protein.",
    cardVersion: { title: "Snack pair", detail: "Keep snacks steady.", evidenceLabel: "Snack support" },
    sourceRefs: [PREVENTION_SOURCE_REFS.adaEating],
    tags: ["snack", "protein", "carb"],
  }),
  entry({
    id: "diabetes_body_cues_008",
    focus: "Diabetes",
    actionType: "Check",
    severityTier: 2,
    title: "Body cues",
    shortText: "Notice thirst, shakiness, sweating, dizziness, or confusion.",
    seniorMessage: "Notice how your body feels today, especially thirst, shakiness, or dizziness.",
    why: "Cues can guide what to report.",
    bestFor: ["diabetes", "recent high glucose", "possible low blood sugar"],
    actionRoutes: [route("Check symptoms", "health.symptoms", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Notice thirst, shakiness, sweating, dizziness, or confusion. Tell someone if it worries you.",
    cardVersion: { title: "Body cues", detail: "Notice sugar-related signs.", evidenceLabel: "Watch signs" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesSymptoms, PREVENTION_SOURCE_REFS.cdcHypoglycemia],
    tags: ["symptoms", "watch signs", "diabetes"],
  }),
  entry({
    id: "diabetes_low_sugar_help_009",
    focus: "Diabetes",
    actionType: "Protect",
    severityTier: 4,
    title: "Low sugar signs",
    shortText: "Get help for severe shaking, confusion, fainting, or not improving.",
    seniorMessage: "If you feel confused, faint, or severely shaky, get help now.",
    why: "Severe low sugar can be urgent.",
    bestFor: ["low blood sugar symptoms", "confusion", "fainting"],
    avoidIf: [],
    doNotSay: ["Ignore confusion.", "Wait alone if faint.", "This is definitely low blood sugar."],
    redFlags: ["confusion", "fainting", "severe shakiness", "not improving"],
    escalationRule: "Escalate if severe symptoms, confusion, fainting, or not improving are present.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Confusion, fainting, or severe shakiness needs help now.",
    cardVersion: { title: "Low sugar signs", detail: "Know urgent signs.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcHypoglycemia],
    clinicalRisk: "high",
    tags: ["urgent", "low sugar", "red flags"],
  }),
  entry({
    id: "diabetes_high_sugar_help_010",
    focus: "Diabetes",
    actionType: "Protect",
    severityTier: 4,
    title: "High sugar signs",
    shortText: "Get help for confusion, fainting, extreme thirst, or feeling very unwell.",
    seniorMessage: "If you feel confused, faint, or very unwell, get help now.",
    why: "Very high sugar can become urgent.",
    bestFor: ["very high glucose", "confusion", "fainting", "extreme thirst"],
    avoidIf: [],
    doNotSay: ["This proves your sugar is high.", "Just exercise hard.", "Wait alone if confused."],
    redFlags: ["confusion", "fainting", "extreme thirst", "very unwell"],
    escalationRule: "Escalate if confusion, fainting, or severe symptoms are present.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Confusion, fainting, or feeling very unwell needs help now.",
    cardVersion: { title: "High sugar signs", detail: "Know urgent signs.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niddkDiabetes, PREVENTION_SOURCE_REFS.cdcDiabetesSymptoms],
    clinicalRisk: "high",
    tags: ["urgent", "high sugar", "red flags"],
  }),
  entry({
    id: "diabetes_label_check_011",
    focus: "Diabetes",
    actionType: "Check",
    severityTier: 1,
    title: "Label check",
    shortText: "Look for added sugar in one packaged food.",
    seniorMessage: "Check one label today. Added sugar can hide in packaged foods.",
    why: "Supports lower-sugar choices.",
    bestFor: ["diabetes", "packaged foods", "meal planning"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Get groceries", "concierge.shopping", "concierge")],
    voiceVersion: "Check one food label for added sugar today.",
    cardVersion: { title: "Label check", detail: "Check one packaged food.", evidenceLabel: "Food label" },
    sourceRefs: [PREVENTION_SOURCE_REFS.adaEating],
    tags: ["label", "sugar", "food"],
  }),
  entry({
    id: "diabetes_simple_meal_plan_012",
    focus: "Diabetes",
    actionType: "Plan",
    severityTier: 1,
    title: "Meal plan",
    shortText: "Choose one simple meal before you get hungry.",
    seniorMessage: "Planning one simple meal can make the day easier.",
    why: "Supports routine.",
    bestFor: ["diabetes", "meal planning", "lives alone"],
    actionRoutes: foodRoutes,
    shoppingList: ["vegetables", "lean protein", "wholegrain option", "water"],
    voiceVersion: "Pick one simple meal before you get too hungry.",
    cardVersion: { title: "Meal plan", detail: "Choose one simple meal.", evidenceLabel: "Planning" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals],
    tags: ["meal plan", "routine", "food"],
  }),
  entry({
    id: "diabetes_no_sugary_drink_013",
    focus: "Diabetes",
    actionType: "Avoid",
    severityTier: 1,
    title: "Drink swap",
    shortText: "Choose water or unsweetened tea instead of a sugary drink.",
    seniorMessage: "A simple drink swap can help keep the day steadier.",
    why: "Avoids added sugar from drinks.",
    bestFor: ["diabetes", "high glucose", "sugary drinks", "thirst"],
    actionRoutes: [route("Get essentials", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["water", "unsweetened tea", "sugar-free flavour drops"],
    voiceVersion: "Choose water or unsweetened tea instead of a sugary drink today.",
    cardVersion: { title: "Drink swap", detail: "Skip sugary drinks.", evidenceLabel: "Lower sugar" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals, PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["lower sugar", "water", "drink", "diabetes"],
  }),
  entry({
    id: "diabetes_protein_breakfast_014",
    focus: "Diabetes",
    actionType: "Eat",
    severityTier: 1,
    title: "Protein breakfast",
    shortText: "Add protein to breakfast, such as eggs, yogurt, beans, or tofu.",
    seniorMessage: "Protein at breakfast can make the morning feel steadier.",
    why: "Supports a balanced diabetes-friendly meal pattern.",
    bestFor: ["diabetes", "morning hunger", "high glucose", "low appetite"],
    actionRoutes: foodRoutes,
    recipes: [
      {
        title: "Greek yogurt bowl",
        prepTime: "5 min",
        ingredients: ["plain Greek yogurt", "berries", "nuts or seeds"],
        seniorFriendlyWhy: "Soft, quick, and easy to adjust.",
        allergyNotes: ["Skip nuts or seeds if they conflict with saved allergies."],
      },
    ],
    shoppingList: ["eggs", "plain Greek yogurt", "beans", "tofu"],
    voiceVersion: "Add a simple protein to breakfast if it fits your diet.",
    cardVersion: { title: "Protein breakfast", detail: "Start steady.", evidenceLabel: "Balanced plate" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcDiabetesMeals, PREVENTION_SOURCE_REFS.adaEating],
    tags: ["protein", "breakfast", "diabetes", "food"],
  }),
  entry({
    id: "diabetes_evening_winddown_015",
    focus: "Diabetes",
    actionType: "Sleep",
    severityTier: 1,
    title: "Evening routine",
    shortText: "Set one calm evening cue so tomorrow starts predictably.",
    seniorMessage: "A predictable evening routine can make tomorrow easier.",
    why: "Supports routine and rest.",
    bestFor: ["diabetes", "poor sleep", "stress", "routine"],
    actionRoutes: sleepRoutes,
    voiceVersion: "Choose one calm evening cue tonight.",
    cardVersion: { title: "Evening routine", detail: "Keep tomorrow predictable.", evidenceLabel: "Rest routine" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaSleep],
    tags: ["sleep", "routine", "diabetes"],
  }),
  entry({
    id: "diabetes_calm_pause_016",
    focus: "Diabetes",
    actionType: "Calm",
    severityTier: 1,
    title: "Calm pause",
    shortText: "Use a calm breathing pause if movement feels too much.",
    seniorMessage: "A calm pause is a useful backup when movement feels hard.",
    why: "Keeps the day steady without forcing exercise.",
    bestFor: ["diabetes", "movement too hard", "stress", "dizziness"],
    actionRoutes: breathingRoutes,
    voiceVersion: "Use a calm breathing pause if movement feels too much.",
    cardVersion: { title: "Calm pause", detail: "Use breathing instead.", evidenceLabel: "Backup plan" },
    sourceRefs: [PREVENTION_SOURCE_REFS.adaExercise, PREVENTION_SOURCE_REFS.niaSleep],
    tags: ["breathing", "calm", "diabetes", "movement"],
  }),

  entry({
    id: "mobility_chair_strength_001",
    focus: "Falls",
    actionType: "Move",
    severityTier: 1,
    title: "Chair strength",
    shortText: "Practice supported sit-to-stand if you feel steady.",
    seniorMessage: "Supported chair strength is a good fall-prevention move.",
    why: "Builds lower-body strength.",
    bestFor: ["fall risk", "walker", "cane", "mobility support"],
    actionRoutes: [route("Start exercise", "activities.sit_to_stand", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Try supported sit-to-stand only if you feel steady.",
    cardVersion: { title: "Chair strength", detail: "Supported sit-to-stand.", evidenceLabel: "Strength" },
    sourceRefs: [PREVENTION_SOURCE_REFS.uspstfFalls, PREVENTION_SOURCE_REFS.cdcOlderActivity],
    tags: ["strength", "falls", "mobility"],
  }),
  entry({
    id: "mobility_balance_practice_002",
    focus: "Falls",
    actionType: "Move",
    severityTier: 1,
    title: "Balance practice",
    shortText: "Use support and practice only if steady.",
    seniorMessage: "A supported balance practice can help, but only if you feel safe.",
    why: "Supports balance work.",
    bestFor: ["fall risk", "balance difficulty", "mobility support"],
    actionRoutes: [route("Start balance", "activities.balance", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Use a counter or chair for support. Skip it if you feel dizzy.",
    cardVersion: { title: "Balance practice", detail: "Use support if steady.", evidenceLabel: "Balance" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOlderActivity, PREVENTION_SOURCE_REFS.uspstfFalls],
    tags: ["balance", "falls", "exercise"],
  }),
  entry({
    id: "mobility_sit_to_stand_003",
    focus: "Falls",
    actionType: "Move",
    severityTier: 1,
    title: "Sit to stand",
    shortText: "Stand slowly with support nearby.",
    seniorMessage: "Stand slowly and keep support nearby.",
    why: "Supports safer movement.",
    bestFor: ["fall risk", "dizziness when standing", "walker"],
    actionRoutes: [route("Start exercise", "activities.sit_to_stand", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Stand slowly. Hold support if you need it.",
    cardVersion: { title: "Sit to stand", detail: "Stand slowly with support.", evidenceLabel: "Steady movement" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls],
    tags: ["standing", "falls", "dizziness"],
  }),
  entry({
    id: "mobility_shoes_check_004",
    focus: "Falls",
    actionType: "Home safety",
    severityTier: 1,
    title: "Shoe check",
    shortText: "Wear firm, well-fitting shoes before walking.",
    seniorMessage: "Firm shoes can make walking steadier.",
    why: "Poor footwear can increase fall risk.",
    bestFor: ["fall risk", "walking", "poor footwear"],
    actionRoutes: [route("Get home help", "concierge", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Check your shoes before walking. Firm and well-fitting is best.",
    cardVersion: { title: "Shoe check", detail: "Wear firm shoes.", evidenceLabel: "Fall prevention" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls],
    tags: ["shoes", "falls", "protect"],
  }),
  entry({
    id: "mobility_light_path_005",
    focus: "Falls",
    actionType: "Home safety",
    severityTier: 1,
    title: "Light path",
    shortText: "Turn on lights before walking through the home.",
    seniorMessage: "Good lighting makes the next walk safer.",
    why: "Lighting reduces trip risk.",
    bestFor: ["fall risk", "lives alone", "night walking"],
    actionRoutes: [route("Home safety", "safe_home", "route"), route("Home help", "concierge", "concierge")],
    voiceVersion: "Turn on lights before walking, especially at night.",
    cardVersion: { title: "Light path", detail: "Turn lights on first.", evidenceLabel: "Home safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaFallsHome],
    tags: ["lighting", "home safety", "falls"],
  }),
  entry({
    id: "mobility_clear_clutter_006",
    focus: "Falls",
    actionType: "Home safety",
    severityTier: 1,
    title: "Clear path",
    shortText: "Move one loose rug, cord, or clutter spot.",
    seniorMessage: "Clear one walking path today. One small change helps.",
    why: "Trip hazards raise fall risk.",
    bestFor: ["fall risk", "walker", "cane", "lives alone"],
    actionRoutes: [route("Home safety", "safe_home", "route"), route("Home help", "concierge", "concierge")],
    voiceVersion: "Clear one path today. Rugs, cords, and clutter are good places to start.",
    cardVersion: { title: "Clear path", detail: "Remove one trip risk.", evidenceLabel: "Home safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls, PREVENTION_SOURCE_REFS.niaFallsHome],
    tags: ["clutter", "home safety", "falls"],
  }),
  entry({
    id: "mobility_hydration_protein_007",
    focus: "Falls",
    actionType: "Eat",
    severityTier: 1,
    title: "Protein and water",
    shortText: "Choose protein and keep water nearby.",
    seniorMessage: "Protein and water can support a steadier day.",
    why: "Supports strength and hydration.",
    bestFor: ["fall risk", "low appetite", "mobility support"],
    actionRoutes: foodRoutes,
    shoppingList: ["eggs", "plain yogurt", "beans", "water"],
    voiceVersion: "Choose a little protein and keep water nearby today.",
    cardVersion: { title: "Protein water", detail: "Support strength simply.", evidenceLabel: "Strength support" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMeals, PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["protein", "water", "strength"],
  }),
  entry({
    id: "mobility_medicine_steady_008",
    focus: "Falls",
    actionType: "Medicine",
    severityTier: 2,
    title: "Medicine steadiness",
    shortText: "Notice dizziness or sleepiness after medicines.",
    seniorMessage: "If medicine makes you dizzy or sleepy, mention it to your pharmacist or doctor.",
    why: "Some medicines affect steadiness.",
    bestFor: ["sedating medication", "dizziness", "fall risk"],
    actionRoutes: medicineRoutes,
    voiceVersion: "Notice dizziness or sleepiness after medicines. Ask before changing anything.",
    cardVersion: { title: "Medicine steadiness", detail: "Watch dizziness or sleepiness.", evidenceLabel: "Medication safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls, PREVENTION_SOURCE_REFS.medlineMultiple],
    tags: ["medicine", "dizziness", "falls"],
  }),
  entry({
    id: "mobility_bathroom_path_011",
    focus: "Falls",
    actionType: "Home safety",
    severityTier: 1,
    title: "Bathroom path",
    shortText: "Clear the route to the bathroom before bedtime.",
    seniorMessage: "A clear bathroom path can make night walking safer.",
    why: "Night walking and clutter can increase trip risk.",
    bestFor: ["fall risk", "night walking", "lives alone", "walker"],
    actionRoutes: homeSafetyRoutes,
    voiceVersion: "Clear the route to the bathroom before bedtime.",
    cardVersion: { title: "Bathroom path", detail: "Clear the night route.", evidenceLabel: "Home safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaFallsHome, PREVENTION_SOURCE_REFS.cdcFalls],
    tags: ["bathroom", "night", "home safety", "falls"],
  }),
  entry({
    id: "mobility_slow_stand_012",
    focus: "Falls",
    actionType: "Avoid",
    severityTier: 1,
    title: "No rushing up",
    shortText: "Pause after sitting, then stand slowly with support nearby.",
    seniorMessage: "Do not rush up today. Pause, then stand slowly.",
    why: "Supports steadier movement when dizziness or medicines may affect balance.",
    bestFor: ["dizziness", "sedating medication", "fall risk", "walker"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Review medicine", "meds", "route")],
    voiceVersion: "Pause before standing, then stand slowly with support nearby.",
    cardVersion: { title: "No rushing up", detail: "Pause before standing.", evidenceLabel: "Steady movement" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls, PREVENTION_SOURCE_REFS.medlineMultiple],
    tags: ["standing", "dizziness", "avoid", "falls", "medicine"],
  }),
  entry({
    id: "mobility_heavy_task_help_013",
    focus: "Falls",
    actionType: "Home safety",
    severityTier: 1,
    title: "Heavy task help",
    shortText: "Ask for help with lifting, reaching high shelves, or moving furniture.",
    seniorMessage: "Let Concierge help with a heavy or awkward task.",
    why: "Avoids risky reaching, lifting, and carrying.",
    bestFor: ["fall risk", "lives alone", "home task", "walker"],
    actionRoutes: [route("Home help", "concierge", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Ask for help with lifting, reaching, or moving furniture.",
    cardVersion: { title: "Heavy task help", detail: "Do not carry it alone.", evidenceLabel: "Home safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaFallsHome],
    tags: ["home help", "lifting", "falls", "concierge"],
  }),
  entry({
    id: "mobility_vision_check_009",
    focus: "Falls",
    actionType: "Plan",
    severityTier: 2,
    title: "Vision check",
    shortText: "Plan a vision review if seeing clearly is harder.",
    seniorMessage: "If seeing clearly is harder, it may be worth planning a vision check.",
    why: "Vision affects safe movement.",
    bestFor: ["fall risk", "vision problems", "older adult"],
    actionRoutes: [route("Book appointment", "concierge.schedule", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "If seeing clearly is harder, ask about a vision check.",
    cardVersion: { title: "Vision check", detail: "Plan a vision review.", evidenceLabel: "Fall prevention" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls, PREVENTION_SOURCE_REFS.niaEyes],
    tags: ["vision", "falls", "appointment"],
  }),
  entry({
    id: "mobility_after_fall_help_010",
    focus: "Falls",
    actionType: "Protect",
    severityTier: 5,
    title: "After a fall",
    shortText: "Get help after a fall, head hit, severe pain, or confusion.",
    seniorMessage: "After a fall, head hit, severe pain, or confusion, get help now.",
    why: "Serious falls need fast help.",
    bestFor: ["fall", "head injury", "confusion", "blood thinner"],
    avoidIf: [],
    doNotSay: ["Ignore a head hit.", "Stand up quickly after a fall.", "This is safe to handle alone."],
    redFlags: ["head hit", "severe pain", "confusion", "cannot stand", "bleeding"],
    escalationRule: "Escalate immediately for head hit, severe pain, confusion, bleeding, or inability to stand.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "If you fell and hit your head, feel confused, or cannot stand, get help now.",
    cardVersion: { title: "After a fall", detail: "Know urgent signs.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcFalls],
    clinicalRisk: "high",
    tags: ["urgent", "fall", "red flags"],
  }),

  entry({
    id: "meds_daily_cue_001",
    focus: "Medicine",
    actionType: "Review",
    severityTier: 1,
    title: "Daily cue",
    shortText: "Link medicines to a familiar meal or routine.",
    seniorMessage: "A familiar cue can make the medicine routine easier.",
    why: "Supports routine memory.",
    bestFor: ["active medications", "medicine routine", "missed medication"],
    actionRoutes: medicineRoutes,
    voiceVersion: "Link your medicine routine to something familiar, like breakfast.",
    cardVersion: { title: "Daily cue", detail: "Use a familiar routine.", evidenceLabel: "Routine cue" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineOrganize],
    tags: ["medicine", "routine", "cue"],
  }),
  entry({
    id: "meds_medicine_list_002",
    focus: "Medicine",
    actionType: "Review",
    severityTier: 1,
    title: "Medicine list",
    shortText: "Keep a current list of medicines and supplements.",
    seniorMessage: "A current medicine list can help prevent confusion.",
    why: "Supports safer conversations.",
    bestFor: ["multiple medications", "lives alone", "doctor visit"],
    actionRoutes: [route("Review medicine", "meds", "route"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Keep a current list of medicines, vitamins, and supplements.",
    cardVersion: { title: "Medicine list", detail: "Keep the list current.", evidenceLabel: "FDA list" },
    sourceRefs: [PREVENTION_SOURCE_REFS.fdaMedList],
    tags: ["medicine list", "safety", "review"],
  }),
  entry({
    id: "meds_refill_sync_003",
    focus: "Medicine",
    actionType: "Plan",
    severityTier: 1,
    title: "Refill sync",
    shortText: "Ask pharmacy if refills can be synced.",
    seniorMessage: "Refill sync can make pharmacy trips easier.",
    why: "Reduces routine friction.",
    bestFor: ["active medications", "refill needs", "pharmacy"],
    actionRoutes: [route("Review medicine", "meds", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Ask whether your refills can be synced. Do not change medicines.",
    cardVersion: { title: "Refill sync", detail: "Ask pharmacy about timing.", evidenceLabel: "Pharmacy" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMedsSafe],
    tags: ["refill", "pharmacy", "medicine"],
  }),
  entry({
    id: "meds_pill_pack_004",
    focus: "Medicine",
    actionType: "Plan",
    severityTier: 1,
    title: "Pill packs",
    shortText: "Ask whether pill packs or large labels would help.",
    seniorMessage: "Pill packs or large labels may make the routine easier.",
    why: "Supports organisation.",
    bestFor: ["medicine confusion", "multiple medications", "vision problems"],
    actionRoutes: medicineRoutes,
    voiceVersion: "Ask your pharmacist if pill packs or large labels would help.",
    cardVersion: { title: "Pill packs", detail: "Ask about easier packaging.", evidenceLabel: "Organisation" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineOrganize],
    tags: ["pill pack", "pharmacy", "organisation"],
  }),
  entry({
    id: "meds_pharmacist_questions_005",
    focus: "Medicine",
    actionType: "Plan",
    severityTier: 2,
    title: "Pharmacist questions",
    shortText: "Ask about side effects and medicine combinations.",
    seniorMessage: "Your pharmacist can help with side-effect and combination questions.",
    why: "Supports safer medicine use.",
    bestFor: ["side effects", "medicine safety signal", "multiple medications"],
    actionRoutes: medicineRoutes,
    voiceVersion: "Ask your pharmacist what side effects to watch for and what to report.",
    cardVersion: { title: "Pharmacist questions", detail: "Prepare medicine questions.", evidenceLabel: "Ask pharmacist" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineQuestions],
    tags: ["pharmacist", "side effects", "medicine"],
  }),
  entry({
    id: "meds_pause_before_change_014",
    focus: "Medicine",
    actionType: "Calm",
    severityTier: 1,
    title: "Pause first",
    shortText: "Pause and ask before changing, skipping, or doubling medicine.",
    seniorMessage: "A calm pause helps prevent medicine mistakes.",
    why: "Supports safer decisions when medicine feels confusing.",
    bestFor: ["medicine confusion", "missed medication", "side effects", "active medications"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Review medicine", "meds", "route")],
    voiceVersion: "Pause and ask before changing, skipping, or doubling medicine.",
    cardVersion: { title: "Pause first", detail: "Ask before changing anything.", evidenceLabel: "Medicine safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMedsSafe, PREVENTION_SOURCE_REFS.medlineQuestions],
    tags: ["pause", "medicine", "confusion", "safety"],
  }),
  entry({
    id: "meds_side_effect_watch_006",
    focus: "Medicine",
    actionType: "Check",
    severityTier: 2,
    title: "Side-effect watch",
    shortText: "Notice rash, swelling, dizziness, or breathing trouble.",
    seniorMessage: "Notice new symptoms after medicines and ask before changing anything.",
    why: "Supports early reporting.",
    bestFor: ["side effects", "medicine safety signal", "dizziness"],
    actionRoutes: [route("Check symptoms", "health.symptoms", "route"), route("Review medicine", "meds", "route")],
    voiceVersion: "Notice new rash, swelling, dizziness, or breathing trouble. Ask before changing medicine.",
    cardVersion: { title: "Side-effect watch", detail: "Notice new symptoms.", evidenceLabel: "Medicine safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineQuestions],
    tags: ["side effects", "symptoms", "medicine"],
  }),
  entry({
    id: "meds_missed_dose_007",
    focus: "Medicine",
    actionType: "Review",
    severityTier: 3,
    title: "Missed dose",
    shortText: "Do not double up unless a clinician told you.",
    seniorMessage: "If a dose was missed, do not double up unless your clinician told you.",
    why: "Prevents dose mistakes.",
    bestFor: ["missed medication", "late dose", "medicine confusion"],
    doNotSay: ["Double the next dose.", "Skip doses to save money.", "Change the schedule yourself."],
    actionRoutes: medicineRoutes,
    voiceVersion: "If a dose was missed, do not double up unless your clinician told you.",
    cardVersion: { title: "Missed dose", detail: "Avoid doubling up.", evidenceLabel: "Dose safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMedsSafe],
    tags: ["missed dose", "medicine", "safety"],
  }),
  entry({
    id: "meds_pharmacy_question_011",
    focus: "Medicine",
    actionType: "Medicine",
    severityTier: 2,
    title: "Pharmacy question",
    shortText: "Ask what side effects, interactions, or timing issues to watch for.",
    seniorMessage: "One pharmacy question can make the routine clearer.",
    why: "Supports safer medicine conversations.",
    bestFor: ["multiple medications", "medicine safety signal", "side effects", "pharmacy"],
    actionRoutes: medicineRoutes,
    voiceVersion: "Ask what side effects, interactions, or timing issues you should watch for.",
    cardVersion: { title: "Pharmacy question", detail: "Prepare one question.", evidenceLabel: "Ask pharmacist" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineQuestions, PREVENTION_SOURCE_REFS.medlineMultiple],
    tags: ["pharmacy", "side effects", "interactions", "medicine"],
  }),
  entry({
    id: "meds_side_effect_note_012",
    focus: "Medicine",
    actionType: "Medicine",
    severityTier: 2,
    title: "Side-effect note",
    shortText: "Write when a new symptom started and which medicine was nearby.",
    seniorMessage: "A short note can help your pharmacist or doctor understand what changed.",
    why: "Supports clear reporting without changing medicines.",
    bestFor: ["side effects", "medicine safety signal", "dizziness", "new symptom"],
    actionRoutes: [route("Check symptoms", "health.symptoms", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Write when the symptom started and which medicine was nearby. Ask before changing anything.",
    cardVersion: { title: "Side-effect note", detail: "Write what changed.", evidenceLabel: "Medicine safety" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineQuestions],
    tags: ["side effects", "symptoms", "medicine", "note"],
  }),
  entry({
    id: "meds_refill_stock_check_013",
    focus: "Medicine",
    actionType: "Medicine",
    severityTier: 1,
    title: "Refill check",
    shortText: "Check whether any medicine is running low before the weekend.",
    seniorMessage: "A quick refill check can prevent a rushed pharmacy trip.",
    why: "Supports continuity and reduces routine friction.",
    bestFor: ["refill needs", "active medications", "pharmacy", "missed medication"],
    actionRoutes: [route("Review medicine", "meds", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Check whether any medicine is running low before the weekend.",
    cardVersion: { title: "Refill check", detail: "Look before it runs low.", evidenceLabel: "Pharmacy" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMedsSafe, PREVENTION_SOURCE_REFS.medlineOrganize],
    tags: ["refill", "pharmacy", "medicine", "routine"],
  }),
  entry({
    id: "meds_food_water_cue_008",
    focus: "Medicine",
    actionType: "Eat",
    severityTier: 1,
    title: "Food water cue",
    shortText: "Keep water nearby when reviewing medicines.",
    seniorMessage: "Water nearby can make the medicine routine easier.",
    why: "Supports routine comfort.",
    bestFor: ["active medications", "medicine routine", "hydration"],
    actionRoutes: [route("Review medicine", "meds", "route"), route("Get essentials", "concierge.shopping", "concierge")],
    shoppingList: ["water", "easy breakfast", "plain yogurt"],
    voiceVersion: "Keep water nearby when you review medicines.",
    cardVersion: { title: "Food water cue", detail: "Keep water nearby.", evidenceLabel: "Routine cue" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMedsSafe, PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["water", "medicine", "cue"],
  }),
  entry({
    id: "meds_disposal_plan_009",
    focus: "Medicine",
    actionType: "Plan",
    severityTier: 1,
    title: "Disposal plan",
    shortText: "Use take-back options for unused or expired medicines.",
    seniorMessage: "Unused or expired medicines can be handled through take-back options.",
    why: "Keeps medicines organised.",
    bestFor: ["old medicines", "medicine cabinet", "lives alone"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Concierge help", "concierge", "concierge")],
    voiceVersion: "Ask VYVA about medicine take-back options. Do not throw away anything uncertain.",
    cardVersion: { title: "Disposal plan", detail: "Plan medicine take-back.", evidenceLabel: "FDA disposal" },
    sourceRefs: [PREVENTION_SOURCE_REFS.fdaDisposal],
    tags: ["disposal", "medicine", "organisation"],
  }),
  entry({
    id: "meds_breathing_redflag_010",
    focus: "Medicine",
    actionType: "Protect",
    severityTier: 5,
    title: "Medicine red flags",
    shortText: "Get urgent help for breathing trouble, swelling, or severe reaction.",
    seniorMessage: "Breathing trouble, swelling, or a severe reaction needs urgent help now.",
    why: "Severe reactions can be urgent.",
    bestFor: ["severe reaction", "trouble breathing", "swelling"],
    avoidIf: [],
    doNotSay: ["Wait alone with breathing trouble.", "Take more medicine to fix it.", "This is safe."],
    redFlags: ["trouble breathing", "face or throat swelling", "severe rash", "fainting"],
    escalationRule: "Escalate immediately for breathing trouble, swelling, fainting, or severe reaction symptoms.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Breathing trouble, swelling, or fainting needs urgent help now.",
    cardVersion: { title: "Medicine red flags", detail: "Know urgent signs.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.medlineQuestions],
    clinicalRisk: "high",
    tags: ["urgent", "medicine", "red flags"],
  }),

  entry({
    id: "symptom_what_changed_001",
    focus: "Follow-up",
    actionType: "Check",
    severityTier: 1,
    title: "What changed",
    shortText: "Write what changed since yesterday.",
    seniorMessage: "Noting what changed can make follow-up easier.",
    why: "Supports clear updates.",
    bestFor: ["recent symptom report", "follow-up", "doctor visit"],
    actionRoutes: [route("Check symptoms", "health.symptoms", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Write down what changed since yesterday.",
    cardVersion: { title: "What changed", detail: "Note the main change.", evidenceLabel: "Symptom note" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["symptoms", "notes", "follow-up"],
  }),
  entry({
    id: "symptom_timing_002",
    focus: "Follow-up",
    actionType: "Check",
    severityTier: 1,
    title: "Symptom timing",
    shortText: "Note when symptoms started and what affects them.",
    seniorMessage: "Timing helps your care team understand the story.",
    why: "Improves visit preparation.",
    bestFor: ["recent symptom report", "symptom tracking", "doctor visit"],
    actionRoutes: [route("Check symptoms", "health.symptoms", "route"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Note when it started and what makes it better or worse.",
    cardVersion: { title: "Symptom timing", detail: "Note start and changes.", evidenceLabel: "Visit prep" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["symptoms", "timing", "notes"],
  }),
  entry({
    id: "symptom_doctor_note_003",
    focus: "Follow-up",
    actionType: "Plan",
    severityTier: 1,
    title: "Doctor note",
    shortText: "Prepare one clear note for your doctor or nurse.",
    seniorMessage: "VYVA can help prepare a short note for your next conversation.",
    why: "Makes follow-up easier.",
    bestFor: ["recent symptom report", "doctor visit", "caregiver update"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Ask VYVA to prepare a short doctor note.",
    cardVersion: { title: "Doctor note", detail: "Prepare a clear update.", evidenceLabel: "Visit prep" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["doctor note", "summary", "follow-up"],
  }),
  entry({
    id: "symptom_worsening_004",
    focus: "Follow-up",
    actionType: "Protect",
    severityTier: 3,
    title: "Worse symptoms",
    shortText: "Ask for help if symptoms are worsening or worrying.",
    seniorMessage: "If symptoms are getting worse, ask for help rather than waiting alone.",
    why: "Worsening symptoms need attention.",
    bestFor: ["recent symptom report", "worsening symptoms", "lives alone"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Book appointment", "concierge.schedule", "concierge")],
    voiceVersion: "If symptoms are getting worse, ask for help rather than waiting alone.",
    cardVersion: { title: "Worse symptoms", detail: "Ask for help sooner.", evidenceLabel: "Follow-up" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["worsening", "symptoms", "follow-up"],
  }),
  entry({
    id: "symptom_simple_rest_005",
    focus: "Follow-up",
    actionType: "Eat",
    severityTier: 1,
    title: "Simple rest",
    shortText: "Plan a quiet rest and easy food.",
    seniorMessage: "A quiet rest and simple food can make follow-up easier.",
    why: "Supports a steady day.",
    bestFor: ["recent symptom report", "tired", "low appetite"],
    actionRoutes: [route("Get groceries", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["soup", "plain yogurt", "fruit", "water"],
    voiceVersion: "Plan a quiet rest and simple food today.",
    cardVersion: { title: "Easy food", detail: "Rest and simple food.", evidenceLabel: "Steady day" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaMeals, PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["rest", "food", "symptoms"],
  }),
  entry({
    id: "symptom_medicine_list_006",
    focus: "Follow-up",
    actionType: "Review",
    severityTier: 1,
    title: "Medicine list",
    shortText: "Bring a current medicine list to follow-up.",
    seniorMessage: "A medicine list helps your doctor or nurse see the full picture.",
    why: "Supports safer follow-up.",
    bestFor: ["recent symptom report", "doctor visit", "multiple medications"],
    actionRoutes: [route("Review medicine", "meds", "route"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Bring a current medicine list to follow-up.",
    cardVersion: { title: "Medicine list", detail: "Bring the current list.", evidenceLabel: "Visit prep" },
    sourceRefs: [PREVENTION_SOURCE_REFS.fdaMedList, PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["medicine list", "follow-up", "doctor"],
  }),
  entry({
    id: "symptom_vyva_summary_007",
    focus: "Follow-up",
    actionType: "Plan",
    severityTier: 1,
    title: "VYVA summary",
    shortText: "Ask VYVA to summarize symptoms, readings, and medicines.",
    seniorMessage: "VYVA can summarize what changed in simple words.",
    why: "Helps with clear communication.",
    bestFor: ["recent symptom report", "lives alone", "caregiver update"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Ask VYVA to summarize symptoms, readings, and medicines.",
    cardVersion: { title: "VYVA summary", detail: "Summarize for follow-up.", evidenceLabel: "Clear update" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["summary", "vyva", "follow-up"],
  }),
  entry({
    id: "symptom_rest_note_009",
    focus: "Follow-up",
    actionType: "Calm",
    severityTier: 1,
    title: "Rest and note",
    shortText: "Take a quiet pause, then note what changed in plain words.",
    seniorMessage: "A quiet pause and one short note can make follow-up easier.",
    why: "Supports clearer symptom tracking.",
    bestFor: ["recent symptom report", "dizziness", "stress", "follow-up"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Check symptoms", "health.symptoms", "route")],
    voiceVersion: "Take a quiet pause, then note what changed in simple words.",
    cardVersion: { title: "Rest and note", detail: "Pause, then write one line.", evidenceLabel: "Clear update" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["symptoms", "note", "calm", "follow-up"],
  }),
  entry({
    id: "symptom_share_update_010",
    focus: "Follow-up",
    actionType: "Plan",
    severityTier: 1,
    title: "Share update",
    shortText: "Share a short update with a caregiver or clinician if symptoms changed.",
    seniorMessage: "A short update can help someone understand what changed.",
    why: "Supports timely follow-up.",
    bestFor: ["recent symptom report", "caregiver update", "doctor visit", "lives alone"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Ask VYVA to prepare a short update for your caregiver or clinician.",
    cardVersion: { title: "Share update", detail: "Make a short summary.", evidenceLabel: "Follow-up" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions],
    tags: ["caregiver", "summary", "follow-up"],
  }),
  entry({
    id: "symptom_escalate_now_008",
    focus: "Follow-up",
    actionType: "Protect",
    severityTier: 5,
    title: "Urgent symptoms",
    shortText: "Get urgent help for chest pain, breathing trouble, stroke signs, or fainting.",
    seniorMessage: "Chest pain, breathing trouble, stroke signs, or fainting need urgent help now.",
    why: "Official red flags need fast help.",
    bestFor: ["red flag symptoms", "possible stroke", "possible heart attack", "fainting"],
    avoidIf: [],
    doNotSay: ["Wait and see with red flags.", "This is probably nothing.", "Stay alone if fainting."],
    redFlags: ["chest pain", "trouble breathing", "sudden weakness", "speech trouble", "fainting"],
    escalationRule: "Escalate immediately if any listed red flag is present.",
    actionRoutes: [route("SOS", "health.check_in", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Chest pain, trouble breathing, sudden weakness, speech trouble, or fainting need urgent help now.",
    cardVersion: { title: "Urgent symptoms", detail: "Know red flags.", evidenceLabel: "Red flags" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcHeartAttack, PREVENTION_SOURCE_REFS.cdcStroke],
    clinicalRisk: "high",
    tags: ["urgent", "red flags", "symptoms"],
  }),

  entry({
    id: "prevention_screening_review_001",
    focus: "Plan",
    actionType: "Plan",
    severityTier: 2,
    title: "Screening review",
    shortText: "Ask what screenings are due at your next visit.",
    seniorMessage: "A screening review is a useful prevention question.",
    why: "Supports preventive care planning.",
    bestFor: ["no strong signal", "older adult", "doctor visit"],
    actionRoutes: [route("Doctor note", "health.report", "route"), route("Book appointment", "concierge.schedule", "concierge")],
    voiceVersion: "Ask what screenings are due at your next visit.",
    cardVersion: { title: "Screening review", detail: "Ask what is due.", evidenceLabel: "Prevention" },
    sourceRefs: [PREVENTION_SOURCE_REFS.uspstfAB],
    tags: ["screening", "prevention", "plan"],
  }),
  entry({
    id: "prevention_vaccine_check_002",
    focus: "Plan",
    actionType: "Plan",
    severityTier: 2,
    title: "Vaccine check",
    shortText: "Ask if flu, COVID, RSV, shingles, or tetanus vaccines are due.",
    seniorMessage: "A vaccine check is a simple prevention step.",
    why: "Supports routine prevention.",
    bestFor: ["older adult", "no strong signal", "care gap"],
    actionRoutes: [route("Book appointment", "concierge.schedule", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Ask whether any routine vaccines are due.",
    cardVersion: { title: "Vaccine check", detail: "Ask what is due.", evidenceLabel: "Prevention" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcVaccines],
    tags: ["vaccines", "prevention", "appointment"],
  }),
  entry({
    id: "prevention_strength_balance_003",
    focus: "Plan",
    actionType: "Move",
    severityTier: 1,
    title: "Strength balance",
    shortText: "Choose a short strength or balance routine.",
    seniorMessage: "Strength and balance are useful prevention habits.",
    why: "Supports mobility and falls prevention.",
    bestFor: ["no strong signal", "fall risk", "older adult"],
    actionRoutes: [route("Start exercise", "activities.sit_to_stand", "route"), route("Start balance", "activities.balance", "route")],
    voiceVersion: "Choose a short strength or balance routine if you feel steady.",
    cardVersion: { title: "Strength balance", detail: "Open a short routine.", evidenceLabel: "Mobility" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOlderActivity, PREVENTION_SOURCE_REFS.uspstfFalls],
    tags: ["strength", "balance", "prevention"],
  }),
  entry({
    id: "prevention_daily_walk_004",
    focus: "Plan",
    actionType: "Move",
    severityTier: 1,
    title: "Daily walk",
    shortText: "Take a short easy walk if you feel steady.",
    seniorMessage: "A short easy walk is a good prevention move.",
    why: "Supports regular activity.",
    bestFor: ["no strong signal", "older adult", "heart profile"],
    actionRoutes: [route("Start exercise", "activities.seated_strength", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Take a short easy walk if you feel steady.",
    cardVersion: { title: "Daily walk", detail: "Keep the pace easy.", evidenceLabel: "Activity" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOlderActivity],
    tags: ["walking", "activity", "prevention"],
  }),
  entry({
    id: "prevention_sleep_routine_005",
    focus: "Plan",
    actionType: "Sleep",
    severityTier: 1,
    title: "Sleep routine",
    shortText: "Plan one calm step before bed.",
    seniorMessage: "One calm bedtime step can help your routine.",
    why: "Supports regular rest.",
    bestFor: ["no strong signal", "poor sleep", "older adult"],
    actionRoutes: [route("Start breathing", "activities.breathing", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Choose one calm bedtime step tonight.",
    cardVersion: { title: "Sleep routine", detail: "Plan one calm step.", evidenceLabel: "Sleep" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaSleep],
    tags: ["sleep", "routine", "prevention"],
  }),
  entry({
    id: "prevention_social_reachout_006",
    focus: "Plan",
    actionType: "Plan",
    severityTier: 1,
    title: "Reach out",
    shortText: "Message, call, or join one friendly activity.",
    seniorMessage: "A small social connection can support well-being.",
    why: "Supports connection.",
    bestFor: ["lives alone", "no strong signal", "low mood"],
    actionRoutes: [route("Join community", "community", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Reach out to one person or join one friendly activity.",
    cardVersion: { title: "Reach out", detail: "Make one connection.", evidenceLabel: "Connection" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaSocial],
    tags: ["social", "connection", "loneliness"],
  }),
  entry({
    id: "prevention_brain_activity_007",
    focus: "Plan",
    actionType: "Learn",
    severityTier: 1,
    title: "Brain activity",
    shortText: "Try one memory, reading, music, or learning activity.",
    seniorMessage: "One small brain activity can be part of prevention.",
    why: "Supports cognitive engagement.",
    bestFor: ["no strong signal", "cognitive activity", "older adult"],
    actionRoutes: [route("Mind activity", "community", "route"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "Try one memory, reading, music, or learning activity today.",
    cardVersion: { title: "Brain activity", detail: "Try one mind activity.", evidenceLabel: "Cognitive health" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaCognitive],
    tags: ["cognitive", "learning", "prevention"],
  }),
  entry({
    id: "prevention_mouth_eyes_ears_008",
    focus: "Plan",
    actionType: "Plan",
    severityTier: 2,
    title: "Check senses",
    shortText: "Plan dental, vision, or hearing care if something changed.",
    seniorMessage: "Dental, vision, and hearing checks can support daily safety.",
    why: "Supports everyday function.",
    bestFor: ["vision problems", "hearing changes", "dental care", "fall risk"],
    actionRoutes: [route("Book appointment", "concierge.schedule", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    voiceVersion: "If teeth, vision, or hearing changed, ask about a check.",
    cardVersion: { title: "Check senses", detail: "Plan care if changed.", evidenceLabel: "Daily function" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcOral, PREVENTION_SOURCE_REFS.niaEyes, PREVENTION_SOURCE_REFS.niaHearing],
    tags: ["dental", "vision", "hearing", "prevention"],
  }),
  entry({
    id: "prevention_morning_light_009",
    focus: "Plan",
    actionType: "Sleep",
    severityTier: 1,
    title: "Morning light",
    shortText: "Get morning light near a window or outside if safe.",
    seniorMessage: "Morning light can help your daily rhythm.",
    why: "Supports sleep routine and daytime rhythm.",
    bestFor: ["poor sleep", "no strong signal", "older adult", "routine"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Join community", "community", "route")],
    voiceVersion: "Get morning light near a window or outside if safe.",
    cardVersion: { title: "Morning light", detail: "Support your daily rhythm.", evidenceLabel: "Sleep routine" },
    sourceRefs: [PREVENTION_SOURCE_REFS.niaSleep],
    tags: ["sleep", "morning", "routine", "prevention"],
  }),
  entry({
    id: "prevention_easy_water_010",
    focus: "Plan",
    actionType: "Eat",
    severityTier: 1,
    title: "Water nearby",
    shortText: "Keep water where you sit most often.",
    seniorMessage: "Keeping water nearby makes a healthy choice easier.",
    why: "Supports hydration without added sugar.",
    bestFor: ["no strong signal", "older adult", "hydration", "lives alone"],
    actionRoutes: [route("Get essentials", "concierge.shopping", "concierge"), route("Ask VYVA", "vyva.chat", "voice")],
    shoppingList: ["water", "unsweetened tea"],
    voiceVersion: "Keep water where you sit most often today.",
    cardVersion: { title: "Water nearby", detail: "Make hydration easy.", evidenceLabel: "Daily basics" },
    sourceRefs: [PREVENTION_SOURCE_REFS.cdcWater],
    tags: ["water", "hydration", "prevention"],
  }),
  entry({
    id: "prevention_weekly_question_011",
    focus: "Plan",
    actionType: "Plan",
    severityTier: 1,
    title: "One question",
    shortText: "Save one question for your next health visit.",
    seniorMessage: "One saved question can make your next visit more useful.",
    why: "Supports preventive care planning.",
    bestFor: ["doctor visit", "no strong signal", "health planning", "caregiver update"],
    actionRoutes: [route("Ask VYVA", "vyva.chat", "voice"), route("Doctor note", "health.report", "route")],
    voiceVersion: "Save one question for your next health visit.",
    cardVersion: { title: "One question", detail: "Prepare for next visit.", evidenceLabel: "Care planning" },
    sourceRefs: [PREVENTION_SOURCE_REFS.nhsDoctorQuestions, PREVENTION_SOURCE_REFS.uspstfAB],
    tags: ["question", "doctor", "prevention", "plan"],
  }),
];

export const PREVENTION_CONTENT_IDS = new Set(PREVENTION_CONTENT_LIBRARY.map((item) => item.id));
