import type {
  SocialLanguage,
  SocialReadingClubDestination,
  SocialRoomMember,
} from "../../src/social/types";

type Localized<T> = Partial<Record<SocialLanguage, T>> & {
  en: T;
  es: T;
};

const pick = <T>(values: Localized<T>, language: SocialLanguage): T => values[language] ?? values.en ?? values.es;

function memberName(members: SocialRoomMember[], index: number, fallback: string) {
  return members[index]?.name || fallback;
}

export function buildReadingClubDestination(
  language: SocialLanguage,
  members: SocialRoomMember[],
  participantCount: number,
): SocialReadingClubDestination {
  const spotlightNames = [
    memberName(members, 0, language === "de" ? "Maria" : language === "en" ? "Maria" : "Maria"),
    memberName(members, 1, language === "de" ? "Jose" : language === "en" ? "Jose" : "Jose"),
    memberName(members, 2, language === "de" ? "Carmen" : language === "en" ? "Carmen" : "Carmen"),
  ];

  return pick<SocialReadingClubDestination>({
    en: {
      title: "The Reading Room Literary Club",
      subtitle: "A daily club table for books, life stories, recommendations and gentle new friendships.",
      hostNote: "Isabel keeps the room moving: short prompts, protected greetings, and no pressure to finish a book before joining.",
      todayQuestion: "Which book, character or remembered scene would you enjoy sharing with someone new?",
      metrics: [
        { id: "readers", label: "Readers today", value: String(Math.max(participantCount, 7)), detail: "drop-in members" },
        { id: "tables", label: "Club tables", value: "3", detail: "morning, afternoon, evening" },
        { id: "shelves", label: "Shelves open", value: "4", detail: "books, stories, memoirs, poems" },
      ],
      agendaTitle: "Today's club program",
      agenda: [
        {
          id: "morning-welcome",
          timeLabel: "Morning",
          title: "Welcome table",
          body: "Share one book, one line you remember, or one memory a story opened for you.",
          statusLabel: "Open now",
        },
        {
          id: "afternoon-exchange",
          timeLabel: "Afternoon",
          title: "Recommendation exchange",
          body: "Members trade gentle suggestions by mood: comforting, funny, thoughtful, familiar.",
          statusLabel: "Next table",
        },
        {
          id: "evening-salon",
          timeLabel: "Evening",
          title: "Small salon",
          body: "Isabel forms small discussion circles around memoirs, short stories and favourite characters.",
          statusLabel: "Later today",
        },
      ],
      shelvesTitle: "Club shelves",
      shelves: [
        {
          id: "currently-reading",
          title: "Currently reading",
          body: "A light shelf for what members are reading or rereading now.",
          items: [
            {
              id: "gentle-novel",
              title: "A gentle family novel",
              authorLabel: "Member pick",
              tag: "Family",
              body: "For conversations about home, siblings and the small details people remember.",
              discussionStarter: "Which family scene felt true to you?",
            },
            {
              id: "history-pages",
              title: "Pages from history",
              authorLabel: "Shared shelf",
              tag: "History",
              body: "For readers who like real events, newspapers, biographies and remembered places.",
              discussionStarter: "What period of history still feels close?",
            },
          ],
        },
        {
          id: "memory-shelf",
          title: "Memory shelf",
          body: "Stories that bring back a person, street, season or song.",
          items: [
            {
              id: "childhood-story",
              title: "A childhood story",
              authorLabel: "Story prompt",
              tag: "Memory",
              body: "Bring a schoolbook, library card, bedtime story or first poem.",
              discussionStarter: "Who first read something aloud to you?",
            },
            {
              id: "short-poem",
              title: "A short poem remembered",
              authorLabel: "Public-domain safe",
              tag: "Poetry",
              body: "Share the feeling or memory it brings, without needing long quoted passages.",
              discussionStarter: "What image from a poem stayed with you?",
            },
          ],
        },
      ],
      spotlightsTitle: "Members at the table",
      memberSpotlights: [
        {
          memberId: members[0]?.id ?? "member-maria",
          name: spotlightNames[0],
          roleLine: "Memoir and family stories",
          body: "Looking for someone who enjoys stories about ordinary days and big turning points.",
          starter: "Ask about a family story that still makes her smile.",
        },
        {
          memberId: members[1]?.id ?? "member-jose",
          name: spotlightNames[1],
          roleLine: "History and biographies",
          body: "Brought a question about how history changes when people tell it from memory.",
          starter: "Ask which biography felt most alive.",
        },
        {
          memberId: members[2]?.id ?? "member-carmen",
          name: spotlightNames[2],
          roleLine: "Theatre, stories and recommendations",
          body: "Enjoys swapping short recommendations that are easy to begin.",
          starter: "Ask for a story with a hopeful ending.",
        },
      ],
      companionTitle: "Find your place at the table",
      companionBody: "Choose the kind of literary connection you want today. Isabel will keep the introduction protected.",
      companionModes: [
        {
          id: "one-to-one",
          title: "One reader",
          body: "A private, consent-based greeting with one compatible reader.",
          ctaLabel: "Find one reader",
          bridgePrompt: "a book, character or memory you would like to share one-to-one.",
        },
        {
          id: "small-circle",
          title: "Small circle",
          body: "A calmer table with two or three people around the same theme.",
          ctaLabel: "Find a small circle",
          bridgePrompt: "a theme for a small reading circle.",
        },
        {
          id: "pen-note",
          title: "Pen note",
          body: "Start with a short written greeting before any live conversation.",
          ctaLabel: "Start with a note",
          bridgePrompt: "a short note about a book or scene you would enjoy exchanging.",
        },
      ],
      passportTitle: "Reading passport",
      passportBody: "A simple way to make today's visit feel complete.",
      passportItems: [
        { id: "share", label: "Share", body: "Add one book, scene or memory to the club table." },
        { id: "recommend", label: "Recommend", body: "Leave one gentle suggestion for another reader." },
        { id: "greet", label: "Greet", body: "Send one protected greeting or companion request." },
      ],
      reflectionTitle: "Add to the club table",
      reflectionPlaceholder: "Write a book, scene, character or memory...",
      reflectionSubmitLabel: "Post reflection",
      reflectionPrompts: [
        "A book that kept me company was...",
        "A character I still remember is...",
        "A story I would recommend gently is...",
      ],
      guidelinesTitle: "Club care",
      guidelines: [
        "Share memories and summaries in your own words.",
        "Use short excerpts only when needed.",
        "Every greeting stays protected until both people agree.",
      ],
    },
    es: {
      title: "El Club Literario de Reading Room",
      subtitle: "Una mesa diaria para libros, historias de vida, recomendaciones y nuevas amistades tranquilas.",
      hostNote: "Isabel mantiene el ritmo: preguntas breves, saludos protegidos y ninguna presion por terminar un libro.",
      todayQuestion: "Que libro, personaje o escena recordada te gustaria compartir con alguien nuevo?",
      metrics: [
        { id: "readers", label: "Lectores hoy", value: String(Math.max(participantCount, 7)), detail: "miembros que entran" },
        { id: "tables", label: "Mesas del club", value: "3", detail: "manana, tarde, noche" },
        { id: "shelves", label: "Estantes abiertos", value: "4", detail: "libros, relatos, memorias, poemas" },
      ],
      agendaTitle: "Programa de hoy",
      agenda: [
        {
          id: "morning-welcome",
          timeLabel: "Manana",
          title: "Mesa de bienvenida",
          body: "Comparte un libro, una frase que recuerdas o una memoria que abrio una historia.",
          statusLabel: "Abierta ahora",
        },
        {
          id: "afternoon-exchange",
          timeLabel: "Tarde",
          title: "Intercambio de recomendaciones",
          body: "Los miembros recomiendan por estado de animo: comodo, divertido, reflexivo, familiar.",
          statusLabel: "Siguiente mesa",
        },
        {
          id: "evening-salon",
          timeLabel: "Noche",
          title: "Salon pequeno",
          body: "Isabel forma circulos pequenos sobre memorias, cuentos y personajes favoritos.",
          statusLabel: "Mas tarde",
        },
      ],
      shelvesTitle: "Estantes del club",
      shelves: [
        {
          id: "currently-reading",
          title: "Leyendo ahora",
          body: "Un estante ligero para lo que se lee o se relee hoy.",
          items: [
            {
              id: "gentle-novel",
              title: "Una novela familiar tranquila",
              authorLabel: "Eleccion del club",
              tag: "Familia",
              body: "Para hablar de casa, hermanos y pequenos detalles que se recuerdan.",
              discussionStarter: "Que escena familiar te parecio verdadera?",
            },
            {
              id: "history-pages",
              title: "Paginas de historia",
              authorLabel: "Estante compartido",
              tag: "Historia",
              body: "Para lectores que disfrutan hechos reales, periodicos, biografias y lugares recordados.",
              discussionStarter: "Que epoca historica todavia sientes cercana?",
            },
          ],
        },
        {
          id: "memory-shelf",
          title: "Estante de recuerdos",
          body: "Historias que traen de vuelta una persona, una calle, una estacion o una cancion.",
          items: [
            {
              id: "childhood-story",
              title: "Una historia de infancia",
              authorLabel: "Pregunta del club",
              tag: "Recuerdo",
              body: "Trae un libro escolar, carnet de biblioteca, cuento nocturno o primer poema.",
              discussionStarter: "Quien te leyo algo en voz alta por primera vez?",
            },
            {
              id: "short-poem",
              title: "Un poema breve recordado",
              authorLabel: "Seguro para dominio publico",
              tag: "Poesia",
              body: "Comparte la sensacion o recuerdo que trae, sin necesitar citas largas.",
              discussionStarter: "Que imagen de un poema se quedo contigo?",
            },
          ],
        },
      ],
      spotlightsTitle: "Personas en la mesa",
      memberSpotlights: [
        {
          memberId: members[0]?.id ?? "member-maria",
          name: spotlightNames[0],
          roleLine: "Memorias e historias familiares",
          body: "Busca a alguien que disfrute historias de dias corrientes y grandes cambios.",
          starter: "Pregunta por una historia familiar que todavia le haga sonreir.",
        },
        {
          memberId: members[1]?.id ?? "member-jose",
          name: spotlightNames[1],
          roleLine: "Historia y biografias",
          body: "Trajo una pregunta sobre como cambia la historia cuando se cuenta desde la memoria.",
          starter: "Pregunta que biografia le parecio mas viva.",
        },
        {
          memberId: members[2]?.id ?? "member-carmen",
          name: spotlightNames[2],
          roleLine: "Teatro, relatos y recomendaciones",
          body: "Disfruta cambiar recomendaciones cortas que son faciles de empezar.",
          starter: "Pide una historia con final esperanzador.",
        },
      ],
      companionTitle: "Encuentra tu lugar en la mesa",
      companionBody: "Elige el tipo de conexion literaria que quieres hoy. Isabel protege la presentacion.",
      companionModes: [
        {
          id: "one-to-one",
          title: "Un lector",
          body: "Un saludo privado y protegido con una persona compatible.",
          ctaLabel: "Buscar un lector",
          bridgePrompt: "un libro, personaje o recuerdo que quieras compartir a solas.",
        },
        {
          id: "small-circle",
          title: "Circulo pequeno",
          body: "Una mesa tranquila con dos o tres personas alrededor del mismo tema.",
          ctaLabel: "Buscar circulo",
          bridgePrompt: "un tema para un pequeno circulo de lectura.",
        },
        {
          id: "pen-note",
          title: "Nota escrita",
          body: "Empieza con un saludo escrito antes de cualquier conversacion en directo.",
          ctaLabel: "Empezar con nota",
          bridgePrompt: "una nota breve sobre un libro o escena que quieras intercambiar.",
        },
      ],
      passportTitle: "Pasaporte lector",
      passportBody: "Una forma sencilla de cerrar la visita de hoy.",
      passportItems: [
        { id: "share", label: "Compartir", body: "Anade un libro, escena o recuerdo a la mesa." },
        { id: "recommend", label: "Recomendar", body: "Deja una sugerencia amable para otra persona." },
        { id: "greet", label: "Saludar", body: "Envia un saludo protegido o una peticion de compania." },
      ],
      reflectionTitle: "Anadir a la mesa",
      reflectionPlaceholder: "Escribe un libro, escena, personaje o recuerdo...",
      reflectionSubmitLabel: "Publicar reflexion",
      reflectionPrompts: [
        "Un libro que me hizo compania fue...",
        "Un personaje que todavia recuerdo es...",
        "Una historia que recomendaria con calma es...",
      ],
      guidelinesTitle: "Cuidado del club",
      guidelines: [
        "Comparte recuerdos y resumenes con tus propias palabras.",
        "Usa citas cortas solo cuando hagan falta.",
        "Cada saludo queda protegido hasta que ambas personas aceptan.",
      ],
    },
    de: {
      title: "Der Reading Room Literaturclub",
      subtitle: "Ein taeglicher Clubtisch fuer Buecher, Lebensgeschichten, Empfehlungen und ruhige neue Kontakte.",
      hostNote: "Isabel haelt den Raum in Bewegung: kurze Fragen, geschuetzte Gruesse und kein Druck, ein Buch fertig zu haben.",
      todayQuestion: "Welches Buch, welche Figur oder erinnerte Szene wuerdest du gern mit jemand Neuem teilen?",
      metrics: [
        { id: "readers", label: "Lesende heute", value: String(Math.max(participantCount, 7)), detail: "offene Mitglieder" },
        { id: "tables", label: "Clubtische", value: "3", detail: "Morgen, Nachmittag, Abend" },
        { id: "shelves", label: "Offene Regale", value: "4", detail: "Buecher, Geschichten, Memoiren, Gedichte" },
      ],
      agendaTitle: "Heutiges Clubprogramm",
      agenda: [
        {
          id: "morning-welcome",
          timeLabel: "Morgen",
          title: "Willkommenstisch",
          body: "Teile ein Buch, eine erinnerte Zeile oder eine Erinnerung, die eine Geschichte geoeffnet hat.",
          statusLabel: "Jetzt offen",
        },
        {
          id: "afternoon-exchange",
          timeLabel: "Nachmittag",
          title: "Empfehlungsaustausch",
          body: "Mitglieder tauschen sanfte Vorschlaege nach Stimmung: troestlich, lustig, nachdenklich, vertraut.",
          statusLabel: "Naechster Tisch",
        },
        {
          id: "evening-salon",
          timeLabel: "Abend",
          title: "Kleiner Salon",
          body: "Isabel bildet kleine Gespraechskreise zu Memoiren, Kurzgeschichten und Lieblingsfiguren.",
          statusLabel: "Spaeter heute",
        },
      ],
      shelvesTitle: "Clubregale",
      shelves: [
        {
          id: "currently-reading",
          title: "Gerade gelesen",
          body: "Ein leichtes Regal fuer das, was Mitglieder jetzt lesen oder wiederlesen.",
          items: [
            {
              id: "gentle-novel",
              title: "Ein ruhiger Familienroman",
              authorLabel: "Clubauswahl",
              tag: "Familie",
              body: "Fuer Gespraeche ueber Zuhause, Geschwister und kleine Details, die bleiben.",
              discussionStarter: "Welche Familienszene fuehlte sich wahr an?",
            },
            {
              id: "history-pages",
              title: "Seiten aus der Geschichte",
              authorLabel: "Geteiltes Regal",
              tag: "Geschichte",
              body: "Fuer Menschen, die echte Ereignisse, Zeitungen, Biografien und erinnerte Orte moegen.",
              discussionStarter: "Welche Zeit der Geschichte fuehlt sich noch nah an?",
            },
          ],
        },
        {
          id: "memory-shelf",
          title: "Erinnerungsregal",
          body: "Geschichten, die eine Person, Strasse, Jahreszeit oder ein Lied zurueckbringen.",
          items: [
            {
              id: "childhood-story",
              title: "Eine Kindheitsgeschichte",
              authorLabel: "Clubfrage",
              tag: "Erinnerung",
              body: "Bring ein Schulbuch, einen Bibliotheksausweis, eine Gute-Nacht-Geschichte oder ein erstes Gedicht.",
              discussionStarter: "Wer hat dir zuerst etwas vorgelesen?",
            },
            {
              id: "short-poem",
              title: "Ein kurzes erinnertes Gedicht",
              authorLabel: "Sicher fuer Gemeingut",
              tag: "Poesie",
              body: "Teile das Gefuehl oder die Erinnerung, ohne lange Textstellen zitieren zu muessen.",
              discussionStarter: "Welches Bild aus einem Gedicht blieb bei dir?",
            },
          ],
        },
      ],
      spotlightsTitle: "Menschen am Tisch",
      memberSpotlights: [
        {
          memberId: members[0]?.id ?? "member-maria",
          name: spotlightNames[0],
          roleLine: "Memoiren und Familiengeschichten",
          body: "Sucht jemanden, der Geschichten ueber gewoehnliche Tage und grosse Wendepunkte mag.",
          starter: "Frage nach einer Familiengeschichte, die sie noch laecheln laesst.",
        },
        {
          memberId: members[1]?.id ?? "member-jose",
          name: spotlightNames[1],
          roleLine: "Geschichte und Biografien",
          body: "Hat eine Frage dazu mitgebracht, wie Geschichte sich veraendert, wenn Menschen sie aus Erinnerung erzaehlen.",
          starter: "Frage, welche Biografie am lebendigsten wirkte.",
        },
        {
          memberId: members[2]?.id ?? "member-carmen",
          name: spotlightNames[2],
          roleLine: "Theater, Geschichten und Empfehlungen",
          body: "Tauscht gern kurze Empfehlungen aus, die leicht zu beginnen sind.",
          starter: "Bitte um eine Geschichte mit hoffnungsvollem Ende.",
        },
      ],
      companionTitle: "Finde deinen Platz am Tisch",
      companionBody: "Waehle die Art literarischer Verbindung fuer heute. Isabel haelt die Vorstellung geschuetzt.",
      companionModes: [
        {
          id: "one-to-one",
          title: "Eine Leserin",
          body: "Ein privater, geschuetzter Gruss mit einer passenden Person.",
          ctaLabel: "Eine Leserin finden",
          bridgePrompt: "ein Buch, eine Figur oder eine Erinnerung fuer ein Zweiergespraech.",
        },
        {
          id: "small-circle",
          title: "Kleiner Kreis",
          body: "Ein ruhiger Tisch mit zwei oder drei Menschen um dasselbe Thema.",
          ctaLabel: "Kleinen Kreis finden",
          bridgePrompt: "ein Thema fuer einen kleinen Lesekreis.",
        },
        {
          id: "pen-note",
          title: "Schreibnotiz",
          body: "Beginne mit einem kurzen geschriebenen Gruss vor jedem Live-Gespraech.",
          ctaLabel: "Mit Notiz beginnen",
          bridgePrompt: "eine kurze Notiz ueber ein Buch oder eine Szene zum Austauschen.",
        },
      ],
      passportTitle: "Lesepass",
      passportBody: "Eine einfache Art, den heutigen Besuch rund zu machen.",
      passportItems: [
        { id: "share", label: "Teilen", body: "Fuege ein Buch, eine Szene oder Erinnerung zum Clubtisch hinzu." },
        { id: "recommend", label: "Empfehlen", body: "Hinterlasse eine freundliche Empfehlung fuer eine andere Person." },
        { id: "greet", label: "Gruessen", body: "Sende einen geschuetzten Gruss oder eine Begleit-Anfrage." },
      ],
      reflectionTitle: "Zum Clubtisch hinzufuegen",
      reflectionPlaceholder: "Schreibe ein Buch, eine Szene, Figur oder Erinnerung...",
      reflectionSubmitLabel: "Beitrag posten",
      reflectionPrompts: [
        "Ein Buch, das mir Gesellschaft geleistet hat, war...",
        "Eine Figur, die ich noch erinnere, ist...",
        "Eine Geschichte, die ich sanft empfehlen wuerde, ist...",
      ],
      guidelinesTitle: "Clubachtsamkeit",
      guidelines: [
        "Teile Erinnerungen und Zusammenfassungen in eigenen Worten.",
        "Nutze kurze Auszuege nur, wenn sie wirklich helfen.",
        "Jeder Gruss bleibt geschuetzt, bis beide Personen zustimmen.",
      ],
    },
    fr: {
      title: "Le club litteraire Reading Room",
      subtitle: "Une table quotidienne pour livres, recits de vie, recommandations et nouvelles amities tranquilles.",
      hostNote: "Isabel fait avancer le salon avec des questions courtes, des salutations protegees et aucune pression pour finir un livre.",
      todayQuestion: "Quel livre, personnage ou scene gardee en memoire aimeriez-vous partager avec quelqu'un de nouveau ?",
      metrics: [
        { id: "readers", label: "Lecteurs aujourd'hui", value: String(Math.max(participantCount, 7)), detail: "membres de passage" },
        { id: "tables", label: "Tables du club", value: "3", detail: "matin, apres-midi, soir" },
        { id: "shelves", label: "Etageres ouvertes", value: "4", detail: "livres, recits, memoires, poemes" },
      ],
      agendaTitle: "Programme du club aujourd'hui",
      agenda: [
        { id: "morning-welcome", timeLabel: "Matin", title: "Table d'accueil", body: "Partagez un livre, une phrase retenue ou un souvenir qu'une histoire a ouvert.", statusLabel: "Ouverte maintenant" },
        { id: "afternoon-exchange", timeLabel: "Apres-midi", title: "Echange de recommandations", body: "Les membres echangent des suggestions par humeur : reconfortante, drole, reflechie, familiere.", statusLabel: "Prochaine table" },
        { id: "evening-salon", timeLabel: "Soir", title: "Petit salon", body: "Isabel forme de petits cercles autour des memoires, nouvelles et personnages preferes.", statusLabel: "Plus tard" },
      ],
      shelvesTitle: "Etageres du club",
      shelves: [
        {
          id: "currently-reading",
          title: "Lectures en cours",
          body: "Une etagere legere pour ce que les membres lisent ou relisent.",
          items: [
            { id: "gentle-novel", title: "Un roman familial doux", authorLabel: "Choix du club", tag: "Famille", body: "Pour parler de maison, de freres et soeurs et de petits details qui restent.", discussionStarter: "Quelle scene familiale vous a semble vraie ?" },
            { id: "history-pages", title: "Pages d'histoire", authorLabel: "Etagere partagee", tag: "Histoire", body: "Pour les personnes qui aiment les faits reels, journaux, biographies et lieux souvenus.", discussionStarter: "Quelle periode de l'histoire vous semble encore proche ?" },
          ],
        },
        {
          id: "memory-shelf",
          title: "Etagere des souvenirs",
          body: "Des histoires qui ramenent une personne, une rue, une saison ou une chanson.",
          items: [
            { id: "childhood-story", title: "Une histoire d'enfance", authorLabel: "Question du club", tag: "Souvenir", body: "Apportez un livre d'ecole, une carte de bibliotheque, une histoire du soir ou un premier poeme.", discussionStarter: "Qui vous a lu quelque chose a voix haute en premier ?" },
            { id: "short-poem", title: "Un court poeme garde en memoire", authorLabel: "Sur pour le domaine public", tag: "Poesie", body: "Partagez le sentiment ou le souvenir, sans avoir besoin de longues citations.", discussionStarter: "Quelle image d'un poeme est restee avec vous ?" },
          ],
        },
      ],
      spotlightsTitle: "Membres a la table",
      memberSpotlights: [
        { memberId: members[0]?.id ?? "member-maria", name: spotlightNames[0], roleLine: "Memoires et histoires familiales", body: "Cherche quelqu'un qui aime les histoires de jours ordinaires et de grands tournants.", starter: "Demandez une histoire familiale qui la fait encore sourire." },
        { memberId: members[1]?.id ?? "member-jose", name: spotlightNames[1], roleLine: "Histoire et biographies", body: "A apporte une question sur la facon dont l'histoire change quand elle est racontee depuis la memoire.", starter: "Demandez quelle biographie lui a semble la plus vivante." },
        { memberId: members[2]?.id ?? "member-carmen", name: spotlightNames[2], roleLine: "Theatre, recits et recommandations", body: "Aime echanger de courtes recommandations faciles a commencer.", starter: "Demandez une histoire avec une fin pleine d'espoir." },
      ],
      companionTitle: "Trouvez votre place a la table",
      companionBody: "Choisissez le type de lien litteraire souhaite aujourd'hui. Isabel garde la presentation protegee.",
      companionModes: [
        { id: "one-to-one", title: "Une personne lectrice", body: "Un salut prive et protege avec une personne compatible.", ctaLabel: "Trouver une personne", bridgePrompt: "un livre, un personnage ou un souvenir a partager a deux." },
        { id: "small-circle", title: "Petit cercle", body: "Une table calme avec deux ou trois personnes autour du meme theme.", ctaLabel: "Trouver un cercle", bridgePrompt: "un theme pour un petit cercle de lecture." },
        { id: "pen-note", title: "Note ecrite", body: "Commencer par une courte salutation ecrite avant toute conversation en direct.", ctaLabel: "Commencer par une note", bridgePrompt: "une courte note sur un livre ou une scene a echanger." },
      ],
      passportTitle: "Passeport de lecture",
      passportBody: "Une facon simple de rendre la visite d'aujourd'hui complete.",
      passportItems: [
        { id: "share", label: "Partager", body: "Ajoutez un livre, une scene ou un souvenir a la table du club." },
        { id: "recommend", label: "Recommander", body: "Laissez une suggestion douce pour une autre personne." },
        { id: "greet", label: "Saluer", body: "Envoyez une salutation protegee ou une demande de compagnie." },
      ],
      reflectionTitle: "Ajouter a la table du club",
      reflectionPlaceholder: "Ecrivez un livre, une scene, un personnage ou un souvenir...",
      reflectionSubmitLabel: "Publier la reflexion",
      reflectionPrompts: [
        "Un livre qui m'a tenu compagnie etait...",
        "Un personnage dont je me souviens encore est...",
        "Une histoire que je recommanderais doucement est...",
      ],
      guidelinesTitle: "Soin du club",
      guidelines: [
        "Partagez souvenirs et resumes avec vos propres mots.",
        "Utilisez seulement de courts extraits quand c'est utile.",
        "Chaque salutation reste protegee jusqu'a l'accord des deux personnes.",
      ],
    },
    it: {
      title: "Il club letterario Reading Room",
      subtitle: "Un tavolo quotidiano per libri, storie di vita, consigli e nuove amicizie tranquille.",
      hostNote: "Isabel mantiene vivo il salotto con domande brevi, saluti protetti e nessuna pressione a finire un libro.",
      todayQuestion: "Quale libro, personaggio o scena ricordata ti piacerebbe condividere con una persona nuova?",
      metrics: [
        { id: "readers", label: "Lettori oggi", value: String(Math.max(participantCount, 7)), detail: "membri di passaggio" },
        { id: "tables", label: "Tavoli del club", value: "3", detail: "mattina, pomeriggio, sera" },
        { id: "shelves", label: "Scaffali aperti", value: "4", detail: "libri, storie, memorie, poesie" },
      ],
      agendaTitle: "Programma del club di oggi",
      agenda: [
        { id: "morning-welcome", timeLabel: "Mattina", title: "Tavolo di benvenuto", body: "Condividi un libro, una frase ricordata o un ricordo aperto da una storia.", statusLabel: "Aperto ora" },
        { id: "afternoon-exchange", timeLabel: "Pomeriggio", title: "Scambio di consigli", body: "I membri scambiano suggerimenti per umore: conforto, sorriso, riflessione, familiarita.", statusLabel: "Prossimo tavolo" },
        { id: "evening-salon", timeLabel: "Sera", title: "Piccolo salotto", body: "Isabel forma piccoli cerchi su memorie, racconti brevi e personaggi preferiti.", statusLabel: "Piu tardi" },
      ],
      shelvesTitle: "Scaffali del club",
      shelves: [
        {
          id: "currently-reading",
          title: "Letture in corso",
          body: "Uno scaffale leggero per cio che i membri leggono o rileggono ora.",
          items: [
            { id: "gentle-novel", title: "Un romanzo familiare gentile", authorLabel: "Scelta del club", tag: "Famiglia", body: "Per parlare di casa, fratelli e piccoli dettagli che restano.", discussionStarter: "Quale scena familiare ti e sembrata vera?" },
            { id: "history-pages", title: "Pagine di storia", authorLabel: "Scaffale condiviso", tag: "Storia", body: "Per chi ama eventi reali, giornali, biografie e luoghi ricordati.", discussionStarter: "Quale periodo storico sembra ancora vicino?" },
          ],
        },
        {
          id: "memory-shelf",
          title: "Scaffale dei ricordi",
          body: "Storie che riportano una persona, una strada, una stagione o una canzone.",
          items: [
            { id: "childhood-story", title: "Una storia d'infanzia", authorLabel: "Domanda del club", tag: "Ricordo", body: "Porta un libro di scuola, una tessera di biblioteca, una storia della sera o una prima poesia.", discussionStarter: "Chi ti ha letto qualcosa ad alta voce per primo?" },
            { id: "short-poem", title: "Una poesia breve ricordata", authorLabel: "Sicura per dominio pubblico", tag: "Poesia", body: "Condividi il sentimento o il ricordo, senza bisogno di citazioni lunghe.", discussionStarter: "Quale immagine di una poesia e rimasta con te?" },
          ],
        },
      ],
      spotlightsTitle: "Membri al tavolo",
      memberSpotlights: [
        { memberId: members[0]?.id ?? "member-maria", name: spotlightNames[0], roleLine: "Memorie e storie familiari", body: "Cerca qualcuno che ami storie di giorni ordinari e grandi svolte.", starter: "Chiedi una storia familiare che la faccia ancora sorridere." },
        { memberId: members[1]?.id ?? "member-jose", name: spotlightNames[1], roleLine: "Storia e biografie", body: "Ha portato una domanda su come la storia cambia quando passa dalla memoria.", starter: "Chiedi quale biografia e sembrata piu viva." },
        { memberId: members[2]?.id ?? "member-carmen", name: spotlightNames[2], roleLine: "Teatro, storie e consigli", body: "Ama scambiare brevi consigli facili da iniziare.", starter: "Chiedi una storia con un finale pieno di speranza." },
      ],
      companionTitle: "Trova il tuo posto al tavolo",
      companionBody: "Scegli il tipo di connessione letteraria che desideri oggi. Isabel mantiene protetta la presentazione.",
      companionModes: [
        { id: "one-to-one", title: "Una persona lettrice", body: "Un saluto privato e protetto con una persona compatibile.", ctaLabel: "Trova una persona", bridgePrompt: "un libro, un personaggio o un ricordo da condividere a due." },
        { id: "small-circle", title: "Piccolo cerchio", body: "Un tavolo calmo con due o tre persone intorno allo stesso tema.", ctaLabel: "Trova un cerchio", bridgePrompt: "un tema per un piccolo cerchio di lettura." },
        { id: "pen-note", title: "Nota scritta", body: "Inizia con un breve saluto scritto prima di ogni conversazione dal vivo.", ctaLabel: "Inizia con una nota", bridgePrompt: "una breve nota su un libro o una scena da scambiare." },
      ],
      passportTitle: "Passaporto di lettura",
      passportBody: "Un modo semplice per rendere completa la visita di oggi.",
      passportItems: [
        { id: "share", label: "Condividi", body: "Aggiungi un libro, una scena o un ricordo al tavolo del club." },
        { id: "recommend", label: "Consiglia", body: "Lascia un suggerimento gentile per un'altra persona." },
        { id: "greet", label: "Saluta", body: "Invia un saluto protetto o una richiesta di compagnia." },
      ],
      reflectionTitle: "Aggiungi al tavolo del club",
      reflectionPlaceholder: "Scrivi un libro, una scena, un personaggio o un ricordo...",
      reflectionSubmitLabel: "Pubblica riflessione",
      reflectionPrompts: [
        "Un libro che mi ha fatto compagnia e stato...",
        "Un personaggio che ricordo ancora e...",
        "Una storia che consiglierei con gentilezza e...",
      ],
      guidelinesTitle: "Cura del club",
      guidelines: [
        "Condividi ricordi e riassunti con parole tue.",
        "Usa solo brevi estratti quando servono.",
        "Ogni saluto resta protetto finche entrambe le persone accettano.",
      ],
    },
    pt: {
      title: "O Clube Literario Reading Room",
      subtitle: "Uma mesa diaria para livros, historias de vida, recomendacoes e novas amizades tranquilas.",
      hostNote: "A Isabel mantem a sala em movimento com perguntas curtas, saudacoes protegidas e sem pressao para terminar um livro.",
      todayQuestion: "Que livro, personagem ou cena recordada gostaria de partilhar com alguem novo?",
      metrics: [
        { id: "readers", label: "Leitores hoje", value: String(Math.max(participantCount, 7)), detail: "membros de passagem" },
        { id: "tables", label: "Mesas do clube", value: "3", detail: "manha, tarde, noite" },
        { id: "shelves", label: "Prateleiras abertas", value: "4", detail: "livros, historias, memorias, poemas" },
      ],
      agendaTitle: "Programa do clube de hoje",
      agenda: [
        { id: "morning-welcome", timeLabel: "Manha", title: "Mesa de boas-vindas", body: "Partilhe um livro, uma frase recordada ou uma memoria que uma historia abriu.", statusLabel: "Aberta agora" },
        { id: "afternoon-exchange", timeLabel: "Tarde", title: "Troca de recomendacoes", body: "Os membros trocam sugestoes por humor: conforto, humor, reflexao, familiaridade.", statusLabel: "Proxima mesa" },
        { id: "evening-salon", timeLabel: "Noite", title: "Pequeno salao", body: "A Isabel forma pequenos circulos sobre memorias, contos e personagens preferidas.", statusLabel: "Mais tarde" },
      ],
      shelvesTitle: "Prateleiras do clube",
      shelves: [
        {
          id: "currently-reading",
          title: "A ler agora",
          body: "Uma prateleira leve para o que os membros estao a ler ou reler.",
          items: [
            { id: "gentle-novel", title: "Um romance familiar tranquilo", authorLabel: "Escolha do clube", tag: "Familia", body: "Para conversas sobre casa, irmaos e pequenos detalhes que ficam.", discussionStarter: "Que cena familiar lhe pareceu verdadeira?" },
            { id: "history-pages", title: "Paginas de historia", authorLabel: "Prateleira partilhada", tag: "Historia", body: "Para quem gosta de acontecimentos reais, jornais, biografias e lugares lembrados.", discussionStarter: "Que periodo da historia ainda parece proximo?" },
          ],
        },
        {
          id: "memory-shelf",
          title: "Prateleira de memorias",
          body: "Historias que trazem de volta uma pessoa, rua, estacao ou cancao.",
          items: [
            { id: "childhood-story", title: "Uma historia de infancia", authorLabel: "Pergunta do clube", tag: "Memoria", body: "Traga um livro escolar, cartao da biblioteca, historia de deitar ou primeiro poema.", discussionStarter: "Quem lhe leu algo em voz alta pela primeira vez?" },
            { id: "short-poem", title: "Um poema breve recordado", authorLabel: "Seguro para dominio publico", tag: "Poesia", body: "Partilhe o sentimento ou memoria, sem precisar de citacoes longas.", discussionStarter: "Que imagem de um poema ficou consigo?" },
          ],
        },
      ],
      spotlightsTitle: "Membros a mesa",
      memberSpotlights: [
        { memberId: members[0]?.id ?? "member-maria", name: spotlightNames[0], roleLine: "Memorias e historias familiares", body: "Procura alguem que goste de historias de dias comuns e grandes viragens.", starter: "Pergunte por uma historia familiar que ainda a faz sorrir." },
        { memberId: members[1]?.id ?? "member-jose", name: spotlightNames[1], roleLine: "Historia e biografias", body: "Trouxe uma pergunta sobre como a historia muda quando e contada pela memoria.", starter: "Pergunte que biografia pareceu mais viva." },
        { memberId: members[2]?.id ?? "member-carmen", name: spotlightNames[2], roleLine: "Teatro, historias e recomendacoes", body: "Gosta de trocar recomendacoes curtas e faceis de comecar.", starter: "Peca uma historia com final esperancoso." },
      ],
      companionTitle: "Encontre o seu lugar a mesa",
      companionBody: "Escolha o tipo de ligacao literaria que quer hoje. A Isabel mantem a apresentacao protegida.",
      companionModes: [
        { id: "one-to-one", title: "Uma pessoa leitora", body: "Uma saudacao privada e protegida com uma pessoa compativel.", ctaLabel: "Encontrar uma pessoa", bridgePrompt: "um livro, personagem ou memoria para partilhar a dois." },
        { id: "small-circle", title: "Pequeno circulo", body: "Uma mesa calma com duas ou tres pessoas sobre o mesmo tema.", ctaLabel: "Encontrar um circulo", bridgePrompt: "um tema para um pequeno circulo de leitura." },
        { id: "pen-note", title: "Nota escrita", body: "Comecar com uma saudacao escrita antes de qualquer conversa ao vivo.", ctaLabel: "Comecar com nota", bridgePrompt: "uma nota curta sobre um livro ou cena para trocar." },
      ],
      passportTitle: "Passaporte de leitura",
      passportBody: "Uma forma simples de completar a visita de hoje.",
      passportItems: [
        { id: "share", label: "Partilhar", body: "Adicione um livro, cena ou memoria a mesa do clube." },
        { id: "recommend", label: "Recomendar", body: "Deixe uma sugestao gentil para outra pessoa." },
        { id: "greet", label: "Saudar", body: "Envie uma saudacao protegida ou pedido de companhia." },
      ],
      reflectionTitle: "Adicionar a mesa do clube",
      reflectionPlaceholder: "Escreva um livro, cena, personagem ou memoria...",
      reflectionSubmitLabel: "Publicar reflexao",
      reflectionPrompts: [
        "Um livro que me fez companhia foi...",
        "Uma personagem que ainda recordo e...",
        "Uma historia que recomendaria com gentileza e...",
      ],
      guidelinesTitle: "Cuidado do clube",
      guidelines: [
        "Partilhe memorias e resumos por palavras suas.",
        "Use apenas excertos curtos quando forem uteis.",
        "Cada saudacao fica protegida ate ambas as pessoas concordarem.",
      ],
    },
  }, language);
}
